/* AUTO-GENERATED by scripts/gen-endpoint-maps.mjs from docs/api-reference/fluentforms/endpoints.json — do not edit by hand. */
import type { EndpointDef } from '../../core/types.js';

export const TOOL_ENDPOINTS: Record<string, Record<string, EndpointDef>> = {
  "forms_forms": {
    "list_forms": {
      "op": "forms/list-forms",
      "method": "GET",
      "path": "/forms",
      "summary": "List Forms",
      "destructive": false
    },
    "create_form": {
      "op": "forms/create-form",
      "method": "POST",
      "path": "/forms",
      "summary": "Create Form",
      "destructive": false
    },
    "ping": {
      "op": "forms/ping",
      "method": "GET",
      "path": "/forms/ping",
      "summary": "Ping Forms API",
      "destructive": false
    },
    "list_form_templates": {
      "op": "forms/list-form-templates",
      "method": "GET",
      "path": "/forms/templates",
      "summary": "List Form Templates",
      "destructive": false
    },
    "get_form": {
      "op": "forms/get-form",
      "method": "GET",
      "path": "/forms/{form_id}",
      "summary": "Get Form",
      "destructive": false
    },
    "update_form": {
      "op": "forms/update-form",
      "method": "POST",
      "path": "/forms/{form_id}",
      "summary": "Update Form",
      "destructive": false
    },
    "delete_form": {
      "op": "forms/delete-form",
      "method": "DELETE",
      "path": "/forms/{form_id}",
      "summary": "Delete Form",
      "destructive": true
    },
    "duplicate_form": {
      "op": "forms/duplicate-form",
      "method": "POST",
      "path": "/forms/{form_id}/duplicate",
      "summary": "Duplicate Form",
      "destructive": false
    },
    "convert_form": {
      "op": "forms/convert-form",
      "method": "POST",
      "path": "/forms/{form_id}/convert",
      "summary": "Convert Form Type (rewrites the form)",
      "destructive": true
    },
    "clear_form_edit_history": {
      "op": "forms/clear-form-edit-history",
      "method": "POST",
      "path": "/forms/{form_id}/clearHistory",
      "summary": "Clear Form Edit History",
      "destructive": true
    },
    "get_form_edit_history": {
      "op": "forms/get-form-edit-history",
      "method": "GET",
      "path": "/forms/{form_id}/editHistory",
      "summary": "Get Form Edit History",
      "destructive": false
    },
    "get_form_fields": {
      "op": "forms/get-form-fields",
      "method": "GET",
      "path": "/forms/{form_id}/fields",
      "summary": "Get Form Fields",
      "destructive": false
    },
    "find_form_shortcode_page": {
      "op": "forms/find-form-shortcode-page",
      "method": "GET",
      "path": "/forms/{form_id}/findShortCodePage",
      "summary": "Find Form Shortcode Page",
      "destructive": false
    },
    "list_form_pages": {
      "op": "forms/list-form-pages",
      "method": "GET",
      "path": "/forms/{form_id}/pages",
      "summary": "List Pages Embedding the Form",
      "destructive": false
    },
    "get_form_resources": {
      "op": "forms/get-form-resources",
      "method": "GET",
      "path": "/forms/{form_id}/resources",
      "summary": "Get Form Resources",
      "destructive": false
    },
    "get_form_shortcodes": {
      "op": "forms/get-form-shortcodes",
      "method": "GET",
      "path": "/forms/{form_id}/shortcodes",
      "summary": "Get Form Shortcodes",
      "destructive": false
    },
    "reset_form_analytics": {
      "op": "analytics/reset-form-analytics",
      "method": "POST",
      "path": "/analytics/{form_id}/reset",
      "summary": "Reset Form Analytics",
      "destructive": true
    }
  },
  "forms_submissions": {
    "list_submissions": {
      "op": "submissions/list-submissions",
      "method": "GET",
      "path": "/submissions",
      "summary": "List Submissions",
      "destructive": false
    },
    "list_all_submissions": {
      "op": "submissions/list-all-submissions",
      "method": "GET",
      "path": "/submissions/all",
      "summary": "List All Submissions",
      "destructive": false
    },
    "bulk_action_submissions": {
      "op": "submissions/bulk-action-submissions",
      "method": "POST",
      "path": "/submissions/bulk-actions",
      "summary": "Bulk Action Submissions",
      "destructive": true
    },
    "print_submissions": {
      "op": "submissions/print-submissions",
      "method": "GET",
      "path": "/submissions/print",
      "summary": "Print Submissions",
      "destructive": false
    },
    "get_submission_resources": {
      "op": "submissions/get-submission-resources",
      "method": "GET",
      "path": "/submissions/resources",
      "summary": "Get Submission Resources",
      "destructive": false
    },
    "get_submission": {
      "op": "submissions/get-submission",
      "method": "GET",
      "path": "/submissions/{entry_id}",
      "summary": "Get Submission",
      "destructive": false
    },
    "delete_submission": {
      "op": "submissions/delete-submission",
      "method": "DELETE",
      "path": "/submissions/{entry_id}",
      "summary": "Delete Submission",
      "destructive": true
    },
    "toggle_submission_favorite": {
      "op": "submissions/toggle-submission-favorite",
      "method": "POST",
      "path": "/submissions/{entry_id}/is-favorite",
      "summary": "Toggle Submission Favorite",
      "destructive": false
    },
    "get_submission_logs": {
      "op": "submissions/get-submission-logs",
      "method": "GET",
      "path": "/submissions/{entry_id}/logs",
      "summary": "Get Submission Logs",
      "destructive": false
    },
    "delete_submission_logs": {
      "op": "submissions/delete-submission-logs",
      "method": "DELETE",
      "path": "/submissions/{entry_id}/logs",
      "summary": "Delete Submission Logs",
      "destructive": true
    },
    "get_submission_notes": {
      "op": "submissions/get-submission-notes",
      "method": "GET",
      "path": "/submissions/{entry_id}/notes",
      "summary": "Get Submission Notes",
      "destructive": false
    },
    "create_submission_note": {
      "op": "submissions/create-submission-note",
      "method": "POST",
      "path": "/submissions/{entry_id}/notes",
      "summary": "Create Submission Note",
      "destructive": false
    },
    "update_submission_status": {
      "op": "submissions/update-submission-status",
      "method": "POST",
      "path": "/submissions/{entry_id}/status",
      "summary": "Update Submission Status",
      "destructive": false
    },
    "get_submission_users": {
      "op": "submissions/get-submission-users",
      "method": "GET",
      "path": "/submissions/{entry_id}/submission-users",
      "summary": "Get Submission Users",
      "destructive": false
    },
    "update_submission_user": {
      "op": "submissions/update-submission-user",
      "method": "POST",
      "path": "/submissions/{entry_id}/update-submission-user",
      "summary": "Update Submission User",
      "destructive": false
    },
    "submit_form": {
      "op": "form-submit/submit-form",
      "method": "POST",
      "path": "/form-submit",
      "summary": "Submit a Form Entry (public — fires notifications, integrations and payments)",
      "destructive": true,
      "bodyNote": "Public endpoint: this creates a REAL submission as an end user would, firing email notifications, integration feeds and payment processing. Body shape: {\"form_id\": <id>, \"data\": \"<url-encoded field=value pairs>\"} — the same payload the front-end form posts."
    },
    "query_submissions_report": {
      "op": "report/query-submissions-report",
      "method": "POST",
      "path": "/report/submissions",
      "summary": "Query Submissions Report (filtered read)",
      "destructive": false
    }
  },
  "forms_settings": {
    "get_form_settings": {
      "op": "settings/get-form-settings",
      "method": "GET",
      "path": "/settings/{form_id}",
      "summary": "Get Form Settings",
      "destructive": false
    },
    "save_form_settings": {
      "op": "settings/save-form-settings",
      "method": "POST",
      "path": "/settings/{form_id}",
      "summary": "Save Form Settings",
      "destructive": false
    },
    "delete_form_settings": {
      "op": "settings/delete-form-settings",
      "method": "DELETE",
      "path": "/settings/{form_id}",
      "summary": "Delete Form Settings",
      "destructive": true
    },
    "get_general_settings": {
      "op": "settings/get-general-settings",
      "method": "GET",
      "path": "/settings/{form_id}/general",
      "summary": "Get General Form Settings",
      "destructive": false
    },
    "save_general_settings": {
      "op": "settings/save-general-settings",
      "method": "POST",
      "path": "/settings/{form_id}/general",
      "summary": "Save General Form Settings",
      "destructive": false
    },
    "get_customizer_settings": {
      "op": "settings/get-customizer-settings",
      "method": "GET",
      "path": "/settings/{form_id}/customizer",
      "summary": "Get Form Customizer Settings",
      "destructive": false
    },
    "save_customizer_settings": {
      "op": "settings/save-customizer-settings",
      "method": "POST",
      "path": "/settings/{form_id}/customizer",
      "summary": "Save Form Customizer Settings",
      "destructive": false
    },
    "save_entry_columns": {
      "op": "settings/save-entry-columns",
      "method": "POST",
      "path": "/settings/{form_id}/entry-columns",
      "summary": "Save Entry Columns",
      "destructive": false
    },
    "get_conversational_design": {
      "op": "settings/get-conversational-design",
      "method": "GET",
      "path": "/settings/{form_id}/conversational-design",
      "summary": "Get Conversational Form Design",
      "destructive": false
    },
    "save_conversational_design": {
      "op": "settings/save-conversational-design",
      "method": "POST",
      "path": "/settings/{form_id}/store-conversational-design",
      "summary": "Save Conversational Form Design",
      "destructive": false
    },
    "get_form_preset": {
      "op": "settings/get-form-preset",
      "method": "GET",
      "path": "/settings/{form_id}/preset",
      "summary": "Get Form Style Preset",
      "destructive": false
    },
    "save_form_preset": {
      "op": "settings/save-form-preset",
      "method": "POST",
      "path": "/settings/{form_id}/save-preset",
      "summary": "Save Form Style Preset",
      "destructive": false
    }
  },
  "forms_integrations": {
    "list_global_integrations": {
      "op": "integrations/list-global-integrations",
      "method": "GET",
      "path": "/integrations",
      "summary": "List Global Integrations",
      "destructive": false
    },
    "save_global_integration": {
      "op": "integrations/save-global-integration",
      "method": "POST",
      "path": "/integrations",
      "summary": "Save Global Integration",
      "destructive": false
    },
    "update_integration_module_status": {
      "op": "integrations/update-integration-module-status",
      "method": "POST",
      "path": "/integrations/update-status",
      "summary": "Update Integration Module Status",
      "destructive": false
    },
    "get_form_integration": {
      "op": "integrations/get-form-integration",
      "method": "GET",
      "path": "/integrations/{form_id}",
      "summary": "Get Form Integration",
      "destructive": false,
      "bodyNote": "Pass query: {\"integration_id\": <feed id>, \"integration_name\": \"<slug>\"} — both come from forms_integrations_list (feed id, and provider minus the \"_feeds\" suffix). Without integration_id it returns that integration's default settings template, which is the shape to send to forms_integrations_save."
    },
    "save_form_integration": {
      "op": "integrations/save-form-integration",
      "method": "POST",
      "path": "/integrations/{form_id}",
      "summary": "Save Form Integration",
      "destructive": false,
      "bodyNote": "Body shape: {\"integration_name\": \"<registered slug>\", \"integration\": {\"name\": \"<feed name>\", \"enabled\": true, \"list_id\": …, \"merge_fields\"/other per-integration fields…, \"conditionals\": {\"status\": false, \"type\": \"all\", \"conditions\": []}}, \"integration_id\": <existing feed id to update, omit to create>}. integration_name MUST be one of the slugs in forms_integrations_list's available_integrations (e.g. \"fluentcrm\", \"fluent_support\", \"fluent_community\", \"wp_social_ninja\" — note the inconsistent underscores): Fluent Forms stores the feed under \"<integration_name>_feeds\" without checking the name, so a wrong slug saves a row the submission processor never runs. This tool refuses unregistered names before writing and returns the feed as Fluent Forms lists it (`stored`) after. Status-only toggle: {\"integration_id\": <id>, \"status\": false} with no \"integration\". Read an existing feed first with forms_integrations_get {query: {integration_id, integration_name}} and mirror its shape.",
      "readback": {
        "path": "/integrations/{form_id}/form-integrations",
        "allow": {
          "bodyField": "integration_name",
          "fromKey": "available_integrations",
          "requiredWhen": "integration"
        },
        "stored": {
          "itemsKey": "feeds",
          "idFrom": "integration_id"
        }
      }
    },
    "delete_form_integration": {
      "op": "integrations/delete-form-integration",
      "method": "DELETE",
      "path": "/integrations/{form_id}",
      "summary": "Delete Form Integration",
      "destructive": true,
      "bodyNote": "Pass query: {\"integration_id\": <feed id>} (from forms_integrations_list). The delete is scoped to form_id."
    },
    "list_form_integrations": {
      "op": "integrations/list-form-integrations",
      "method": "GET",
      "path": "/integrations/{form_id}/form-integrations",
      "summary": "List Form Integration Feeds (with available integration slugs)",
      "destructive": false
    },
    "get_integration_list_component": {
      "op": "integrations/get-integration-list-component",
      "method": "GET",
      "path": "/integrations/{form_id}/integration-list-id",
      "summary": "Get Integration List Component",
      "destructive": false
    }
  },
  "forms_reports": {
    "get_api_logs_report": {
      "op": "report/get-api-logs-report",
      "method": "GET",
      "path": "/report/api-logs",
      "summary": "Get API Logs Report",
      "destructive": false
    },
    "get_completion_rate": {
      "op": "report/get-completion-rate",
      "method": "GET",
      "path": "/report/completion-rate",
      "summary": "Get Form Completion Rate",
      "destructive": false
    },
    "get_country_heatmap": {
      "op": "report/get-country-heatmap",
      "method": "GET",
      "path": "/report/country-heatmap",
      "summary": "Get Country Heatmap",
      "destructive": false
    },
    "get_form_stats": {
      "op": "report/get-form-stats",
      "method": "GET",
      "path": "/report/form-stats",
      "summary": "Get Form Stats",
      "destructive": false
    },
    "get_form_report": {
      "op": "report/get-form-report",
      "method": "GET",
      "path": "/report/forms/{form_id}",
      "summary": "Get Form Report",
      "destructive": false
    },
    "get_heatmap_data": {
      "op": "report/get-heatmap-data",
      "method": "GET",
      "path": "/report/heatmap-data",
      "summary": "Get Heatmap Data",
      "destructive": false
    },
    "get_net_revenue": {
      "op": "report/get-net-revenue",
      "method": "GET",
      "path": "/report/net-revenue",
      "summary": "Get Net Revenue",
      "destructive": false
    },
    "get_overview_chart": {
      "op": "report/get-overview-chart",
      "method": "GET",
      "path": "/report/overview-chart",
      "summary": "Get Overview Chart",
      "destructive": false
    },
    "get_payment_types": {
      "op": "report/get-payment-types",
      "method": "GET",
      "path": "/report/payment-types",
      "summary": "Get Payment Types Report",
      "destructive": false
    },
    "get_revenue_chart": {
      "op": "report/get-revenue-chart",
      "method": "GET",
      "path": "/report/revenue-chart",
      "summary": "Get Revenue Chart",
      "destructive": false
    },
    "list_report_forms": {
      "op": "report/list-report-forms",
      "method": "GET",
      "path": "/report/select-forms",
      "summary": "List Forms for Reports",
      "destructive": false
    },
    "get_submissions_analysis": {
      "op": "report/get-submissions-analysis",
      "method": "GET",
      "path": "/report/submissions-analysis",
      "summary": "Get Submissions Analysis",
      "destructive": false
    },
    "get_subscriptions_report": {
      "op": "report/get-subscriptions-report",
      "method": "GET",
      "path": "/report/subscriptions",
      "summary": "Get Subscriptions Report",
      "destructive": false
    },
    "get_top_performing_forms": {
      "op": "report/get-top-performing-forms",
      "method": "GET",
      "path": "/report/top-performing-forms",
      "summary": "Get Top Performing Forms",
      "destructive": false
    }
  },
  "forms_admin": {
    "get_global_settings": {
      "op": "global-settings/get-global-settings",
      "method": "GET",
      "path": "/global-settings",
      "summary": "Get Global Settings",
      "destructive": false
    },
    "save_global_settings": {
      "op": "global-settings/save-global-settings",
      "method": "POST",
      "path": "/global-settings",
      "summary": "Save Global Settings",
      "destructive": false
    },
    "get_license": {
      "op": "license/get-license",
      "method": "GET",
      "path": "/license",
      "summary": "Get License Status",
      "destructive": false
    },
    "activate_license": {
      "op": "license/activate-license",
      "method": "POST",
      "path": "/license",
      "summary": "Activate License",
      "destructive": false
    },
    "deactivate_license": {
      "op": "license/deactivate-license",
      "method": "DELETE",
      "path": "/license",
      "summary": "Deactivate License",
      "destructive": true
    },
    "list_managers": {
      "op": "managers/list-managers",
      "method": "GET",
      "path": "/managers",
      "summary": "List Managers",
      "destructive": false
    },
    "add_manager": {
      "op": "managers/add-manager",
      "method": "POST",
      "path": "/managers",
      "summary": "Add Manager",
      "destructive": false
    },
    "remove_manager": {
      "op": "managers/remove-manager",
      "method": "DELETE",
      "path": "/managers",
      "summary": "Remove Manager",
      "destructive": true
    },
    "list_manager_users": {
      "op": "managers/list-manager-users",
      "method": "GET",
      "path": "/managers/users",
      "summary": "List Assignable Users",
      "destructive": false
    },
    "list_roles": {
      "op": "roles/list-roles",
      "method": "GET",
      "path": "/roles",
      "summary": "List Roles and Capabilities",
      "destructive": false
    },
    "add_role_capability": {
      "op": "roles/add-role-capability",
      "method": "POST",
      "path": "/roles",
      "summary": "Add Role Capability",
      "destructive": false
    }
  },
  "forms_utilities": {
    "list_logs": {
      "op": "logs/list-logs",
      "method": "GET",
      "path": "/logs",
      "summary": "List Logs",
      "destructive": false
    },
    "delete_logs": {
      "op": "logs/delete-logs",
      "method": "DELETE",
      "path": "/logs",
      "summary": "Delete Logs",
      "destructive": true
    },
    "get_log_filters": {
      "op": "logs/get-log-filters",
      "method": "GET",
      "path": "/logs/filters",
      "summary": "Get Log Filters",
      "destructive": false
    },
    "global_search": {
      "op": "global-search/global-search",
      "method": "GET",
      "path": "/global-search",
      "summary": "Global Search",
      "destructive": false
    },
    "handle_admin_notice": {
      "op": "notice/handle-admin-notice",
      "method": "POST",
      "path": "/notice",
      "summary": "Handle Admin Notice Action",
      "destructive": false
    },
    "check_plugin_statuses": {
      "op": "suggested-plugins/check-plugin-statuses",
      "method": "POST",
      "path": "/suggested-plugins/check-plugin-statuses",
      "summary": "Check Plugin Statuses",
      "destructive": false
    },
    "install_plugin": {
      "op": "suggested-plugins/install-plugin",
      "method": "POST",
      "path": "/suggested-plugins/install-plugin",
      "summary": "Install a WordPress Plugin",
      "destructive": true,
      "bodyNote": "Installs an ARBITRARY plugin from wordpress.org by slug ({\"plugin_slug\": \"...\"}) — the endpoint does not restrict the slug to Fluent Forms' suggestions."
    },
    "activate_plugin": {
      "op": "suggested-plugins/activate-plugin",
      "method": "POST",
      "path": "/suggested-plugins/activate-plugin",
      "summary": "Activate a WordPress Plugin",
      "destructive": true,
      "bodyNote": "Activates any installed plugin by slug ({\"plugin_slug\": \"...\"}) — i.e. starts executing its code on the site."
    },
    "get_mcp_status": {
      "op": "mcp/get-mcp-status",
      "method": "GET",
      "path": "/mcp/status",
      "summary": "Get MCP Adapter Status",
      "destructive": false
    },
    "toggle_mcp": {
      "op": "mcp/toggle-mcp",
      "method": "POST",
      "path": "/mcp/toggle",
      "summary": "Toggle MCP Adapter",
      "destructive": false
    },
    "install_mcp_adapter": {
      "op": "mcp/install-mcp-adapter",
      "method": "POST",
      "path": "/mcp/install-adapter",
      "summary": "Install the MCP Adapter Plugin",
      "destructive": true
    },
    "get_mcp_config_snippets": {
      "op": "mcp/get-mcp-config-snippets",
      "method": "GET",
      "path": "/mcp/config-snippets",
      "summary": "Get MCP Config Snippets",
      "destructive": false
    }
  }
};

export const TOOL_META: Record<string, { description: string; note?: string; idempotent?: boolean }> = {
  "forms_forms": {
    "description": "Create, read, update, duplicate, convert and delete forms, and inspect their fields, shortcodes, embedding pages and edit history."
  },
  "forms_submissions": {
    "description": "Read and manage form submissions (entries): filters, notes, logs, statuses, favorites, bulk actions, and the public submission endpoint."
  },
  "forms_settings": {
    "description": "Per-form settings: general options, confirmations, style customizer, entry columns, conversational design, and style presets."
  },
  "forms_integrations": {
    "description": "Connect forms to third-party services: global integration credentials and per-form integration feeds."
  },
  "forms_reports": {
    "description": "Read-only analytics for forms: submission counts, completion rates, revenue, payment types, heatmaps and top-performing forms."
  },
  "forms_admin": {
    "description": "Site-level Fluent Forms administration: global settings, licensing, managers and role capabilities.",
    "note": "The license endpoints require Fluent Forms Pro."
  },
  "forms_utilities": {
    "description": "Maintenance and helper operations: system logs, global search, admin notices, plugin install helpers, and the MCP adapter settings."
  }
};
