/* AUTO-GENERATED by scripts/gen-endpoint-maps.mjs from docs/api-reference/fluentcommunity/endpoints.json — do not edit by hand. */
import type { EndpointDef } from '../../core/types.js';

export const TOOL_ENDPOINTS: Record<string, Record<string, EndpointDef>> = {
  "community_spaces": {
    "create_cart_product": {
      "op": "spaces/create-cart-product",
      "method": "POST",
      "path": "/cart/products/create",
      "summary": "Create Cart Product",
      "destructive": false
    },
    "search_cart_products": {
      "op": "spaces/search-cart-products",
      "method": "GET",
      "path": "/cart/products/search",
      "summary": "Search Cart Products",
      "destructive": false
    },
    "delete_space_paywall": {
      "op": "spaces/delete-space-paywall",
      "method": "DELETE",
      "path": "/cart/spaces/{spaceId}/paywalls",
      "summary": "Delete Space Paywall",
      "destructive": true
    },
    "list_space_paywalls": {
      "op": "spaces/list-space-paywalls",
      "method": "GET",
      "path": "/cart/spaces/{spaceId}/paywalls",
      "summary": "List Space Paywalls",
      "destructive": false
    },
    "create_space_paywall": {
      "op": "spaces/create-space-paywall",
      "method": "POST",
      "path": "/cart/spaces/{spaceId}/paywalls",
      "summary": "Create Space Paywall",
      "destructive": false
    },
    "get_space_media_gallery": {
      "op": "spaces/get-space-media-gallery",
      "method": "GET",
      "path": "/media-gallery/{spaceSlug}",
      "summary": "Get Space Media Gallery",
      "destructive": false
    },
    "list_spaces": {
      "op": "spaces/list-spaces",
      "method": "GET",
      "path": "/spaces",
      "summary": "List Spaces",
      "destructive": false
    },
    "create_space": {
      "op": "spaces/create-space",
      "method": "POST",
      "path": "/spaces",
      "summary": "Create Space",
      "destructive": false
    },
    "list_all_spaces": {
      "op": "spaces/list-all-spaces",
      "method": "GET",
      "path": "/spaces/all-spaces",
      "summary": "List All Spaces",
      "destructive": false
    },
    "list_discoverable_spaces": {
      "op": "spaces/list-discoverable-spaces",
      "method": "GET",
      "path": "/spaces/discover",
      "summary": "List Discoverable Spaces",
      "destructive": false
    },
    "list_space_groups": {
      "op": "spaces/list-space-groups",
      "method": "GET",
      "path": "/spaces/space_groups",
      "summary": "List Space Groups",
      "destructive": false
    },
    "create_space_group": {
      "op": "spaces/create-space-group",
      "method": "POST",
      "path": "/spaces/space_groups",
      "summary": "Create Space Group",
      "destructive": false
    },
    "move_space_to_group": {
      "op": "spaces/move-space-to-group",
      "method": "PATCH",
      "path": "/spaces/space_groups/move-space",
      "summary": "Move Space To Group",
      "destructive": false
    },
    "reindex_space_groups": {
      "op": "spaces/reindex-space-groups",
      "method": "PATCH",
      "path": "/spaces/space_groups/re-index",
      "summary": "Reindex Space Groups",
      "destructive": false
    },
    "reindex_spaces_in_groups": {
      "op": "spaces/reindex-spaces-in-groups",
      "method": "PATCH",
      "path": "/spaces/space_groups/re-index-spaces",
      "summary": "Reindex Spaces In Groups",
      "destructive": false
    },
    "delete_space_group": {
      "op": "spaces/delete-space-group",
      "method": "DELETE",
      "path": "/spaces/space_groups/{id}",
      "summary": "Delete Space Group",
      "destructive": true
    },
    "update_space_group": {
      "op": "spaces/update-space-group",
      "method": "PUT",
      "path": "/spaces/space_groups/{id}",
      "summary": "Update Space Group",
      "destructive": false
    },
    "search_space_users": {
      "op": "spaces/search-space-users",
      "method": "GET",
      "path": "/spaces/users/search",
      "summary": "Search Space Users",
      "destructive": false
    },
    "delete_space_by_id": {
      "op": "spaces/delete-space-by-id",
      "method": "DELETE",
      "path": "/spaces/{spaceId}/by-id",
      "summary": "Delete Space By ID",
      "destructive": true
    },
    "update_space_by_id": {
      "op": "spaces/update-space-by-id",
      "method": "PUT",
      "path": "/spaces/{spaceId}/by-id",
      "summary": "Update Space By ID",
      "destructive": false
    },
    "delete_space_by_slug": {
      "op": "spaces/delete-space-by-slug",
      "method": "DELETE",
      "path": "/spaces/{spaceSlug}",
      "summary": "Delete Space By Slug",
      "destructive": true
    },
    "get_space_by_slug": {
      "op": "spaces/get-space-by-slug",
      "method": "GET",
      "path": "/spaces/{spaceSlug}/by-slug",
      "summary": "Get Space By Slug",
      "destructive": false
    },
    "update_space_by_slug": {
      "op": "spaces/update-space-by-slug",
      "method": "PUT",
      "path": "/spaces/{spaceSlug}/by-slug",
      "summary": "Update Space By Slug",
      "destructive": false
    },
    "join_space": {
      "op": "spaces/join-space",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/join",
      "summary": "Join Space",
      "destructive": false
    },
    "leave_space": {
      "op": "spaces/leave-space",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/leave",
      "summary": "Leave Space",
      "destructive": false
    },
    "create_space_link": {
      "op": "spaces/create-space-link",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/links",
      "summary": "Create Space Link",
      "destructive": false
    },
    "get_space_lockscreens": {
      "op": "spaces/get-space-lockscreens",
      "method": "GET",
      "path": "/spaces/{spaceSlug}/lockscreens",
      "summary": "Get Space Lockscreens",
      "destructive": false
    },
    "update_space_lockscreens": {
      "op": "spaces/update-space-lockscreens",
      "method": "PUT",
      "path": "/spaces/{spaceSlug}/lockscreens",
      "summary": "Update Space Lockscreens",
      "destructive": false
    },
    "list_space_members": {
      "op": "spaces/list-space-members",
      "method": "GET",
      "path": "/spaces/{spaceSlug}/members",
      "summary": "List Space Members",
      "destructive": false
    },
    "add_space_member": {
      "op": "spaces/add-space-member",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/members",
      "summary": "Add Space Member",
      "destructive": false
    },
    "bulk_add_space_members": {
      "op": "spaces/bulk-add-space-members",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/members/bulk-add",
      "summary": "Bulk Add Space Members",
      "destructive": true
    },
    "bulk_import_space_members": {
      "op": "spaces/bulk-import-space-members",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/members/bulk-import",
      "summary": "Bulk Import Space Members",
      "destructive": true
    },
    "remove_space_member": {
      "op": "spaces/remove-space-member",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/members/remove",
      "summary": "Remove Space Member",
      "destructive": true
    },
    "resolve_space_member_crm_tag": {
      "op": "spaces/resolve-space-member-crm-tag",
      "method": "POST",
      "path": "/spaces/{spaceSlug}/members/resolve-crm-tag",
      "summary": "Resolve Space Member CRM Tag",
      "destructive": false
    },
    "get_space_meta_settings": {
      "op": "spaces/get-space-meta-settings",
      "method": "GET",
      "path": "/spaces/{spaceSlug}/meta-settings",
      "summary": "Get Space Meta Settings",
      "destructive": false
    }
  },
  "community_feeds": {
    "list_activities": {
      "op": "feeds/list-activities",
      "method": "GET",
      "path": "/activities",
      "summary": "List Activities",
      "destructive": false
    },
    "list_comment_reactions": {
      "op": "feeds/list-comment-reactions",
      "method": "GET",
      "path": "/comments/{comment_id}/reactions",
      "summary": "List Comment Reactions",
      "destructive": false
    },
    "get_comment": {
      "op": "feeds/get-comment",
      "method": "GET",
      "path": "/comments/{id}",
      "summary": "Get Comment",
      "destructive": false
    },
    "list_documents": {
      "op": "feeds/list-documents",
      "method": "GET",
      "path": "/documents",
      "summary": "List Documents",
      "destructive": false
    },
    "delete_document": {
      "op": "feeds/delete-document",
      "method": "POST",
      "path": "/documents/delete",
      "summary": "Delete Document",
      "destructive": true
    },
    "update_document": {
      "op": "feeds/update-document",
      "method": "POST",
      "path": "/documents/update",
      "summary": "Update Document",
      "destructive": false
    },
    "upload_document": {
      "op": "feeds/upload-document",
      "method": "POST",
      "path": "/documents/upload",
      "summary": "Upload Document",
      "destructive": false
    },
    "list_feeds": {
      "op": "feeds/list-feeds",
      "method": "GET",
      "path": "/feeds",
      "summary": "List Feeds",
      "destructive": false
    },
    "create_feed": {
      "op": "feeds/create-feed",
      "method": "POST",
      "path": "/feeds",
      "summary": "Create Feed",
      "destructive": false
    },
    "batch_create_feeds": {
      "op": "feeds/batch-create-feeds",
      "method": "POST",
      "path": "/feeds/batch",
      "summary": "Batch Create Feeds (mass post creation)",
      "destructive": true
    },
    "list_bookmarked_feeds": {
      "op": "feeds/list-bookmarked-feeds",
      "method": "GET",
      "path": "/feeds/bookmarks",
      "summary": "List Bookmarked Feeds",
      "destructive": false
    },
    "list_feed_links": {
      "op": "feeds/list-feed-links",
      "method": "GET",
      "path": "/feeds/links",
      "summary": "List Feed Links",
      "destructive": false
    },
    "create_feed_link": {
      "op": "feeds/create-feed-link",
      "method": "POST",
      "path": "/feeds/links",
      "summary": "Create Feed Link",
      "destructive": false
    },
    "preview_feed_markdown": {
      "op": "feeds/preview-feed-markdown",
      "method": "POST",
      "path": "/feeds/markdown-preview",
      "summary": "Preview Feed Markdown",
      "destructive": false
    },
    "upload_feed_media": {
      "op": "feeds/upload-feed-media",
      "method": "POST",
      "path": "/feeds/media-upload",
      "summary": "Upload Feed Media",
      "destructive": false
    },
    "get_feed_oembed": {
      "op": "feeds/get-feed-oembed",
      "method": "GET",
      "path": "/feeds/oembed",
      "summary": "Get Feed oEmbed",
      "destructive": false
    },
    "get_feed_ticker": {
      "op": "feeds/get-feed-ticker",
      "method": "GET",
      "path": "/feeds/ticker",
      "summary": "Get Feed Ticker",
      "destructive": false
    },
    "get_feed_ticker_updates": {
      "op": "feeds/get-feed-ticker-updates",
      "method": "GET",
      "path": "/feeds/ticker-updates",
      "summary": "Get Feed Ticker Updates",
      "destructive": false
    },
    "get_feed_welcome_banner": {
      "op": "feeds/get-feed-welcome-banner",
      "method": "GET",
      "path": "/feeds/welcome-banner",
      "summary": "Get Feed Welcome Banner",
      "destructive": false
    },
    "delete_feed": {
      "op": "feeds/delete-feed",
      "method": "DELETE",
      "path": "/feeds/{feed_id}",
      "summary": "Delete Feed",
      "destructive": true
    },
    "patch_feed": {
      "op": "feeds/patch-feed",
      "method": "PATCH",
      "path": "/feeds/{feed_id}",
      "summary": "Patch Feed",
      "destructive": false
    },
    "update_feed": {
      "op": "feeds/update-feed",
      "method": "POST",
      "path": "/feeds/{feed_id}",
      "summary": "Update Feed",
      "destructive": false
    },
    "vote_in_feed_survey": {
      "op": "feeds/vote-in-feed-survey",
      "method": "POST",
      "path": "/feeds/{feed_id}/apps/survey-vote",
      "summary": "Vote In Feed Survey",
      "destructive": false
    },
    "list_feed_survey_voters": {
      "op": "feeds/list-feed-survey-voters",
      "method": "GET",
      "path": "/feeds/{feed_id}/apps/survey-voters/{option_slug}",
      "summary": "List Feed Survey Voters",
      "destructive": false
    },
    "get_feed_by_id": {
      "op": "feeds/get-feed-by-id",
      "method": "GET",
      "path": "/feeds/{feed_id}/by-id",
      "summary": "Get Feed By ID",
      "destructive": false
    },
    "list_feed_comments": {
      "op": "feeds/list-feed-comments",
      "method": "GET",
      "path": "/feeds/{feed_id}/comments",
      "summary": "List Feed Comments",
      "destructive": false
    },
    "create_feed_comment": {
      "op": "feeds/create-feed-comment",
      "method": "POST",
      "path": "/feeds/{feed_id}/comments",
      "summary": "Create Feed Comment",
      "destructive": false
    },
    "delete_feed_comment": {
      "op": "feeds/delete-feed-comment",
      "method": "DELETE",
      "path": "/feeds/{feed_id}/comments/{comment_id}",
      "summary": "Delete Feed Comment",
      "destructive": true
    },
    "patch_feed_comment": {
      "op": "feeds/patch-feed-comment",
      "method": "PATCH",
      "path": "/feeds/{feed_id}/comments/{comment_id}",
      "summary": "Patch Feed Comment",
      "destructive": false
    },
    "update_feed_comment": {
      "op": "feeds/update-feed-comment",
      "method": "POST",
      "path": "/feeds/{feed_id}/comments/{comment_id}",
      "summary": "Update Feed Comment",
      "destructive": false
    },
    "react_to_feed_comment": {
      "op": "feeds/react-to-feed-comment",
      "method": "POST",
      "path": "/feeds/{feed_id}/comments/{comment_id}/reactions",
      "summary": "React To Feed Comment",
      "destructive": false
    },
    "delete_feed_media_preview": {
      "op": "feeds/delete-feed-media-preview",
      "method": "DELETE",
      "path": "/feeds/{feed_id}/media-preview",
      "summary": "Delete Feed Media Preview",
      "destructive": true
    },
    "react_to_feed": {
      "op": "feeds/react-to-feed",
      "method": "POST",
      "path": "/feeds/{feed_id}/react",
      "summary": "React To Feed",
      "destructive": false
    },
    "list_feed_reactions": {
      "op": "feeds/list-feed-reactions",
      "method": "GET",
      "path": "/feeds/{feed_id}/reactions",
      "summary": "List Feed Reactions",
      "destructive": false
    },
    "toggle_feed_reaction": {
      "op": "feeds/toggle-feed-reaction",
      "method": "POST",
      "path": "/feeds/{feed_id}/reactions/toggle",
      "summary": "Toggle Feed Reaction",
      "destructive": false
    },
    "get_feed_by_slug": {
      "op": "feeds/get-feed-by-slug",
      "method": "GET",
      "path": "/feeds/{feed_slug}/by-slug",
      "summary": "Get Feed By Slug",
      "destructive": false
    },
    "save_player_audio_media": {
      "op": "feeds/save-player-audio-media",
      "method": "POST",
      "path": "/fluent-player/audio-media/{media_id}",
      "summary": "Save Player Audio Media",
      "destructive": false
    },
    "get_player_video_content": {
      "op": "feeds/get-player-video-content",
      "method": "GET",
      "path": "/fluent-player/video-content/{media_id}",
      "summary": "Get Player Video Content",
      "destructive": false
    },
    "upload_player_video": {
      "op": "feeds/upload-player-video",
      "method": "POST",
      "path": "/fluent-player/video-upload",
      "summary": "Upload Player Video",
      "destructive": false
    },
    "save_moderation_config": {
      "op": "feeds/save-moderation-config",
      "method": "POST",
      "path": "/moderation/config",
      "summary": "Save Moderation Config",
      "destructive": false
    },
    "report_content": {
      "op": "feeds/report-content",
      "method": "POST",
      "path": "/moderation/report",
      "summary": "Report Content",
      "destructive": false
    },
    "list_scheduled_posts": {
      "op": "feeds/list-scheduled-posts",
      "method": "GET",
      "path": "/scheduled-posts",
      "summary": "List Scheduled Posts",
      "destructive": false
    },
    "publish_scheduled_post": {
      "op": "feeds/publish-scheduled-post",
      "method": "POST",
      "path": "/scheduled-posts/publish/{feed_id}",
      "summary": "Publish Scheduled Post",
      "destructive": false
    },
    "update_scheduled_post": {
      "op": "feeds/update-scheduled-post",
      "method": "PUT",
      "path": "/scheduled-posts/{feed_id}",
      "summary": "Update Scheduled Post",
      "destructive": false
    }
  },
  "community_chat": {
    "get_chat_broadcast_auth": {
      "op": "chat/get-chat-broadcast-auth",
      "method": "GET",
      "path": "/chat/broadcast/auth",
      "summary": "Get Chat Broadcast Auth",
      "destructive": false
    },
    "save_chat_broadcast_auth": {
      "op": "chat/save-chat-broadcast-auth",
      "method": "POST",
      "path": "/chat/broadcast/auth",
      "summary": "Save Chat Broadcast Auth",
      "destructive": false
    },
    "create_chat_group": {
      "op": "chat/create-chat-group",
      "method": "POST",
      "path": "/chat/groups",
      "summary": "Create Chat Group",
      "destructive": false
    },
    "update_chat_group": {
      "op": "chat/update-chat-group",
      "method": "POST",
      "path": "/chat/groups/{thread_id}",
      "summary": "Update Chat Group",
      "destructive": false
    },
    "delete_chat_group": {
      "op": "chat/delete-chat-group",
      "method": "POST",
      "path": "/chat/groups/{thread_id}/delete",
      "summary": "Delete Chat Group",
      "destructive": true
    },
    "leave_chat_group": {
      "op": "chat/leave-chat-group",
      "method": "POST",
      "path": "/chat/groups/{thread_id}/leave",
      "summary": "Leave Chat Group",
      "destructive": false
    },
    "list_chat_group_members": {
      "op": "chat/list-chat-group-members",
      "method": "GET",
      "path": "/chat/groups/{thread_id}/members",
      "summary": "List Chat Group Members",
      "destructive": false
    },
    "add_chat_group_members": {
      "op": "chat/add-chat-group-members",
      "method": "POST",
      "path": "/chat/groups/{thread_id}/members",
      "summary": "Add Chat Group Members",
      "destructive": false
    },
    "promote_chat_group_member_to_admin": {
      "op": "chat/promote-chat-group-member-to-admin",
      "method": "POST",
      "path": "/chat/groups/{thread_id}/members/{member_id}/admin",
      "summary": "Promote Chat Group Member to Admin (no demote endpoint exists)",
      "destructive": true
    },
    "remove_chat_group_member": {
      "op": "chat/remove-chat-group-member",
      "method": "POST",
      "path": "/chat/groups/{thread_id}/members/{member_id}/remove",
      "summary": "Remove Chat Group Member",
      "destructive": true
    },
    "delete_chat_message": {
      "op": "chat/delete-chat-message",
      "method": "POST",
      "path": "/chat/messages/delete/{message_id}",
      "summary": "Delete Chat Message",
      "destructive": true
    },
    "react_to_chat_message": {
      "op": "chat/react-to-chat-message",
      "method": "POST",
      "path": "/chat/messages/{message_id}/react",
      "summary": "React To Chat Message",
      "destructive": false
    },
    "list_chat_messages": {
      "op": "chat/list-chat-messages",
      "method": "GET",
      "path": "/chat/messages/{thread_id}",
      "summary": "List Chat Messages",
      "destructive": false
    },
    "send_chat_message": {
      "op": "chat/send-chat-message",
      "method": "POST",
      "path": "/chat/messages/{thread_id}",
      "summary": "Send Chat Message",
      "destructive": false
    },
    "upload_chat_message_media": {
      "op": "chat/upload-chat-message-media",
      "method": "POST",
      "path": "/chat/messages/{thread_id}/media_upload",
      "summary": "Upload Chat Message Media",
      "destructive": false
    },
    "list_new_chat_messages": {
      "op": "chat/list-new-chat-messages",
      "method": "GET",
      "path": "/chat/messages/{thread_id}/new",
      "summary": "List New Chat Messages",
      "destructive": false
    },
    "mark_chat_threads_read": {
      "op": "chat/mark-chat-threads-read",
      "method": "POST",
      "path": "/chat/read-threads",
      "summary": "Mark Chat Threads Read",
      "destructive": false
    },
    "list_chat_threads": {
      "op": "chat/list-chat-threads",
      "method": "GET",
      "path": "/chat/threads",
      "summary": "List Chat Threads",
      "destructive": false
    },
    "create_chat_thread": {
      "op": "chat/create-chat-thread",
      "method": "POST",
      "path": "/chat/threads",
      "summary": "Create Chat Thread",
      "destructive": false
    },
    "block_chat_thread": {
      "op": "chat/block-chat-thread",
      "method": "POST",
      "path": "/chat/threads/block/{thread_id}",
      "summary": "Block Chat Thread",
      "destructive": false
    },
    "delete_chat_thread": {
      "op": "chat/delete-chat-thread",
      "method": "POST",
      "path": "/chat/threads/delete/{thread_id}",
      "summary": "Delete Chat Thread",
      "destructive": true
    },
    "join_chat_thread": {
      "op": "chat/join-chat-thread",
      "method": "POST",
      "path": "/chat/threads/join/{thread_id}",
      "summary": "Join Chat Thread",
      "destructive": false
    },
    "leave_chat_thread": {
      "op": "chat/leave-chat-thread",
      "method": "POST",
      "path": "/chat/threads/leave/{thread_id}",
      "summary": "Leave Chat Thread",
      "destructive": false
    },
    "unblock_chat_thread": {
      "op": "chat/unblock-chat-thread",
      "method": "POST",
      "path": "/chat/threads/unblock/{thread_id}",
      "summary": "Unblock Chat Thread",
      "destructive": false
    },
    "get_chat_thread": {
      "op": "chat/get-chat-thread",
      "method": "GET",
      "path": "/chat/threads/{thread_id}",
      "summary": "Get Chat Thread",
      "destructive": false
    },
    "list_chat_thread_members": {
      "op": "chat/list-chat-thread-members",
      "method": "GET",
      "path": "/chat/threads/{thread_id}/members",
      "summary": "List Chat Thread Members",
      "destructive": false
    },
    "block_chat_thread_member": {
      "op": "chat/block-chat-thread-member",
      "method": "POST",
      "path": "/chat/threads/{thread_id}/members/{member_id}/block-chat",
      "summary": "Block Chat Thread Member",
      "destructive": false
    },
    "unblock_chat_thread_member": {
      "op": "chat/unblock-chat-thread-member",
      "method": "POST",
      "path": "/chat/threads/{thread_id}/members/{member_id}/unblock-chat",
      "summary": "Unblock Chat Thread Member",
      "destructive": false
    },
    "list_unread_chat_threads": {
      "op": "chat/list-unread-chat-threads",
      "method": "GET",
      "path": "/chat/unread_threads",
      "summary": "List Unread Chat Threads",
      "destructive": false
    },
    "list_chat_users": {
      "op": "chat/list-chat-users",
      "method": "GET",
      "path": "/chat/users",
      "summary": "List Chat Users",
      "destructive": false
    }
  },
  "community_courses": {
    "list_all_space_courses": {
      "op": "courses/list-all-space-courses",
      "method": "GET",
      "path": "/admin/all_space_courses",
      "summary": "List Courses Across All Spaces",
      "destructive": false,
      "toolName": "community_courses_list_all_space_courses"
    },
    "list_managed_courses": {
      "op": "courses/list-managed-courses",
      "method": "GET",
      "path": "/admin/courses",
      "summary": "List Managed Courses",
      "destructive": false
    },
    "create_course": {
      "op": "courses/create-course",
      "method": "POST",
      "path": "/admin/courses",
      "summary": "Create Course",
      "destructive": false
    },
    "delete_course": {
      "op": "courses/delete-course",
      "method": "DELETE",
      "path": "/admin/courses/{course_id}",
      "summary": "Delete Course",
      "destructive": true
    },
    "get_managed_course": {
      "op": "courses/get-managed-course",
      "method": "GET",
      "path": "/admin/courses/{course_id}",
      "summary": "Get Managed Course",
      "destructive": false
    },
    "update_course": {
      "op": "courses/update-course",
      "method": "PUT",
      "path": "/admin/courses/{course_id}",
      "summary": "Update Course",
      "destructive": false
    },
    "list_course_comments": {
      "op": "courses/list-course-comments",
      "method": "GET",
      "path": "/admin/courses/{course_id}/comments",
      "summary": "List Course Comments",
      "destructive": false
    },
    "copy_course_section": {
      "op": "courses/copy-course-section",
      "method": "PUT",
      "path": "/admin/courses/{course_id}/copy-section",
      "summary": "Copy Course Section",
      "destructive": false
    },
    "duplicate_course": {
      "op": "courses/duplicate-course",
      "method": "POST",
      "path": "/admin/courses/{course_id}/duplicate",
      "summary": "Duplicate Course",
      "destructive": false
    },
    "export_course_quiz_results": {
      "op": "courses/export-course-quiz-results",
      "method": "GET",
      "path": "/admin/courses/{course_id}/export/quiz-results",
      "summary": "Export Course Quiz Results",
      "destructive": false
    },
    "export_course_students": {
      "op": "courses/export-course-students",
      "method": "GET",
      "path": "/admin/courses/{course_id}/export/students",
      "summary": "Export Course Students",
      "destructive": false
    },
    "search_course_instructors": {
      "op": "courses/search-course-instructors",
      "method": "GET",
      "path": "/admin/courses/{course_id}/instructors/search",
      "summary": "Search Course Instructors",
      "destructive": false
    },
    "list_course_lessons": {
      "op": "courses/list-course-lessons",
      "method": "GET",
      "path": "/admin/courses/{course_id}/lessons",
      "summary": "List Course Lessons",
      "destructive": false
    },
    "create_course_lesson": {
      "op": "courses/create-course-lesson",
      "method": "POST",
      "path": "/admin/courses/{course_id}/lessons",
      "summary": "Create Course Lesson",
      "destructive": false
    },
    "delete_course_lesson": {
      "op": "courses/delete-course-lesson",
      "method": "DELETE",
      "path": "/admin/courses/{course_id}/lessons/{lesson_id}",
      "summary": "Delete Course Lesson",
      "destructive": true
    },
    "get_course_lesson": {
      "op": "courses/get-course-lesson",
      "method": "GET",
      "path": "/admin/courses/{course_id}/lessons/{lesson_id}",
      "summary": "Get Course Lesson",
      "destructive": false
    },
    "patch_course_lesson": {
      "op": "courses/patch-course-lesson",
      "method": "PATCH",
      "path": "/admin/courses/{course_id}/lessons/{lesson_id}",
      "summary": "Patch Course Lesson",
      "destructive": false
    },
    "update_course_lesson": {
      "op": "courses/update-course-lesson",
      "method": "PUT",
      "path": "/admin/courses/{course_id}/lessons/{lesson_id}",
      "summary": "Update Course Lesson",
      "destructive": false
    },
    "duplicate_course_lesson": {
      "op": "courses/duplicate-course-lesson",
      "method": "POST",
      "path": "/admin/courses/{course_id}/lessons/{lesson_id}/duplicate",
      "summary": "Duplicate Course Lesson",
      "destructive": false
    },
    "create_course_link": {
      "op": "courses/create-course-link",
      "method": "POST",
      "path": "/admin/courses/{course_id}/links",
      "summary": "Create Course Link",
      "destructive": false
    },
    "update_course_lockscreen": {
      "op": "courses/update-course-lockscreen",
      "method": "PUT",
      "path": "/admin/courses/{course_id}/lockscreens",
      "summary": "Update Course Lockscreen",
      "destructive": false
    },
    "get_course_meta_settings": {
      "op": "courses/get-course-meta-settings",
      "method": "GET",
      "path": "/admin/courses/{course_id}/meta-settings",
      "summary": "Get Course Meta Settings",
      "destructive": false
    },
    "move_course_lesson": {
      "op": "courses/move-course-lesson",
      "method": "PUT",
      "path": "/admin/courses/{course_id}/move-lesson",
      "summary": "Move Course Lesson",
      "destructive": false
    },
    "list_course_quiz_results": {
      "op": "courses/list-course-quiz-results",
      "method": "GET",
      "path": "/admin/courses/{course_id}/quiz-results",
      "summary": "List Course Quiz Results",
      "destructive": false
    },
    "save_course_quiz_result": {
      "op": "courses/save-course-quiz-result",
      "method": "POST",
      "path": "/admin/courses/{course_id}/quiz-results/{quiz_id}",
      "summary": "Save Course Quiz Result",
      "destructive": false
    },
    "list_course_sections": {
      "op": "courses/list-course-sections",
      "method": "GET",
      "path": "/admin/courses/{course_id}/sections",
      "summary": "List Course Sections",
      "destructive": false
    },
    "create_course_section": {
      "op": "courses/create-course-section",
      "method": "POST",
      "path": "/admin/courses/{course_id}/sections",
      "summary": "Create Course Section",
      "destructive": false
    },
    "reorder_course_sections": {
      "op": "courses/reorder-course-sections",
      "method": "PATCH",
      "path": "/admin/courses/{course_id}/sections/indexes",
      "summary": "Reorder Course Sections",
      "destructive": false
    },
    "delete_course_section": {
      "op": "courses/delete-course-section",
      "method": "DELETE",
      "path": "/admin/courses/{course_id}/sections/{section_id}",
      "summary": "Delete Course Section",
      "destructive": true
    },
    "get_course_section": {
      "op": "courses/get-course-section",
      "method": "GET",
      "path": "/admin/courses/{course_id}/sections/{section_id}",
      "summary": "Get Course Section",
      "destructive": false
    },
    "patch_course_section": {
      "op": "courses/patch-course-section",
      "method": "PATCH",
      "path": "/admin/courses/{course_id}/sections/{section_id}",
      "summary": "Patch Course Section",
      "destructive": false
    },
    "update_course_section": {
      "op": "courses/update-course-section",
      "method": "PUT",
      "path": "/admin/courses/{course_id}/sections/{section_id}",
      "summary": "Update Course Section",
      "destructive": false
    },
    "reorder_course_section_lessons": {
      "op": "courses/reorder-course-section-lessons",
      "method": "PATCH",
      "path": "/admin/courses/{course_id}/sections/{section_id}/indexes",
      "summary": "Reorder Course Section Lessons",
      "destructive": false
    },
    "list_course_students": {
      "op": "courses/list-course-students",
      "method": "GET",
      "path": "/admin/courses/{course_id}/students",
      "summary": "List Course Students",
      "destructive": false
    },
    "add_course_student": {
      "op": "courses/add-course-student",
      "method": "POST",
      "path": "/admin/courses/{course_id}/students",
      "summary": "Add Course Student",
      "destructive": false
    },
    "bulk_add_course_students": {
      "op": "courses/bulk-add-course-students",
      "method": "POST",
      "path": "/admin/courses/{course_id}/students/bulk-add",
      "summary": "Bulk Add Course Students",
      "destructive": true
    },
    "bulk_import_course_students": {
      "op": "courses/bulk-import-course-students",
      "method": "POST",
      "path": "/admin/courses/{course_id}/students/bulk-import",
      "summary": "Bulk Import Course Students",
      "destructive": true
    },
    "resolve_course_student_crm_tag": {
      "op": "courses/resolve-course-student-crm-tag",
      "method": "POST",
      "path": "/admin/courses/{course_id}/students/resolve-crm-tag",
      "summary": "Resolve Course Student CRM Tag",
      "destructive": false
    },
    "delete_course_student": {
      "op": "courses/delete-course-student",
      "method": "DELETE",
      "path": "/admin/courses/{course_id}/students/{student_id}",
      "summary": "Delete Course Student",
      "destructive": true
    },
    "delete_student_course_progress": {
      "op": "courses/delete-student-course-progress",
      "method": "DELETE",
      "path": "/admin/courses/{course_id}/students/{student_id}/progress",
      "summary": "Delete Student Course Progress",
      "destructive": true
    },
    "search_course_users": {
      "op": "courses/search-course-users",
      "method": "GET",
      "path": "/admin/courses/{course_id}/users/search",
      "summary": "Search Course Users",
      "destructive": false
    },
    "get_course_welcome_banner": {
      "op": "courses/get-course-welcome-banner",
      "method": "GET",
      "path": "/admin/courses/{course_id}/welcome-banner",
      "summary": "Get Course Welcome Banner",
      "destructive": false
    },
    "save_course_welcome_banner": {
      "op": "courses/save-course-welcome-banner",
      "method": "POST",
      "path": "/admin/courses/{course_id}/welcome-banner",
      "summary": "Save Course Welcome Banner",
      "destructive": false
    },
    "list_courses": {
      "op": "courses/list-courses",
      "method": "GET",
      "path": "/courses",
      "summary": "List Courses",
      "destructive": false
    },
    "list_all_courses": {
      "op": "courses/list-all-courses",
      "method": "GET",
      "path": "/courses/all-courses",
      "summary": "List All Courses",
      "destructive": false
    },
    "get_course": {
      "op": "courses/get-course",
      "method": "GET",
      "path": "/courses/{course_id}",
      "summary": "Get Course",
      "destructive": false
    },
    "enroll_in_course": {
      "op": "courses/enroll-in-course",
      "method": "POST",
      "path": "/courses/{course_id}/enroll",
      "summary": "Enroll In Course",
      "destructive": false
    },
    "update_course_lesson_completion": {
      "op": "courses/update-course-lesson-completion",
      "method": "PUT",
      "path": "/courses/{course_id}/lessons/{lesson_id}/completion",
      "summary": "Update Course Lesson Completion",
      "destructive": false
    },
    "get_course_lesson_quiz_result": {
      "op": "courses/get-course-lesson-quiz-result",
      "method": "GET",
      "path": "/courses/{course_id}/lessons/{lesson_id}/quiz/result",
      "summary": "Get Course Lesson Quiz Result",
      "destructive": false
    },
    "submit_course_lesson_quiz": {
      "op": "courses/submit-course-lesson-quiz",
      "method": "POST",
      "path": "/courses/{course_id}/lessons/{lesson_id}/quiz/submit",
      "summary": "Submit Course Lesson Quiz",
      "destructive": false
    },
    "mark_course_lesson_video_watched": {
      "op": "courses/mark-course-lesson-video-watched",
      "method": "POST",
      "path": "/courses/{course_id}/lessons/{lesson_id}/video-watched",
      "summary": "Mark Course Lesson Video Watched",
      "destructive": false
    },
    "delete_my_course_progress": {
      "op": "courses/delete-my-course-progress",
      "method": "DELETE",
      "path": "/courses/{course_id}/progress",
      "summary": "Delete My Course Progress",
      "destructive": true
    },
    "get_course_by_slug": {
      "op": "courses/get-course-by-slug",
      "method": "GET",
      "path": "/courses/{course_slug}/by-slug",
      "summary": "Get Course By Slug",
      "destructive": false
    },
    "get_course_lesson_by_slug": {
      "op": "courses/get-course-lesson-by-slug",
      "method": "GET",
      "path": "/courses/{course_slug}/lessons/{lesson_slug}/by-slug",
      "summary": "Get Course Lesson By Slug",
      "destructive": false
    }
  },
  "community_profiles": {
    "list_invitations": {
      "op": "profile/list-invitations",
      "method": "GET",
      "path": "/invitations",
      "summary": "List Invitations",
      "destructive": false
    },
    "create_invitation": {
      "op": "profile/create-invitation",
      "method": "POST",
      "path": "/invitations",
      "summary": "Create Invitation",
      "destructive": false
    },
    "create_invitation_link": {
      "op": "profile/create-invitation-link",
      "method": "POST",
      "path": "/invitations/link",
      "summary": "Create Invitation Link",
      "destructive": false
    },
    "delete_invitation": {
      "op": "profile/delete-invitation",
      "method": "DELETE",
      "path": "/invitations/{invitation_id}",
      "summary": "Delete Invitation",
      "destructive": true
    },
    "resend_invitation": {
      "op": "profile/resend-invitation",
      "method": "POST",
      "path": "/invitations/{invitation_id}/resend",
      "summary": "Resend Invitation",
      "destructive": false
    },
    "get_leaderboard": {
      "op": "profile/get-leaderboard",
      "method": "GET",
      "path": "/leaderboard",
      "summary": "Get Leaderboard",
      "destructive": false
    },
    "list_members": {
      "op": "profile/list-members",
      "method": "GET",
      "path": "/members",
      "summary": "List Members",
      "destructive": false
    },
    "patch_member": {
      "op": "profile/patch-member",
      "method": "PATCH",
      "path": "/members/{user_id}",
      "summary": "Patch Member",
      "destructive": false
    },
    "list_notifications": {
      "op": "profile/list-notifications",
      "method": "GET",
      "path": "/notifications",
      "summary": "List Notifications",
      "destructive": false
    },
    "mark_all_notifications_read": {
      "op": "profile/mark-all-notifications-read",
      "method": "POST",
      "path": "/notifications/mark-all-read",
      "summary": "Mark All Notifications Read",
      "destructive": false
    },
    "mark_notification_read_by_feed": {
      "op": "profile/mark-notification-read-by-feed",
      "method": "POST",
      "path": "/notifications/mark-read/{feed_id}/by-feed-id",
      "summary": "Mark Notification Read By Feed",
      "destructive": false
    },
    "mark_notification_read": {
      "op": "profile/mark-notification-read",
      "method": "POST",
      "path": "/notifications/mark-read/{notification_id}",
      "summary": "Mark Notification Read",
      "destructive": false
    },
    "get_unread_notification_count": {
      "op": "profile/get-unread-notification-count",
      "method": "GET",
      "path": "/notifications/unread",
      "summary": "Get Unread Notification Count",
      "destructive": false
    },
    "toggle_profile_follow": {
      "op": "profile/toggle-profile-follow",
      "method": "POST",
      "path": "/profile/{userId}/toggle-follow",
      "summary": "Toggle Profile Follow",
      "destructive": false
    },
    "get_profile": {
      "op": "profile/get-profile",
      "method": "GET",
      "path": "/profile/{username}",
      "summary": "Get Profile",
      "destructive": false
    },
    "save_profile": {
      "op": "profile/save-profile",
      "method": "POST",
      "path": "/profile/{username}",
      "summary": "Save Profile",
      "destructive": false
    },
    "update_profile": {
      "op": "profile/update-profile",
      "method": "PUT",
      "path": "/profile/{username}",
      "summary": "Update Profile",
      "destructive": false
    },
    "block_profile": {
      "op": "profile/block-profile",
      "method": "POST",
      "path": "/profile/{username}/block",
      "summary": "Block Profile",
      "destructive": false
    },
    "list_profile_blocked_users": {
      "op": "profile/list-profile-blocked-users",
      "method": "GET",
      "path": "/profile/{username}/blocked-users",
      "summary": "List Profile Blocked Users",
      "destructive": false
    },
    "change_profile_password": {
      "op": "profile/change-profile-password",
      "method": "POST",
      "path": "/profile/{username}/change-password",
      "summary": "Change Profile Password",
      "destructive": false
    },
    "list_profile_comments": {
      "op": "profile/list-profile-comments",
      "method": "GET",
      "path": "/profile/{username}/comments",
      "summary": "List Profile Comments",
      "destructive": false
    },
    "list_profile_courses": {
      "op": "profile/list-profile-courses",
      "method": "GET",
      "path": "/profile/{username}/courses",
      "summary": "List Profile Courses",
      "destructive": false
    },
    "follow_profile": {
      "op": "profile/follow-profile",
      "method": "POST",
      "path": "/profile/{username}/follow",
      "summary": "Follow Profile",
      "destructive": false
    },
    "list_profile_followers": {
      "op": "profile/list-profile-followers",
      "method": "GET",
      "path": "/profile/{username}/followers",
      "summary": "List Profile Followers",
      "destructive": false
    },
    "list_profile_followings": {
      "op": "profile/list-profile-followings",
      "method": "GET",
      "path": "/profile/{username}/followings",
      "summary": "List Profile Followings",
      "destructive": false
    },
    "list_profile_memberships": {
      "op": "profile/list-profile-memberships",
      "method": "GET",
      "path": "/profile/{username}/memberships",
      "summary": "List Profile Memberships",
      "destructive": false
    },
    "save_profile_notification": {
      "op": "profile/save-profile-notification",
      "method": "POST",
      "path": "/profile/{username}/notification",
      "summary": "Save Profile Notification",
      "destructive": false
    },
    "get_profile_notification_preferences": {
      "op": "profile/get-profile-notification-preferences",
      "method": "GET",
      "path": "/profile/{username}/notification-preferences",
      "summary": "Get Profile Notification Preferences",
      "destructive": false
    },
    "save_profile_notification_preferences": {
      "op": "profile/save-profile-notification-preferences",
      "method": "POST",
      "path": "/profile/{username}/notification-preferences",
      "summary": "Save Profile Notification Preferences",
      "destructive": false
    },
    "reconfirm_profile_email": {
      "op": "profile/reconfirm-profile-email",
      "method": "POST",
      "path": "/profile/{username}/reconfirm-email",
      "summary": "Reconfirm Profile Email",
      "destructive": false
    },
    "list_profile_spaces": {
      "op": "profile/list-profile-spaces",
      "method": "GET",
      "path": "/profile/{username}/spaces",
      "summary": "List Profile Spaces",
      "destructive": false
    },
    "unblock_profile": {
      "op": "profile/unblock-profile",
      "method": "POST",
      "path": "/profile/{username}/unblock",
      "summary": "Unblock Profile",
      "destructive": false
    },
    "unfollow_profile": {
      "op": "profile/unfollow-profile",
      "method": "POST",
      "path": "/profile/{username}/unfollow",
      "summary": "Unfollow Profile",
      "destructive": false
    }
  },
  "community_analytics": {
    "get_analytics_member_activity": {
      "op": "analytics/get-analytics-member-activity",
      "method": "GET",
      "path": "/analytics/members/activity",
      "summary": "Get Analytics Member Activity",
      "destructive": false
    },
    "list_top_commenters": {
      "op": "analytics/list-top-commenters",
      "method": "GET",
      "path": "/analytics/members/top-commenters",
      "summary": "List Top Commenters",
      "destructive": false
    },
    "list_top_members": {
      "op": "analytics/list-top-members",
      "method": "GET",
      "path": "/analytics/members/top-members",
      "summary": "List Top Members",
      "destructive": false
    },
    "list_top_post_starters": {
      "op": "analytics/list-top-post-starters",
      "method": "GET",
      "path": "/analytics/members/top-post-starters",
      "summary": "List Top Post Starters",
      "destructive": false
    },
    "get_analytics_member_widget": {
      "op": "analytics/get-analytics-member-widget",
      "method": "GET",
      "path": "/analytics/members/widget",
      "summary": "Get Analytics Member Widget",
      "destructive": false
    },
    "get_analytics_overview_activity": {
      "op": "analytics/get-analytics-overview-activity",
      "method": "GET",
      "path": "/analytics/overview/activity",
      "summary": "Get Analytics Overview Activity",
      "destructive": false
    },
    "get_analytics_overview_popular_day_time": {
      "op": "analytics/get-analytics-overview-popular-day-time",
      "method": "GET",
      "path": "/analytics/overview/popular-day-time",
      "summary": "Get Analytics Overview Popular Day Time",
      "destructive": false
    },
    "get_analytics_overview_widget": {
      "op": "analytics/get-analytics-overview-widget",
      "method": "GET",
      "path": "/analytics/overview/widget",
      "summary": "Get Analytics Overview Widget",
      "destructive": false
    },
    "get_analytics_space_activity": {
      "op": "analytics/get-analytics-space-activity",
      "method": "GET",
      "path": "/analytics/spaces/activity",
      "summary": "Get Analytics Space Activity",
      "destructive": false
    },
    "get_analytics_space_popular": {
      "op": "analytics/get-analytics-space-popular",
      "method": "GET",
      "path": "/analytics/spaces/popular",
      "summary": "Get Analytics Space Popular",
      "destructive": false
    },
    "search_spaces_analytics": {
      "op": "analytics/search-spaces-analytics",
      "method": "GET",
      "path": "/analytics/spaces/search",
      "summary": "Search Spaces Analytics",
      "destructive": false
    },
    "get_analytics_space_widget": {
      "op": "analytics/get-analytics-space-widget",
      "method": "GET",
      "path": "/analytics/spaces/widget",
      "summary": "Get Analytics Space Widget",
      "destructive": false
    }
  },
  "community_settings": {
    "get_app_vars": {
      "op": "settings/get-app-vars",
      "method": "GET",
      "path": "/options/app-vars",
      "summary": "Get App Vars",
      "destructive": false
    },
    "list_menu_items": {
      "op": "settings/list-menu-items",
      "method": "GET",
      "path": "/options/menu-items",
      "summary": "List Menu Items",
      "destructive": false
    },
    "get_sidebar_menu_html": {
      "op": "settings/get-sidebar-menu-html",
      "method": "GET",
      "path": "/options/sidebar-menu-html",
      "summary": "Get Sidebar Menu HTML",
      "destructive": false
    },
    "get_color_config": {
      "op": "settings/get-color-config",
      "method": "GET",
      "path": "/settings/color-config",
      "summary": "Get Color Config",
      "destructive": false
    },
    "save_color_config": {
      "op": "settings/save-color-config",
      "method": "POST",
      "path": "/settings/color-config",
      "summary": "Save Color Config",
      "destructive": false
    },
    "get_crm_tagging_config": {
      "op": "settings/get-crm-tagging-config",
      "method": "GET",
      "path": "/settings/crm-tagging-config",
      "summary": "Get CRM Tagging Config",
      "destructive": false
    },
    "save_crm_tagging_config": {
      "op": "settings/save-crm-tagging-config",
      "method": "POST",
      "path": "/settings/crm-tagging-config",
      "summary": "Save CRM Tagging Config",
      "destructive": false
    },
    "get_customization_settings": {
      "op": "settings/get-customization-settings",
      "method": "GET",
      "path": "/settings/customization-settings",
      "summary": "Get Customization Settings",
      "destructive": false
    },
    "save_customization_settings": {
      "op": "settings/save-customization-settings",
      "method": "POST",
      "path": "/settings/customization-settings",
      "summary": "Save Customization Settings",
      "destructive": false
    },
    "get_features": {
      "op": "settings/get-features",
      "method": "GET",
      "path": "/settings/features",
      "summary": "Get Features",
      "destructive": false
    },
    "save_features": {
      "op": "settings/save-features",
      "method": "POST",
      "path": "/settings/features",
      "summary": "Save Features",
      "destructive": false
    },
    "get_fluent_player_settings": {
      "op": "settings/get-fluent-player-settings",
      "method": "GET",
      "path": "/settings/fluent-player-settings",
      "summary": "Get Fluent Player Settings",
      "destructive": false
    },
    "save_fluent_player_settings": {
      "op": "settings/save-fluent-player-settings",
      "method": "POST",
      "path": "/settings/fluent-player-settings",
      "summary": "Save Fluent Player Settings",
      "destructive": false
    },
    "get_followers_config": {
      "op": "settings/get-followers-config",
      "method": "GET",
      "path": "/settings/followers/config",
      "summary": "Get Followers Config",
      "destructive": false
    },
    "save_followers_config": {
      "op": "settings/save-followers-config",
      "method": "POST",
      "path": "/settings/followers/config",
      "summary": "Save Followers Config",
      "destructive": false
    },
    "install_plugin": {
      "op": "settings/install-plugin",
      "method": "POST",
      "path": "/settings/install_plugin",
      "summary": "Install a FluentCommunity Addon Plugin",
      "destructive": true,
      "bodyNote": "Body: {\"plugin\": \"<addon slug>\"}. Unlike Fluent Forms' installer this one is allowlisted — the slug must be one of FluentCommunity's own addons, so it cannot install arbitrary plugins."
    },
    "get_menu_settings": {
      "op": "settings/get-menu-settings",
      "method": "GET",
      "path": "/settings/menu-settings",
      "summary": "Get Menu Settings",
      "destructive": false
    },
    "save_menu_settings": {
      "op": "settings/save-menu-settings",
      "method": "POST",
      "path": "/settings/menu-settings",
      "summary": "Save Menu Settings",
      "destructive": false
    },
    "get_privacy_settings": {
      "op": "settings/get-privacy-settings",
      "method": "GET",
      "path": "/settings/privacy-settings",
      "summary": "Get Privacy Settings",
      "destructive": false
    },
    "save_privacy_settings": {
      "op": "settings/save-privacy-settings",
      "method": "POST",
      "path": "/settings/privacy-settings",
      "summary": "Save Privacy Settings",
      "destructive": false
    },
    "get_snippets_settings": {
      "op": "settings/get-snippets-settings",
      "method": "GET",
      "path": "/settings/snippets-settings",
      "summary": "Get Snippets Settings",
      "destructive": false
    },
    "save_snippets_settings": {
      "op": "settings/save-snippets-settings",
      "method": "POST",
      "path": "/settings/snippets-settings",
      "summary": "Save Snippets Settings",
      "destructive": false
    }
  },
  "community_admin": {
    "get_auth_settings": {
      "op": "admin/get-auth-settings",
      "method": "GET",
      "path": "/admin/auth-settings",
      "summary": "Get Auth Settings",
      "destructive": false
    },
    "save_auth_settings": {
      "op": "admin/save-auth-settings",
      "method": "POST",
      "path": "/admin/auth-settings",
      "summary": "Save Auth Settings",
      "destructive": false
    },
    "list_custom_profile_fields": {
      "op": "admin/list-custom-profile-fields",
      "method": "GET",
      "path": "/admin/custom-profile-fields",
      "summary": "List Custom Profile Fields",
      "destructive": false
    },
    "save_custom_profile_fields": {
      "op": "admin/save-custom-profile-fields",
      "method": "POST",
      "path": "/admin/custom-profile-fields",
      "summary": "Save Custom Profile Fields",
      "destructive": false
    },
    "get_email_settings": {
      "op": "admin/get-email-settings",
      "method": "GET",
      "path": "/admin/email-settings",
      "summary": "Get Email Settings",
      "destructive": false
    },
    "save_email_settings": {
      "op": "admin/save-email-settings",
      "method": "POST",
      "path": "/admin/email-settings",
      "summary": "Save Email Settings",
      "destructive": false
    },
    "get_general_settings": {
      "op": "admin/get-general-settings",
      "method": "GET",
      "path": "/admin/general",
      "summary": "Get General Settings",
      "destructive": false
    },
    "save_general_settings": {
      "op": "admin/save-general-settings",
      "method": "POST",
      "path": "/admin/general",
      "summary": "Save General Settings",
      "destructive": false
    },
    "list_leaderboard_levels": {
      "op": "admin/list-leaderboard-levels",
      "method": "GET",
      "path": "/admin/leaderboards/levels",
      "summary": "List Leaderboard Levels",
      "destructive": false
    },
    "save_leaderboard_levels": {
      "op": "admin/save-leaderboard-levels",
      "method": "POST",
      "path": "/admin/leaderboards/levels",
      "summary": "Save Leaderboard Levels",
      "destructive": false
    },
    "deactivate_license": {
      "op": "admin/deactivate-license",
      "method": "DELETE",
      "path": "/admin/license",
      "summary": "Deactivate License",
      "destructive": true
    },
    "get_license": {
      "op": "admin/get-license",
      "method": "GET",
      "path": "/admin/license",
      "summary": "Get License",
      "destructive": false
    },
    "activate_license": {
      "op": "admin/activate-license",
      "method": "POST",
      "path": "/admin/license",
      "summary": "Activate License",
      "destructive": false
    },
    "create_link": {
      "op": "admin/create-link",
      "method": "POST",
      "path": "/admin/links",
      "summary": "Create Link",
      "destructive": false
    },
    "delete_link": {
      "op": "admin/delete-link",
      "method": "DELETE",
      "path": "/admin/links/{id}",
      "summary": "Delete Link",
      "destructive": true
    },
    "list_managers": {
      "op": "admin/list-managers",
      "method": "GET",
      "path": "/admin/managers",
      "summary": "List Managers",
      "destructive": false
    },
    "add_manager": {
      "op": "admin/add-manager",
      "method": "POST",
      "path": "/admin/managers",
      "summary": "Add Manager",
      "destructive": false
    },
    "delete_manager": {
      "op": "admin/delete-manager",
      "method": "DELETE",
      "path": "/admin/managers/{user_id}",
      "summary": "Delete Manager",
      "destructive": true
    },
    "get_messaging_settings": {
      "op": "admin/get-messaging-settings",
      "method": "GET",
      "path": "/admin/messaging-setting",
      "summary": "Get Messaging Settings",
      "destructive": false
    },
    "save_messaging_settings": {
      "op": "admin/save-messaging-settings",
      "method": "POST",
      "path": "/admin/messaging-setting",
      "summary": "Save Messaging Settings",
      "destructive": false
    },
    "list_onboardings": {
      "op": "admin/list-onboardings",
      "method": "GET",
      "path": "/admin/on-boardings",
      "summary": "List Onboardings",
      "destructive": false
    },
    "save_onboarding": {
      "op": "admin/save-onboarding",
      "method": "POST",
      "path": "/admin/on-boardings",
      "summary": "Save Onboarding",
      "destructive": false
    },
    "change_onboarding_slug": {
      "op": "admin/change-onboarding-slug",
      "method": "POST",
      "path": "/admin/on-boardings/change-slug",
      "summary": "Change Onboarding Slug",
      "destructive": false
    },
    "list_profile_link_providers": {
      "op": "admin/list-profile-link-providers",
      "method": "GET",
      "path": "/admin/profile-link-providers",
      "summary": "List Profile Link Providers",
      "destructive": false
    },
    "save_profile_link_providers": {
      "op": "admin/save-profile-link-providers",
      "method": "POST",
      "path": "/admin/profile-link-providers",
      "summary": "Save Profile Link Providers",
      "destructive": false
    },
    "get_push_settings": {
      "op": "admin/get-push-settings",
      "method": "GET",
      "path": "/admin/push-settings",
      "summary": "Get Push Settings",
      "destructive": false
    },
    "save_push_settings": {
      "op": "admin/save-push-settings",
      "method": "POST",
      "path": "/admin/push-settings",
      "summary": "Save Push Settings",
      "destructive": false
    },
    "get_pwa_settings": {
      "op": "admin/get-pwa-settings",
      "method": "GET",
      "path": "/admin/pwa-settings",
      "summary": "Get PWA Settings",
      "destructive": false
    },
    "save_pwa_settings": {
      "op": "admin/save-pwa-settings",
      "method": "POST",
      "path": "/admin/pwa-settings",
      "summary": "Save PWA Settings",
      "destructive": false
    },
    "get_storage_settings": {
      "op": "admin/get-storage-settings",
      "method": "GET",
      "path": "/admin/storage-settings",
      "summary": "Get Storage Settings",
      "destructive": false
    },
    "save_storage_settings": {
      "op": "admin/save-storage-settings",
      "method": "POST",
      "path": "/admin/storage-settings",
      "summary": "Save Storage Settings",
      "destructive": false
    },
    "list_topics": {
      "op": "admin/list-topics",
      "method": "GET",
      "path": "/admin/topics",
      "summary": "List Topics",
      "destructive": false
    },
    "create_topic": {
      "op": "admin/create-topic",
      "method": "POST",
      "path": "/admin/topics",
      "summary": "Create Topic",
      "destructive": false
    },
    "save_topics_config": {
      "op": "admin/save-topics-config",
      "method": "POST",
      "path": "/admin/topics/config",
      "summary": "Save Topics Config",
      "destructive": false
    },
    "reorder_topics": {
      "op": "admin/reorder-topics",
      "method": "POST",
      "path": "/admin/topics/reorder",
      "summary": "Reorder Topics",
      "destructive": false
    },
    "delete_topic": {
      "op": "admin/delete-topic",
      "method": "DELETE",
      "path": "/admin/topics/{topic_id}",
      "summary": "Delete Topic",
      "destructive": true
    },
    "list_user_badges": {
      "op": "admin/list-user-badges",
      "method": "GET",
      "path": "/admin/user-badges",
      "summary": "List User Badges",
      "destructive": false
    },
    "save_user_badges": {
      "op": "admin/save-user-badges",
      "method": "POST",
      "path": "/admin/user-badges",
      "summary": "Save User Badges",
      "destructive": false
    },
    "list_community_users": {
      "op": "admin/list-community-users",
      "method": "GET",
      "path": "/admin/users",
      "summary": "List Community Users",
      "destructive": false
    },
    "list_webhooks": {
      "op": "admin/list-webhooks",
      "method": "GET",
      "path": "/admin/webhooks",
      "summary": "List Webhooks",
      "destructive": false
    },
    "create_webhook": {
      "op": "admin/create-webhook",
      "method": "POST",
      "path": "/admin/webhooks",
      "summary": "Create Webhook",
      "destructive": false
    },
    "delete_webhook": {
      "op": "admin/delete-webhook",
      "method": "DELETE",
      "path": "/admin/webhooks/{id}",
      "summary": "Delete Webhook",
      "destructive": true
    },
    "get_welcome_banner": {
      "op": "admin/get-welcome-banner",
      "method": "GET",
      "path": "/admin/welcome-banner",
      "summary": "Get Welcome Banner",
      "destructive": false
    },
    "save_welcome_banner": {
      "op": "admin/save-welcome-banner",
      "method": "POST",
      "path": "/admin/welcome-banner",
      "summary": "Save Welcome Banner",
      "destructive": false
    }
  }
};

export const TOOL_META: Record<string, { description: string; note?: string; idempotent?: boolean }> = {
  "community_spaces": {
    "description": "Manage community spaces and space groups: membership, lock screens, links, paywalls, and each space's media gallery."
  },
  "community_feeds": {
    "description": "Posts and the activity feed: create and edit posts, comments, reactions, bookmarks, surveys, uploaded documents and media, scheduled posts, and moderation reports."
  },
  "community_chat": {
    "description": "Direct and group chat: threads, group membership, messages, reactions, and blocking."
  },
  "community_courses": {
    "description": "Courses end to end: course CRUD, sections, lessons, students and enrolment, quizzes, progress, and the member-facing course views."
  },
  "community_profiles": {
    "description": "Member profiles and directory: profile fields, follows and blocks, notification preferences, memberships, invitations, notifications, and the leaderboard."
  },
  "community_analytics": {
    "description": "Read-only community analytics: activity over time, popular spaces, and top members."
  },
  "community_settings": {
    "description": "Portal settings and runtime options: colours, features, menus, privacy, snippets, follower and player settings, and CRM tagging."
  },
  "community_admin": {
    "description": "Site administration: licensing, managers, webhooks, topics, badges, onboarding, and the auth, email, push, PWA, storage and messaging settings."
  }
};
