/* AUTO-GENERATED by scripts/gen-endpoint-maps.mjs from docs/api-reference/fluentcart/endpoints.json — do not edit by hand. */
import type { EndpointDef } from '../../core/types.js';

export const TOOL_ENDPOINTS: Record<string, Record<string, EndpointDef>> = {
  "cart_orders": {
    "accept_dispute": {
      "op": "orders/accept-dispute",
      "method": "POST",
      "path": "/orders/{order}/transactions/{transaction_id}/accept-dispute/",
      "summary": "Accept Dispute",
      "destructive": true
    },
    "bulk_actions": {
      "op": "orders/bulk-actions",
      "method": "POST",
      "path": "/orders/do-bulk-action",
      "summary": "Bulk Actions",
      "destructive": true
    },
    "calculate_shipping": {
      "op": "orders/calculate-shipping",
      "method": "POST",
      "path": "/orders/calculate-shipping",
      "summary": "Calculate Shipping",
      "destructive": false
    },
    "change_customer": {
      "op": "orders/change-customer",
      "method": "POST",
      "path": "/orders/{order_id}/change-customer",
      "summary": "Change Customer",
      "destructive": false
    },
    "create_and_change_customer": {
      "op": "orders/create-and-change-customer",
      "method": "POST",
      "path": "/orders/{order_id}/create-and-change-customer",
      "summary": "Create and Change Customer",
      "destructive": false
    },
    "create_custom_order_item": {
      "op": "orders/create-custom-order-item",
      "method": "POST",
      "path": "/orders/{order}/create-custom",
      "summary": "Create Custom Order Item",
      "destructive": false
    },
    "create_order": {
      "op": "orders/create-order",
      "method": "POST",
      "path": "/orders",
      "summary": "Create Order",
      "destructive": false
    },
    "delete_order": {
      "op": "orders/delete-order",
      "method": "DELETE",
      "path": "/orders/{order_id}",
      "summary": "Delete Order",
      "destructive": true
    },
    "generate_missing_licenses": {
      "op": "orders/generate-missing-licenses",
      "method": "POST",
      "path": "/orders/{order}/generate-missing-licenses",
      "summary": "Generate Missing Licenses",
      "destructive": false
    },
    "get_order": {
      "op": "orders/get-order",
      "method": "GET",
      "path": "/orders/{order_id}",
      "summary": "Get Order Details",
      "destructive": false
    },
    "get_order_transactions": {
      "op": "orders/get-order-transactions",
      "method": "GET",
      "path": "/orders/{order}/transactions",
      "summary": "Get Order Transactions",
      "destructive": false
    },
    "get_shipping_methods": {
      "op": "orders/get-shipping-methods",
      "method": "GET",
      "path": "/orders/shipping_methods",
      "summary": "Get Shipping Methods",
      "destructive": false
    },
    "get_single_transaction": {
      "op": "orders/get-single-transaction",
      "method": "GET",
      "path": "/orders/{id}/transactions/{transaction_id}",
      "summary": "Get Single Transaction",
      "destructive": false
    },
    "list_orders": {
      "op": "orders/list-orders",
      "method": "GET",
      "path": "/orders",
      "summary": "List Orders",
      "destructive": false
    },
    "mark_as_paid": {
      "op": "orders/mark-as-paid",
      "method": "POST",
      "path": "/orders/{order}/mark-as-paid",
      "summary": "Mark Order as Paid",
      "destructive": false
    },
    "refund_order": {
      "op": "orders/refund-order",
      "method": "POST",
      "path": "/orders/{order_id}/refund",
      "summary": "Refund Order",
      "destructive": true
    },
    "sync_order_statuses": {
      "op": "orders/sync-order-statuses",
      "method": "PUT",
      "path": "/orders/{order}/sync-statuses",
      "summary": "Sync Order Statuses",
      "destructive": false
    },
    "update_order": {
      "op": "orders/update-order",
      "method": "POST",
      "path": "/orders/{order_id}",
      "summary": "Update Order",
      "destructive": false
    },
    "update_order_address": {
      "op": "orders/update-order-address",
      "method": "PUT",
      "path": "/orders/{order}/address/{id}",
      "summary": "Update Order Address",
      "destructive": false
    },
    "update_order_address_id": {
      "op": "orders/update-order-address-id",
      "method": "POST",
      "path": "/orders/{order_id}/update-address-id",
      "summary": "Update Order Address ID",
      "destructive": false
    },
    "update_statuses": {
      "op": "orders/update-statuses",
      "method": "PUT",
      "path": "/orders/{order}/statuses",
      "summary": "Update Statuses",
      "destructive": false
    },
    "update_transaction_status": {
      "op": "orders/update-transaction-status",
      "method": "PUT",
      "path": "/orders/{order}/transactions/{transaction}/status",
      "summary": "Update Transaction Status",
      "destructive": false
    }
  },
  "cart_products": {
    "add_product_terms": {
      "op": "products/add-product-terms",
      "method": "POST",
      "path": "/products/add-product-terms",
      "summary": "Add Product Terms",
      "destructive": false
    },
    "bulk_edit_fetch": {
      "op": "products/bulk-edit-fetch",
      "method": "GET",
      "path": "/products/bulk-edit-data",
      "summary": "Bulk Edit Fetch",
      "destructive": false
    },
    "bulk_insert_products": {
      "op": "products/bulk-insert-products",
      "method": "POST",
      "path": "/products/bulk-insert",
      "summary": "Bulk Insert Products",
      "destructive": false
    },
    "bulk_update_products": {
      "op": "products/bulk-update-products",
      "method": "POST",
      "path": "/products/bulk-update",
      "summary": "Bulk Update Products",
      "destructive": false
    },
    "create_dummy_products": {
      "op": "products/create-dummy-products",
      "method": "POST",
      "path": "/products/create-dummy",
      "summary": "Create Dummy Products",
      "destructive": false
    },
    "create_product": {
      "op": "products/create-product",
      "method": "POST",
      "path": "/products",
      "summary": "Create Product",
      "destructive": false
    },
    "delete_product": {
      "op": "products/delete-product",
      "method": "DELETE",
      "path": "/products/{product}",
      "summary": "Delete Product",
      "destructive": true
    },
    "delete_taxonomy_term": {
      "op": "products/delete-taxonomy-term",
      "method": "POST",
      "path": "/products/delete-taxonomy-term/{postId}",
      "summary": "Delete Taxonomy Term",
      "destructive": true
    },
    "do_bulk_action": {
      "op": "products/do-bulk-action",
      "method": "POST",
      "path": "/products/do-bulk-action",
      "summary": "Do Bulk Action",
      "destructive": true
    },
    "duplicate_product": {
      "op": "products/duplicate-product",
      "method": "POST",
      "path": "/products/{productId}/duplicate",
      "summary": "Duplicate Product",
      "destructive": false
    },
    "fetch_products_by_ids": {
      "op": "products/fetch-products-by-ids",
      "method": "GET",
      "path": "/products/fetchProductsByIds",
      "summary": "Fetch Products by IDs",
      "destructive": false
    },
    "fetch_taxonomy_terms": {
      "op": "products/fetch-taxonomy-terms",
      "method": "GET",
      "path": "/products/fetch-term",
      "summary": "Fetch Taxonomy Terms",
      "destructive": false
    },
    "fetch_terms_by_parent": {
      "op": "products/fetch-terms-by-parent",
      "method": "POST",
      "path": "/products/fetch-term-by-parent",
      "summary": "Fetch Terms by Parent",
      "destructive": false
    },
    "get_max_excerpt_word_count": {
      "op": "products/get-max-excerpt-word-count",
      "method": "GET",
      "path": "/products/get-max-excerpt-word-count",
      "summary": "Get Max Excerpt Word Count",
      "destructive": false
    },
    "get_pricing_widgets": {
      "op": "products/get-pricing-widgets",
      "method": "GET",
      "path": "/products/{productId}/pricing-widgets",
      "summary": "Get Pricing Widgets",
      "destructive": false
    },
    "get_product": {
      "op": "products/get-product",
      "method": "GET",
      "path": "/products/{product}",
      "summary": "Get Product",
      "destructive": false
    },
    "get_related_products": {
      "op": "products/get-related-products",
      "method": "GET",
      "path": "/products/{productId}/related-products",
      "summary": "Get Related Products",
      "destructive": false
    },
    "list_products": {
      "op": "products/list-products",
      "method": "GET",
      "path": "/products",
      "summary": "List Products",
      "destructive": false
    },
    "remove_shipping_class": {
      "op": "products/remove-shipping-class",
      "method": "POST",
      "path": "/products/{postId}/shipping-class/remove",
      "summary": "Remove Shipping Class",
      "destructive": true
    },
    "remove_tax_class": {
      "op": "products/remove-tax-class",
      "method": "POST",
      "path": "/products/{postId}/tax-class/remove",
      "summary": "Remove Tax Class",
      "destructive": true
    },
    "search_products_by_name": {
      "op": "products/search-products-by-name",
      "method": "GET",
      "path": "/products/searchProductByName",
      "summary": "Search Products by Name",
      "destructive": false
    },
    "suggest_sku": {
      "op": "products/suggest-sku",
      "method": "GET",
      "path": "/products/suggest-sku",
      "summary": "Suggest SKU",
      "destructive": false
    },
    "sync_taxonomy_terms": {
      "op": "products/sync-taxonomy-terms",
      "method": "POST",
      "path": "/products/sync-taxonomy-term/{postId}",
      "summary": "Sync Taxonomy Terms",
      "destructive": false
    },
    "update_long_desc_editor_mode": {
      "op": "products/update-long-desc-editor-mode",
      "method": "POST",
      "path": "/products/{postId}/update-long-desc-editor-mode",
      "summary": "Update Long Description Editor Mode",
      "destructive": false
    },
    "update_product_detail": {
      "op": "products/update-product-detail",
      "method": "POST",
      "path": "/products/detail/{detailId}",
      "summary": "Update Product Detail",
      "destructive": false
    },
    "update_shipping_class": {
      "op": "products/update-shipping-class",
      "method": "POST",
      "path": "/products/{postId}/shipping-class",
      "summary": "Update Shipping Class",
      "destructive": false
    },
    "update_tax_class": {
      "op": "products/update-tax-class",
      "method": "POST",
      "path": "/products/{postId}/tax-class",
      "summary": "Update Tax Class",
      "destructive": false
    }
  },
  "cart_product_variants": {
    "create_variation": {
      "op": "products/create-variation",
      "method": "POST",
      "path": "/products/variants",
      "summary": "Create Variation",
      "destructive": false
    },
    "delete_upgrade_path": {
      "op": "products/delete-upgrade-path",
      "method": "DELETE",
      "path": "/products/upgrade-path/{id}/delete",
      "summary": "Delete Upgrade Path",
      "destructive": true
    },
    "delete_variation": {
      "op": "products/delete-variation",
      "method": "DELETE",
      "path": "/products/variants/{variantId}",
      "summary": "Delete Variation",
      "destructive": true
    },
    "fetch_variations_by_ids": {
      "op": "products/fetch-variations-by-ids",
      "method": "GET",
      "path": "/products/fetchVariationsByIds",
      "summary": "Fetch Variations by IDs",
      "destructive": false
    },
    "find_subscription_variants": {
      "op": "products/find-subscription-variants",
      "method": "GET",
      "path": "/products/findSubscriptionVariants",
      "summary": "Find Subscription Variants",
      "destructive": false
    },
    "get_bundle_info": {
      "op": "products/get-bundle-info",
      "method": "GET",
      "path": "/products/get-bundle-info/{productId}",
      "summary": "Get Bundle Info",
      "destructive": false
    },
    "get_product_pricing": {
      "op": "products/get-product-pricing",
      "method": "GET",
      "path": "/products/{productId}/pricing",
      "summary": "Get Product Pricing",
      "destructive": false
    },
    "get_upgrade_settings": {
      "op": "products/get-upgrade-settings",
      "method": "GET",
      "path": "/products/{id}/upgrade-paths",
      "summary": "Get Upgrade Settings",
      "destructive": false
    },
    "get_variation_upgrade_paths": {
      "op": "products/get-variation-upgrade-paths",
      "method": "GET",
      "path": "/products/variation/{variantId}/upgrade-paths",
      "summary": "Get Variation Upgrade Paths",
      "destructive": false
    },
    "list_all_variants": {
      "op": "products/list-all-variants",
      "method": "GET",
      "path": "/variants",
      "summary": "List All Variants",
      "destructive": false
    },
    "list_product_variations": {
      "op": "products/list-product-variations",
      "method": "GET",
      "path": "/products/variants",
      "summary": "List Product Variations",
      "destructive": false
    },
    "save_bundle_info": {
      "op": "products/save-bundle-info",
      "method": "POST",
      "path": "/products/save-bundle-info/{variationId}",
      "summary": "Save Bundle Info",
      "destructive": false
    },
    "save_upgrade_path": {
      "op": "products/save-upgrade-path",
      "method": "POST",
      "path": "/products/{id}/upgrade-path",
      "summary": "Save Upgrade Path",
      "destructive": false
    },
    "search_product_variant_options": {
      "op": "products/search-product-variant-options",
      "method": "GET",
      "path": "/products/search-product-variant-options",
      "summary": "Search Product Variant Options",
      "destructive": false
    },
    "search_variants_by_name": {
      "op": "products/search-variants-by-name",
      "method": "GET",
      "path": "/products/searchVariantByName",
      "summary": "Search Variants by Name",
      "destructive": false
    },
    "set_variation_media": {
      "op": "products/set-variation-media",
      "method": "POST",
      "path": "/products/variants/{variantId}/setMedia",
      "summary": "Set Variation Media",
      "destructive": false
    },
    "update_inventory": {
      "op": "products/update-inventory",
      "method": "PUT",
      "path": "/products/{postId}/update-inventory/{variantId}",
      "summary": "Update Inventory",
      "destructive": false
    },
    "update_manage_stock": {
      "op": "products/update-manage-stock",
      "method": "PUT",
      "path": "/products/{postId}/update-manage-stock",
      "summary": "Update Manage Stock Setting",
      "destructive": false
    },
    "update_product_pricing": {
      "op": "products/update-product-pricing",
      "method": "POST",
      "path": "/products/{postId}/pricing",
      "summary": "Update Product Pricing",
      "destructive": false
    },
    "update_upgrade_path": {
      "op": "products/update-upgrade-path",
      "method": "POST",
      "path": "/products/upgrade-path/{id}/update",
      "summary": "Update Upgrade Path",
      "destructive": false
    },
    "update_variant_option": {
      "op": "products/update-variant-option",
      "method": "POST",
      "path": "/products/{postId}/update-variant-option",
      "summary": "Update Variant Option",
      "destructive": false
    },
    "update_variation": {
      "op": "products/update-variation",
      "method": "POST",
      "path": "/products/variants/{variantId}",
      "summary": "Update Variation",
      "destructive": false
    },
    "update_variation_pricing_table": {
      "op": "products/update-variation-pricing-table",
      "method": "PUT",
      "path": "/products/variants/{variantId}/pricing-table",
      "summary": "Update Variation Pricing Table",
      "destructive": false
    }
  },
  "cart_product_assets": {
    "change_integration_status": {
      "op": "products/change-integration-status",
      "method": "POST",
      "path": "/products/{product_id}/integrations/feed/change-status",
      "summary": "Change Integration Status",
      "destructive": false
    },
    "delete_downloadable_file": {
      "op": "products/delete-downloadable-file",
      "method": "DELETE",
      "path": "/products/{downloadableId}/delete",
      "summary": "Delete Downloadable File",
      "destructive": true
    },
    "delete_product_integration": {
      "op": "products/delete-product-integration",
      "method": "DELETE",
      "path": "/products/{product_id}/integrations/{integration_id}",
      "summary": "Delete Product Integration",
      "destructive": true
    },
    "get_downloadable_url": {
      "op": "products/get-downloadable-url",
      "method": "GET",
      "path": "/products/getDownloadableUrl/{downloadableId}",
      "summary": "Get Downloadable URL",
      "destructive": false
    },
    "get_product_integration_feeds": {
      "op": "products/get-product-integration-feeds",
      "method": "GET",
      "path": "/products/{productId}/integrations",
      "summary": "Get Product Integration Feeds",
      "destructive": false
    },
    "get_product_integration_settings": {
      "op": "products/get-product-integration-settings",
      "method": "GET",
      "path": "/products/{product_id}/integrations/{integration_name}/settings",
      "summary": "Get Product Integration Settings",
      "destructive": false
    },
    "save_product_integration": {
      "op": "products/save-product-integration",
      "method": "POST",
      "path": "/products/{product_id}/integrations",
      "summary": "Save Product Integration",
      "destructive": false
    },
    "sync_downloadable_files": {
      "op": "products/sync-downloadable-files",
      "method": "POST",
      "path": "/products/{postId}/sync-downloadable-files",
      "summary": "Sync Downloadable Files",
      "destructive": false
    },
    "update_downloadable_file": {
      "op": "products/update-downloadable-file",
      "method": "PUT",
      "path": "/products/{downloadableId}/update",
      "summary": "Update Downloadable File",
      "destructive": false
    }
  },
  "cart_customers": {
    "attach_user": {
      "op": "customers/attach-user",
      "method": "POST",
      "path": "/customers/{customerId}/attachable-user",
      "summary": "Attach WordPress User",
      "destructive": false
    },
    "bulk_actions": {
      "op": "customers/bulk-actions",
      "method": "POST",
      "path": "/customers/do-bulk-action",
      "summary": "Bulk Actions",
      "destructive": true
    },
    "create_address": {
      "op": "customers/create-address",
      "method": "POST",
      "path": "/customers/{customerId}/address",
      "summary": "Create Address",
      "destructive": false
    },
    "create_customer": {
      "op": "customers/create-customer",
      "method": "POST",
      "path": "/customers",
      "summary": "Create Customer",
      "destructive": false
    },
    "delete_address": {
      "op": "customers/delete-address",
      "method": "DELETE",
      "path": "/customers/{customerId}/address",
      "summary": "Delete Address",
      "destructive": true
    },
    "detach_user": {
      "op": "customers/detach-user",
      "method": "POST",
      "path": "/customers/{customerId}/detach-user",
      "summary": "Detach WordPress User",
      "destructive": true
    },
    "find_customer_order": {
      "op": "customers/find-customer-order",
      "method": "GET",
      "path": "/customers/{customerId}/order",
      "summary": "Find Customer Order",
      "destructive": false
    },
    "get_attachable_users": {
      "op": "customers/get-attachable-users",
      "method": "GET",
      "path": "/customers/attachable-user",
      "summary": "Get Attachable Users",
      "destructive": false
    },
    "get_customer": {
      "op": "customers/get-customer",
      "method": "GET",
      "path": "/customers/{customerId}",
      "summary": "Get Customer",
      "destructive": false
    },
    "get_customer_addresses": {
      "op": "customers/get-customer-addresses",
      "method": "GET",
      "path": "/customers/{customerId}/address",
      "summary": "Get Customer Addresses",
      "destructive": false
    },
    "get_customer_orders": {
      "op": "customers/get-customer-orders",
      "method": "GET",
      "path": "/customers/{customerId}/orders",
      "summary": "Get Customer Orders",
      "destructive": false
    },
    "get_customer_stats": {
      "op": "customers/get-customer-stats",
      "method": "GET",
      "path": "/customers/get-stats/{customer}",
      "summary": "Get Customer Stats",
      "destructive": false
    },
    "list_customers": {
      "op": "customers/list-customers",
      "method": "GET",
      "path": "/customers",
      "summary": "List Customers",
      "destructive": false
    },
    "recalculate_ltv": {
      "op": "customers/recalculate-ltv",
      "method": "POST",
      "path": "/customers/{customerId}/recalculate-ltv",
      "summary": "Recalculate Lifetime Value",
      "destructive": false
    },
    "set_primary_address": {
      "op": "customers/set-primary-address",
      "method": "POST",
      "path": "/customers/{customerId}/address/make-primary",
      "summary": "Set Primary Address",
      "destructive": false
    },
    "update_additional_info": {
      "op": "customers/update-additional-info",
      "method": "PUT",
      "path": "/customers/{customerId}/additional-info",
      "summary": "Update Additional Info (Labels)",
      "destructive": false
    },
    "update_address": {
      "op": "customers/update-address",
      "method": "PUT",
      "path": "/customers/{customerId}/address",
      "summary": "Update Address",
      "destructive": false
    },
    "update_customer": {
      "op": "customers/update-customer",
      "method": "PUT",
      "path": "/customers/{customerId}",
      "summary": "Update Customer",
      "destructive": false
    }
  },
  "cart_coupons": {
    "apply_coupon": {
      "op": "coupons/apply-coupon",
      "method": "POST",
      "path": "/coupons/apply",
      "summary": "Apply Coupon",
      "destructive": false
    },
    "cancel_coupon": {
      "op": "coupons/cancel-coupon",
      "method": "POST",
      "path": "/coupons/cancel",
      "summary": "Cancel Coupon",
      "destructive": true
    },
    "check_product_eligibility": {
      "op": "coupons/check-product-eligibility",
      "method": "POST",
      "path": "/coupons/checkProductEligibility",
      "summary": "Check Product Eligibility",
      "destructive": false
    },
    "create_coupon": {
      "op": "coupons/create-coupon",
      "method": "POST",
      "path": "/coupons",
      "summary": "Create Coupon",
      "destructive": false
    },
    "delete_coupon": {
      "op": "coupons/delete-coupon",
      "method": "DELETE",
      "path": "/coupons/{id}",
      "summary": "Coupon",
      "destructive": true
    },
    "get_coupon": {
      "op": "coupons/get-coupon",
      "method": "GET",
      "path": "/coupons/{id}",
      "summary": "Coupon Details",
      "destructive": false
    },
    "get_coupon_settings": {
      "op": "coupons/get-coupon-settings",
      "method": "GET",
      "path": "/coupons/getSettings",
      "summary": "Coupon Settings",
      "destructive": false
    },
    "list_coupon_codes": {
      "op": "coupons/list-coupon-codes",
      "method": "GET",
      "path": "/coupons/listCoupons",
      "summary": "List Coupon Codes",
      "destructive": false
    },
    "list_coupons": {
      "op": "coupons/list-coupons",
      "method": "GET",
      "path": "/coupons",
      "summary": "List Coupons",
      "destructive": false
    },
    "re_apply_coupons": {
      "op": "coupons/re-apply-coupons",
      "method": "POST",
      "path": "/coupons/re-apply",
      "summary": "Re-apply Coupons",
      "destructive": false
    },
    "store_coupon_settings": {
      "op": "coupons/store-coupon-settings",
      "method": "POST",
      "path": "/coupons/storeCouponSettings",
      "summary": "Store Coupon Settings",
      "destructive": false
    },
    "update_coupon": {
      "op": "coupons/update-coupon",
      "method": "PUT",
      "path": "/coupons/{id}",
      "summary": "Update Coupon",
      "destructive": false
    }
  },
  "cart_subscriptions": {
    "cancel_auto_renew": {
      "op": "subscriptions/cancel-auto-renew",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/cancel-auto-renew",
      "summary": "Cancel Auto-Renew",
      "destructive": true
    },
    "cancel_subscription": {
      "op": "subscriptions/cancel-subscription",
      "method": "PUT",
      "path": "/orders/{order}/subscriptions/{subscription}/cancel",
      "summary": "Cancel Subscription",
      "destructive": true
    },
    "confirm_subscription_switch": {
      "op": "subscriptions/confirm-subscription-switch",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/confirm-subscription-switch",
      "summary": "Confirm Subscription Switch",
      "destructive": false
    },
    "fetch_subscription_remote": {
      "op": "subscriptions/fetch-subscription-remote",
      "method": "PUT",
      "path": "/orders/{order}/subscriptions/{subscription}/fetch",
      "summary": "Fetch Subscription from Remote",
      "destructive": false
    },
    "generate_early_payment_link": {
      "op": "subscriptions/generate-early-payment-link",
      "method": "POST",
      "path": "/orders/{order}/subscriptions/{subscription}/early-payment-link",
      "summary": "Generate Early Payment Link",
      "destructive": false
    },
    "get_customer_subscription": {
      "op": "subscriptions/get-customer-subscription",
      "method": "GET",
      "path": "/customer-profile/subscriptions/{subscription_uuid}",
      "summary": "Get Customer Subscription Details",
      "destructive": false
    },
    "get_or_create_plan": {
      "op": "subscriptions/get-or-create-plan",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/get-or-create-plan",
      "summary": "Get or Create Plan",
      "destructive": false
    },
    "get_setup_intent_attempts": {
      "op": "subscriptions/get-setup-intent-attempts",
      "method": "GET",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/setup-intent-attempts",
      "summary": "Get Setup Intent Remaining Attempts",
      "destructive": false
    },
    "get_subscription": {
      "op": "subscriptions/get-subscription",
      "method": "GET",
      "path": "/subscriptions/{subscriptionOrderId}",
      "summary": "Get Subscription Details",
      "destructive": false
    },
    "initiate_early_payment": {
      "op": "subscriptions/initiate-early-payment",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/initiate-early-payment",
      "summary": "Initiate Early Payment",
      "destructive": false
    },
    "list_customer_subscriptions": {
      "op": "subscriptions/list-customer-subscriptions",
      "method": "GET",
      "path": "/customer-profile/subscriptions",
      "summary": "List Customer Subscriptions",
      "destructive": false
    },
    "list_subscriptions": {
      "op": "subscriptions/list-subscriptions",
      "method": "GET",
      "path": "/subscriptions",
      "summary": "List Subscriptions",
      "destructive": false
    },
    "pause_subscription": {
      "op": "subscriptions/pause-subscription",
      "method": "PUT",
      "path": "/orders/{order}/subscriptions/{subscription}/pause",
      "summary": "Pause Subscription",
      "destructive": false
    },
    "reactivate_subscription": {
      "op": "subscriptions/reactivate-subscription",
      "method": "PUT",
      "path": "/orders/{order}/subscriptions/{subscription}/reactivate",
      "summary": "Reactivate Subscription",
      "destructive": false
    },
    "resume_subscription": {
      "op": "subscriptions/resume-subscription",
      "method": "PUT",
      "path": "/orders/{order}/subscriptions/{subscription}/resume",
      "summary": "Resume Subscription",
      "destructive": false
    },
    "switch_payment_method": {
      "op": "subscriptions/switch-payment-method",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/switch-payment-method",
      "summary": "Switch Payment Method",
      "destructive": false
    },
    "update_payment_method": {
      "op": "subscriptions/update-payment-method",
      "method": "POST",
      "path": "/customer-profile/subscriptions/{subscription_uuid}/update-payment-method",
      "summary": "Update Payment Method",
      "destructive": false
    }
  },
  "cart_tax": {
    "create_tax_class": {
      "op": "tax/create-tax-class",
      "method": "POST",
      "path": "/tax/classes",
      "summary": "Create Tax Class",
      "destructive": false
    },
    "create_tax_rate": {
      "op": "tax/create-tax-rate",
      "method": "POST",
      "path": "/tax/country/rate",
      "summary": "Create Tax Rate",
      "destructive": false
    },
    "delete_country_rates": {
      "op": "tax/delete-country-rates",
      "method": "DELETE",
      "path": "/tax/country/{country_code}",
      "summary": "Delete All Rates for a Country",
      "destructive": true
    },
    "delete_oss_shipping_tax_override": {
      "op": "tax/delete-oss-shipping-tax-override",
      "method": "DELETE",
      "path": "/tax/configuration/settings/eu-vat/oss/shipping-override",
      "summary": "Delete OSS Shipping Tax Override",
      "destructive": true
    },
    "delete_oss_tax_override": {
      "op": "tax/delete-oss-tax-override",
      "method": "DELETE",
      "path": "/tax/configuration/settings/eu-vat/oss/override",
      "summary": "Delete OSS Tax Override",
      "destructive": true
    },
    "delete_shipping_tax_override": {
      "op": "tax/delete-shipping-tax-override",
      "method": "DELETE",
      "path": "/tax/rates/country/override/{id}",
      "summary": "Delete Shipping Tax Override",
      "destructive": true
    },
    "delete_tax_class": {
      "op": "tax/delete-tax-class",
      "method": "DELETE",
      "path": "/tax/classes/{id}",
      "summary": "Delete Tax Class",
      "destructive": true
    },
    "delete_tax_rate": {
      "op": "tax/delete-tax-rate",
      "method": "DELETE",
      "path": "/tax/country/rate/{id}",
      "summary": "Delete Tax Rate",
      "destructive": true
    },
    "get_country_tax_id": {
      "op": "tax/get-country-tax-id",
      "method": "GET",
      "path": "/tax/country-tax-id/{country_code}",
      "summary": "Get Country Tax ID",
      "destructive": false
    },
    "get_country_tax_rates": {
      "op": "tax/get-country-tax-rates",
      "method": "GET",
      "path": "/tax/rates/country/rates/{country_code}",
      "summary": "Get Country Tax Rates",
      "destructive": false
    },
    "get_eu_tax_rates": {
      "op": "tax/get-eu-tax-rates",
      "method": "GET",
      "path": "/tax/configuration/settings/eu-vat/rates",
      "summary": "Get EU Tax Rates",
      "destructive": false
    },
    "get_preconfigured_tax_rates": {
      "op": "tax/get-preconfigured-tax-rates",
      "method": "GET",
      "path": "/tax/configuration/rates",
      "summary": "Get Preconfigured Tax Rates",
      "destructive": false
    },
    "get_tax_settings": {
      "op": "tax/get-tax-settings",
      "method": "GET",
      "path": "/tax/configuration/settings",
      "summary": "Get Tax Settings",
      "destructive": false
    },
    "list_all_tax_rates": {
      "op": "tax/list-all-tax-rates",
      "method": "GET",
      "path": "/tax/rates",
      "summary": "List All Tax Rates",
      "destructive": false
    },
    "list_tax_classes": {
      "op": "tax/list-tax-classes",
      "method": "GET",
      "path": "/tax/classes",
      "summary": "List Tax Classes",
      "destructive": false
    },
    "list_tax_records": {
      "op": "tax/list-tax-records",
      "method": "GET",
      "path": "/taxes",
      "summary": "List Tax Records",
      "destructive": false
    },
    "mark_taxes_as_filed": {
      "op": "tax/mark-taxes-as-filed",
      "method": "POST",
      "path": "/taxes",
      "summary": "Mark Taxes as Filed",
      "destructive": false
    },
    "save_configured_countries": {
      "op": "tax/save-configured-countries",
      "method": "POST",
      "path": "/tax/configuration/countries",
      "summary": "Save Configured Countries",
      "destructive": false
    },
    "save_country_tax_id": {
      "op": "tax/save-country-tax-id",
      "method": "POST",
      "path": "/tax/country-tax-id/{country_code}",
      "summary": "Save Country Tax ID",
      "destructive": false
    },
    "save_eu_vat_cross_border_settings": {
      "op": "tax/save-eu-vat-cross-border-settings",
      "method": "POST",
      "path": "/tax/configuration/settings/eu-vat",
      "summary": "Save EU VAT Cross-Border Settings",
      "destructive": false
    },
    "save_oss_shipping_tax_override": {
      "op": "tax/save-oss-shipping-tax-override",
      "method": "POST",
      "path": "/tax/configuration/settings/eu-vat/oss/shipping-override",
      "summary": "Save OSS Shipping Tax Override",
      "destructive": false
    },
    "save_oss_tax_override": {
      "op": "tax/save-oss-tax-override",
      "method": "POST",
      "path": "/tax/configuration/settings/eu-vat/oss/override",
      "summary": "Save OSS Tax Override",
      "destructive": false
    },
    "save_shipping_tax_override": {
      "op": "tax/save-shipping-tax-override",
      "method": "POST",
      "path": "/tax/rates/country/override",
      "summary": "Save Shipping Tax Override",
      "destructive": false
    },
    "save_tax_settings": {
      "op": "tax/save-tax-settings",
      "method": "POST",
      "path": "/tax/configuration/settings",
      "summary": "Save Tax Settings",
      "destructive": false
    },
    "update_tax_class": {
      "op": "tax/update-tax-class",
      "method": "PUT",
      "path": "/tax/classes/{id}",
      "summary": "Update Tax Class",
      "destructive": false
    },
    "update_tax_rate": {
      "op": "tax/update-tax-rate",
      "method": "PUT",
      "path": "/tax/country/rate/{id}",
      "summary": "Update Tax Rate",
      "destructive": false
    }
  },
  "cart_shipping": {
    "create_shipping_class": {
      "op": "shipping/create-shipping-class",
      "method": "POST",
      "path": "/shipping/classes",
      "summary": "Create Shipping Class",
      "destructive": false
    },
    "create_shipping_method": {
      "op": "shipping/create-shipping-method",
      "method": "POST",
      "path": "/shipping/methods",
      "summary": "Create Shipping Method",
      "destructive": false
    },
    "create_shipping_zone": {
      "op": "shipping/create-shipping-zone",
      "method": "POST",
      "path": "/shipping/zones",
      "summary": "Create Shipping Zone",
      "destructive": false
    },
    "delete_shipping_class": {
      "op": "shipping/delete-shipping-class",
      "method": "DELETE",
      "path": "/shipping/classes/{id}",
      "summary": "Delete Shipping Class",
      "destructive": true
    },
    "delete_shipping_method": {
      "op": "shipping/delete-shipping-method",
      "method": "DELETE",
      "path": "/shipping/methods/{method_id}",
      "summary": "Delete Shipping Method",
      "destructive": true
    },
    "delete_shipping_zone": {
      "op": "shipping/delete-shipping-zone",
      "method": "DELETE",
      "path": "/shipping/zones/{id}",
      "summary": "Delete Shipping Zone",
      "destructive": true
    },
    "get_shipping_class": {
      "op": "shipping/get-shipping-class",
      "method": "GET",
      "path": "/shipping/classes/{id}",
      "summary": "Get Shipping Class",
      "destructive": false
    },
    "get_shipping_zone": {
      "op": "shipping/get-shipping-zone",
      "method": "GET",
      "path": "/shipping/zones/{id}",
      "summary": "Get Shipping Zone",
      "destructive": false
    },
    "get_zone_states": {
      "op": "shipping/get-zone-states",
      "method": "GET",
      "path": "/shipping/zone/states",
      "summary": "Get Zone States",
      "destructive": false
    },
    "list_shipping_classes": {
      "op": "shipping/list-shipping-classes",
      "method": "GET",
      "path": "/shipping/classes",
      "summary": "List Shipping Classes",
      "destructive": false
    },
    "list_shipping_zones": {
      "op": "shipping/list-shipping-zones",
      "method": "GET",
      "path": "/shipping/zones",
      "summary": "List Shipping Zones",
      "destructive": false
    },
    "update_shipping_class": {
      "op": "shipping/update-shipping-class",
      "method": "PUT",
      "path": "/shipping/classes/{id}",
      "summary": "Update Shipping Class",
      "destructive": false
    },
    "update_shipping_method": {
      "op": "shipping/update-shipping-method",
      "method": "PUT",
      "path": "/shipping/methods",
      "summary": "Update Shipping Method",
      "destructive": false
    },
    "update_shipping_zone": {
      "op": "shipping/update-shipping-zone",
      "method": "PUT",
      "path": "/shipping/zones/{id}",
      "summary": "Update Shipping Zone",
      "destructive": false
    },
    "update_zone_order": {
      "op": "shipping/update-zone-order",
      "method": "POST",
      "path": "/shipping/zones/update-order",
      "summary": "Update Zone Order",
      "destructive": false
    }
  },
  "cart_settings": {
    "activate_payment_addon": {
      "op": "settings/activate-payment-addon",
      "method": "POST",
      "path": "/settings/payment-methods/activate-addon",
      "summary": "Activate Payment Addon",
      "destructive": false
    },
    "activate_plugin_addon": {
      "op": "settings/activate-plugin-addon",
      "method": "POST",
      "path": "/settings/modules/plugin-addons/activate",
      "summary": "Activate Plugin Addon",
      "destructive": false
    },
    "check_paypal_webhook": {
      "op": "settings/check-paypal-webhook",
      "method": "GET",
      "path": "/settings/payment-methods/paypal/webhook/check",
      "summary": "Check PayPal Webhook",
      "destructive": false
    },
    "disconnect_payment_method": {
      "op": "settings/disconnect-payment-method",
      "method": "POST",
      "path": "/settings/payment-methods/disconnect",
      "summary": "Disconnect Payment Method",
      "destructive": true
    },
    "exchange_paypal_seller_auth_token": {
      "op": "settings/exchange-paypal-seller-auth-token",
      "method": "POST",
      "path": "/settings/payment-methods/paypal/seller-auth-token",
      "summary": "Exchange PayPal Seller Auth Token",
      "destructive": false
    },
    "get_active_storage_drivers": {
      "op": "settings/get-active-storage-drivers",
      "method": "GET",
      "path": "/settings/storage-drivers/active-drivers",
      "summary": "Get Active Storage Drivers",
      "destructive": false
    },
    "get_checkout_fields": {
      "op": "settings/get-checkout-fields",
      "method": "GET",
      "path": "/checkout-fields/get-fields",
      "summary": "Get Checkout Fields",
      "destructive": false
    },
    "get_email_shortcodes": {
      "op": "settings/get-email-shortcodes",
      "method": "GET",
      "path": "/settings/confirmation/shortcode",
      "summary": "Get Email Shortcodes",
      "destructive": false
    },
    "get_module_settings": {
      "op": "settings/get-module-settings",
      "method": "GET",
      "path": "/settings/modules",
      "summary": "Get Module Settings",
      "destructive": false
    },
    "get_payment_method_connection_info": {
      "op": "settings/get-payment-method-connection-info",
      "method": "GET",
      "path": "/settings/payment-methods/connect/info",
      "summary": "Get Payment Method Connection Info",
      "destructive": false
    },
    "get_payment_method_settings": {
      "op": "settings/get-payment-method-settings",
      "method": "GET",
      "path": "/settings/payment-methods",
      "summary": "Get Payment Method Settings",
      "destructive": false
    },
    "get_permissions": {
      "op": "settings/get-permissions",
      "method": "GET",
      "path": "/settings/permissions",
      "summary": "Get Permissions",
      "destructive": false
    },
    "get_plugin_addons": {
      "op": "settings/get-plugin-addons",
      "method": "GET",
      "path": "/settings/modules/plugin-addons",
      "summary": "Get Plugin Addons",
      "destructive": false
    },
    "get_storage_driver_settings": {
      "op": "settings/get-storage-driver-settings",
      "method": "GET",
      "path": "/settings/storage-drivers/{driver}",
      "summary": "Get Storage Driver Settings",
      "destructive": false
    },
    "get_store_settings": {
      "op": "settings/get-store-settings",
      "method": "GET",
      "path": "/settings/store",
      "summary": "Get Store Settings",
      "destructive": false
    },
    "install_payment_addon": {
      "op": "settings/install-payment-addon",
      "method": "POST",
      "path": "/settings/payment-methods/install-addon",
      "summary": "Install Payment Addon",
      "destructive": false
    },
    "install_plugin_addon": {
      "op": "settings/install-plugin-addon",
      "method": "POST",
      "path": "/settings/modules/plugin-addons/install",
      "summary": "Install Plugin Addon",
      "destructive": false
    },
    "list_all_payment_methods": {
      "op": "settings/list-all-payment-methods",
      "method": "GET",
      "path": "/settings/payment-methods/all",
      "summary": "List All Payment Methods",
      "destructive": false
    },
    "list_all_storage_drivers": {
      "op": "settings/list-all-storage-drivers",
      "method": "GET",
      "path": "/settings/storage-drivers",
      "summary": "List All Storage Drivers",
      "destructive": false
    },
    "reorder_payment_methods": {
      "op": "settings/reorder-payment-methods",
      "method": "POST",
      "path": "/settings/payment-methods/reorder",
      "summary": "Reorder Payment Methods",
      "destructive": false
    },
    "save_checkout_fields": {
      "op": "settings/save-checkout-fields",
      "method": "POST",
      "path": "/checkout-fields/save-fields",
      "summary": "Save Checkout Fields",
      "destructive": false
    },
    "save_confirmation_settings": {
      "op": "settings/save-confirmation-settings",
      "method": "POST",
      "path": "/settings/confirmation",
      "summary": "Save Confirmation Settings",
      "destructive": false
    },
    "save_module_settings": {
      "op": "settings/save-module-settings",
      "method": "POST",
      "path": "/settings/modules",
      "summary": "Save Module Settings",
      "destructive": false
    },
    "save_payment_method_design": {
      "op": "settings/save-payment-method-design",
      "method": "POST",
      "path": "/settings/payment-methods/design",
      "summary": "Save Payment Method Design",
      "destructive": false
    },
    "save_payment_method_settings": {
      "op": "settings/save-payment-method-settings",
      "method": "POST",
      "path": "/settings/payment-methods",
      "summary": "Save Payment Method Settings",
      "destructive": false
    },
    "save_permissions": {
      "op": "settings/save-permissions",
      "method": "POST",
      "path": "/settings/permissions",
      "summary": "Save Permissions",
      "destructive": false
    },
    "save_storage_driver_settings": {
      "op": "settings/save-storage-driver-settings",
      "method": "POST",
      "path": "/settings/storage-drivers",
      "summary": "Save Storage Driver Settings",
      "destructive": false
    },
    "save_store_settings": {
      "op": "settings/save-store-settings",
      "method": "POST",
      "path": "/settings/store",
      "summary": "Save Store Settings",
      "destructive": false
    },
    "setup_paypal_webhook": {
      "op": "settings/setup-paypal-webhook",
      "method": "POST",
      "path": "/settings/payment-methods/paypal/webhook/setup",
      "summary": "Setup PayPal Webhook",
      "destructive": false
    },
    "verify_storage_driver_connection": {
      "op": "settings/verify-storage-driver-connection",
      "method": "POST",
      "path": "/settings/storage-drivers/verify-info",
      "summary": "Verify Storage Driver Connection",
      "destructive": false
    }
  },
  "cart_email_notifications": {
    "enable_notification": {
      "op": "email-notification/enable-notification",
      "method": "POST",
      "path": "/email-notification/enable-notification/{name}",
      "summary": "Enable/Disable Notification",
      "destructive": false
    },
    "get_notification": {
      "op": "email-notification/get-notification",
      "method": "GET",
      "path": "/email-notification/{notification}",
      "summary": "Get Single Notification",
      "destructive": false
    },
    "get_reminders": {
      "op": "email-notification/get-reminders",
      "method": "GET",
      "path": "/email-notification/reminders",
      "summary": "Get Scheduling Settings",
      "destructive": false
    },
    "get_settings": {
      "op": "email-notification/get-settings",
      "method": "GET",
      "path": "/email-notification/get-settings",
      "summary": "Get Global Email Settings",
      "destructive": false
    },
    "get_shortcodes": {
      "op": "email-notification/get-shortcodes",
      "method": "GET",
      "path": "/email-notification/get-short-codes",
      "summary": "Get Shortcodes",
      "destructive": false
    },
    "list_notifications": {
      "op": "email-notification/list-notifications",
      "method": "GET",
      "path": "/email-notification",
      "summary": "List All Notifications",
      "destructive": false
    },
    "preview_default_template": {
      "op": "email-notification/preview-default-template",
      "method": "POST",
      "path": "/email-notification/preview-default-template",
      "summary": "Preview Default Template",
      "destructive": false
    },
    "preview_notification": {
      "op": "email-notification/preview-notification",
      "method": "POST",
      "path": "/email-notification/preview",
      "summary": "Preview Notification",
      "destructive": false
    },
    "save_reminders": {
      "op": "email-notification/save-reminders",
      "method": "POST",
      "path": "/email-notification/reminders",
      "summary": "Save Scheduling Settings",
      "destructive": false
    },
    "save_settings": {
      "op": "email-notification/save-settings",
      "method": "POST",
      "path": "/email-notification/save-settings",
      "summary": "Save Global Email Settings",
      "destructive": false
    },
    "update_notification": {
      "op": "email-notification/update-notification",
      "method": "PUT",
      "path": "/email-notification/{notification}",
      "summary": "Update Notification",
      "destructive": false
    }
  },
  "cart_reports": {
    "country_heat_map": {
      "op": "reports/country-heat-map",
      "method": "GET",
      "path": "/reports/country-heat-map",
      "summary": "Get Country Heat Map",
      "destructive": false
    },
    "customer_report": {
      "op": "reports/customer-report",
      "method": "GET",
      "path": "/reports/customer-report",
      "summary": "Get Customer Report",
      "destructive": false
    },
    "daily_signups": {
      "op": "reports/daily-signups",
      "method": "GET",
      "path": "/reports/daily-signups",
      "summary": "Get Daily Signups",
      "destructive": false
    },
    "dashboard_stats": {
      "op": "reports/dashboard-stats",
      "method": "GET",
      "path": "/reports/dashboard-stats",
      "summary": "Get Dashboard Stats",
      "destructive": false
    },
    "fetch_new_vs_returning_customer": {
      "op": "reports/fetch-new-vs-returning-customer",
      "method": "GET",
      "path": "/reports/fetch-new-vs-returning-customer",
      "summary": "Get New vs Returning Customers",
      "destructive": false
    },
    "fetch_order_by_group": {
      "op": "reports/fetch-order-by-group",
      "method": "GET",
      "path": "/reports/fetch-order-by-group",
      "summary": "Get Orders by Group",
      "destructive": false
    },
    "fetch_report_by_day_and_hour": {
      "op": "reports/fetch-report-by-day-and-hour",
      "method": "GET",
      "path": "/reports/fetch-report-by-day-and-hour",
      "summary": "Get Report by Day and Hour",
      "destructive": false
    },
    "fetch_report_meta": {
      "op": "reports/fetch-report-meta",
      "method": "GET",
      "path": "/reports/fetch-report-meta",
      "summary": "Get Report Meta",
      "destructive": false
    },
    "fetch_top_sold_products": {
      "op": "reports/fetch-top-sold-products",
      "method": "GET",
      "path": "/reports/fetch-top-sold-products",
      "summary": "Get Top Sold Products",
      "destructive": false
    },
    "fetch_top_sold_variants": {
      "op": "reports/fetch-top-sold-variants",
      "method": "GET",
      "path": "/reports/fetch-top-sold-variants",
      "summary": "Get Top Sold Variants",
      "destructive": false
    },
    "future_renewals": {
      "op": "reports/future-renewals",
      "method": "GET",
      "path": "/reports/future-renewals",
      "summary": "Get Future Renewals",
      "destructive": false
    },
    "get_dashboard_summary": {
      "op": "reports/get-dashboard-summary",
      "method": "GET",
      "path": "/reports/get-dashboard-summary",
      "summary": "Get Dashboard Summary",
      "destructive": false
    },
    "get_overview": {
      "op": "reports/get-overview",
      "method": "GET",
      "path": "/reports/overview",
      "summary": "Get Revenue Overview",
      "destructive": false
    },
    "get_recent_activities": {
      "op": "reports/get-recent-activities",
      "method": "GET",
      "path": "/reports/get-recent-activities",
      "summary": "Get Recent Activities",
      "destructive": false
    },
    "get_recent_orders": {
      "op": "reports/get-recent-orders",
      "method": "GET",
      "path": "/reports/get-recent-orders",
      "summary": "Get Recent Orders",
      "destructive": false
    },
    "get_revenue": {
      "op": "reports/get-revenue",
      "method": "GET",
      "path": "/reports/revenue",
      "summary": "Get Revenue Data",
      "destructive": false
    },
    "item_count_distribution": {
      "op": "reports/item-count-distribution",
      "method": "GET",
      "path": "/reports/item-count-distribution",
      "summary": "Get Item Count Distribution",
      "destructive": false
    },
    "license_chart": {
      "op": "reports/license-chart",
      "method": "GET",
      "path": "/reports/license-chart",
      "summary": "Get License Line Chart",
      "destructive": false
    },
    "license_pie_chart": {
      "op": "reports/license-pie-chart",
      "method": "GET",
      "path": "/reports/license-pie-chart",
      "summary": "Get License Pie Chart",
      "destructive": false
    },
    "license_summary": {
      "op": "reports/license-summary",
      "method": "GET",
      "path": "/reports/license-summary",
      "summary": "Get License Summary",
      "destructive": false
    },
    "order_chart": {
      "op": "reports/order-chart",
      "method": "GET",
      "path": "/reports/order-chart",
      "summary": "Get Order Chart",
      "destructive": false
    },
    "order_completion_time": {
      "op": "reports/order-completion-time",
      "method": "GET",
      "path": "/reports/order-completion-time",
      "summary": "Get Order Completion Time",
      "destructive": false
    },
    "order_value_distribution": {
      "op": "reports/order-value-distribution",
      "method": "GET",
      "path": "/reports/order-value-distribution",
      "summary": "Get Order Value Distribution",
      "destructive": false
    },
    "product_performance": {
      "op": "reports/product-performance",
      "method": "GET",
      "path": "/reports/product-performance",
      "summary": "Get Product Performance",
      "destructive": false
    },
    "product_report": {
      "op": "reports/product-report",
      "method": "GET",
      "path": "/reports/product-report",
      "summary": "Get Product Report",
      "destructive": false
    },
    "quick_order_stats": {
      "op": "reports/quick-order-stats",
      "method": "GET",
      "path": "/reports/quick-order-stats",
      "summary": "Get Quick Order Stats",
      "destructive": false
    },
    "refund_chart": {
      "op": "reports/refund-chart",
      "method": "GET",
      "path": "/reports/refund-chart",
      "summary": "Get Refund Chart",
      "destructive": false
    },
    "refund_data_by_group": {
      "op": "reports/refund-data-by-group",
      "method": "GET",
      "path": "/reports/refund-data-by-group",
      "summary": "Get Refund Data by Group",
      "destructive": false
    },
    "report_overview": {
      "op": "reports/report-overview",
      "method": "GET",
      "path": "/reports/report-overview",
      "summary": "Get Report Overview",
      "destructive": false
    },
    "retention_chart": {
      "op": "reports/retention-chart",
      "method": "GET",
      "path": "/reports/retention-chart",
      "summary": "Get Retention Chart",
      "destructive": false
    },
    "revenue_by_group": {
      "op": "reports/revenue-by-group",
      "method": "GET",
      "path": "/reports/revenue-by-group",
      "summary": "Get Revenue by Group",
      "destructive": false
    },
    "sales_growth": {
      "op": "reports/sales-growth",
      "method": "GET",
      "path": "/reports/sales-growth",
      "summary": "Get Sales Growth",
      "destructive": false
    },
    "sales_growth_chart": {
      "op": "reports/sales-growth-chart",
      "method": "GET",
      "path": "/reports/sales-growth-chart",
      "summary": "Get Sales Growth Chart",
      "destructive": false
    },
    "sales_report": {
      "op": "reports/sales-report",
      "method": "GET",
      "path": "/reports/sales-report",
      "summary": "Get Sales Report",
      "destructive": false
    },
    "search_repeat_customer": {
      "op": "reports/search-repeat-customer",
      "method": "GET",
      "path": "/reports/search-repeat-customer",
      "summary": "Search Repeat Customers",
      "destructive": false
    },
    "sources": {
      "op": "reports/sources",
      "method": "GET",
      "path": "/reports/sources",
      "summary": "Get Source Report",
      "destructive": false
    },
    "subscription_chart": {
      "op": "reports/subscription-chart",
      "method": "GET",
      "path": "/reports/subscription-chart",
      "summary": "Get Subscription Chart",
      "destructive": false
    },
    "subscription_cohorts": {
      "op": "reports/subscription-cohorts",
      "method": "GET",
      "path": "/reports/subscription-cohorts",
      "summary": "Get Subscription Cohorts",
      "destructive": false
    },
    "subscription_retention": {
      "op": "reports/subscription-retention",
      "method": "GET",
      "path": "/reports/subscription-retention",
      "summary": "Get Subscription Retention",
      "destructive": false
    },
    "top_products_sold": {
      "op": "reports/top-products-sold",
      "method": "GET",
      "path": "/reports/top-products-sold",
      "summary": "Get Top Products Sold",
      "destructive": false
    },
    "weeks_between_refund": {
      "op": "reports/weeks-between-refund",
      "method": "GET",
      "path": "/reports/weeks-between-refund",
      "summary": "Get Weeks Between Refund",
      "destructive": false
    }
  },
  "cart_integrations": {
    "chained_data_request": {
      "op": "integration/chained-data-request",
      "method": "POST",
      "path": "/integration/feed/chained",
      "summary": "Chained Data Request",
      "destructive": false
    },
    "change_feed_status": {
      "op": "integration/change-feed-status",
      "method": "POST",
      "path": "/integration/global-feeds/change-status/{integration_id}",
      "summary": "Change Feed Status",
      "destructive": false
    },
    "change_product_feed_status": {
      "op": "integration/change-product-feed-status",
      "method": "POST",
      "path": "/products/{product_id}/integrations/feed/change-status",
      "summary": "Change Product Feed Status",
      "destructive": false
    },
    "delete_feed": {
      "op": "integration/delete-feed",
      "method": "DELETE",
      "path": "/integration/global-feeds/{integration_id}",
      "summary": "Feed",
      "destructive": true
    },
    "delete_product_integration": {
      "op": "integration/delete-product-integration",
      "method": "DELETE",
      "path": "/products/{product_id}/integrations/{integration_id}",
      "summary": "Product Integration Feed",
      "destructive": true
    },
    "get_dynamic_options": {
      "op": "integration/get-dynamic-options",
      "method": "GET",
      "path": "/integration/feed/dynamic_options",
      "summary": "Dynamic Options",
      "destructive": false
    },
    "get_feed_lists": {
      "op": "integration/get-feed-lists",
      "method": "GET",
      "path": "/integration/feed/lists",
      "summary": "Feed Merge Fields (Lists)",
      "destructive": false
    },
    "get_feed_settings": {
      "op": "integration/get-feed-settings",
      "method": "GET",
      "path": "/integration/global-feeds/settings",
      "summary": "Feed Settings",
      "destructive": false
    },
    "get_global_feeds": {
      "op": "integration/get-global-feeds",
      "method": "GET",
      "path": "/integration/global-feeds",
      "summary": "List Global Integration Feeds",
      "destructive": false
    },
    "get_global_settings": {
      "op": "integration/get-global-settings",
      "method": "GET",
      "path": "/integration/global-settings",
      "summary": "Global Integration Settings",
      "destructive": false
    },
    "get_product_integration_settings": {
      "op": "integration/get-product-integration-settings",
      "method": "GET",
      "path": "/products/{product_id}/integrations/{integration_name}/settings",
      "summary": "Product Integration Settings",
      "destructive": false
    },
    "install_addon_plugin": {
      "op": "integration/install-addon-plugin",
      "method": "POST",
      "path": "/integration/feed/install-plugin",
      "summary": "Install and Activate Add-on Plugin",
      "destructive": false
    },
    "list_addons": {
      "op": "integration/list-addons",
      "method": "GET",
      "path": "/integration/addons",
      "summary": "List Available Add-ons",
      "destructive": false
    },
    "list_product_feeds": {
      "op": "integration/list-product-feeds",
      "method": "GET",
      "path": "/products/{productId}/integrations",
      "summary": "List Product Integration Feeds",
      "destructive": false
    },
    "save_feed_settings": {
      "op": "integration/save-feed-settings",
      "method": "POST",
      "path": "/integration/global-feeds/settings",
      "summary": "Save Feed Settings",
      "destructive": false
    },
    "save_product_integration": {
      "op": "integration/save-product-integration",
      "method": "POST",
      "path": "/products/{product_id}/integrations",
      "summary": "Save Product Integration Feed",
      "destructive": false
    },
    "set_global_settings": {
      "op": "integration/set-global-settings",
      "method": "POST",
      "path": "/integration/global-settings",
      "summary": "Save Global Integration Settings",
      "destructive": false
    }
  },
  "cart_files": {
    "delete_file": {
      "op": "files/delete-file",
      "method": "DELETE",
      "path": "/files/delete",
      "summary": "Delete File",
      "destructive": true
    },
    "get_bucket_list": {
      "op": "files/get-bucket-list",
      "method": "GET",
      "path": "/files/bucket-list",
      "summary": "Get Bucket List",
      "destructive": false
    },
    "list_files": {
      "op": "files/list-files",
      "method": "GET",
      "path": "/files",
      "summary": "List Files",
      "destructive": false
    },
    "upload_editor_file": {
      "op": "files/upload-editor-file",
      "method": "POST",
      "path": "/upload-editor-file",
      "summary": "Upload Editor File",
      "destructive": false
    },
    "upload_file": {
      "op": "files/upload-file",
      "method": "POST",
      "path": "/files/upload",
      "summary": "Upload File",
      "destructive": false
    }
  },
  "cart_labels_attributes": {
    "change_term_sort_order": {
      "op": "labels-attributes/change-term-sort-order",
      "method": "POST",
      "path": "/options/attr/group/{group_id}/term/{term_id}/serial",
      "summary": "Change Term Sort Order",
      "destructive": false
    },
    "create_attribute_group": {
      "op": "labels-attributes/create-attribute-group",
      "method": "POST",
      "path": "/options/attr/group",
      "summary": "Create Attribute Group",
      "destructive": false
    },
    "create_attribute_term": {
      "op": "labels-attributes/create-attribute-term",
      "method": "POST",
      "path": "/options/attr/group/{group_id}/term",
      "summary": "Create Attribute Term",
      "destructive": false
    },
    "create_label": {
      "op": "labels-attributes/create-label",
      "method": "POST",
      "path": "/labels",
      "summary": "Create Label",
      "destructive": false
    },
    "delete_attribute_group": {
      "op": "labels-attributes/delete-attribute-group",
      "method": "DELETE",
      "path": "/options/attr/group/{group_id}",
      "summary": "Delete Attribute Group",
      "destructive": true
    },
    "delete_attribute_term": {
      "op": "labels-attributes/delete-attribute-term",
      "method": "DELETE",
      "path": "/options/attr/group/{group_id}/term/{term_id}",
      "summary": "Delete Attribute Term",
      "destructive": true
    },
    "get_attribute_group": {
      "op": "labels-attributes/get-attribute-group",
      "method": "GET",
      "path": "/options/attr/group/{group_id}",
      "summary": "Get Attribute Group",
      "destructive": false
    },
    "list_attribute_groups": {
      "op": "labels-attributes/list-attribute-groups",
      "method": "GET",
      "path": "/options/attr/groups",
      "summary": "List Attribute Groups",
      "destructive": false
    },
    "list_attribute_terms": {
      "op": "labels-attributes/list-attribute-terms",
      "method": "GET",
      "path": "/options/attr/group/{group_id}/terms",
      "summary": "List Attribute Terms",
      "destructive": false
    },
    "list_labels": {
      "op": "labels-attributes/list-labels",
      "method": "GET",
      "path": "/labels",
      "summary": "List Labels",
      "destructive": false
    },
    "update_attribute_group": {
      "op": "labels-attributes/update-attribute-group",
      "method": "PUT",
      "path": "/options/attr/group/{group_id}",
      "summary": "Update Attribute Group",
      "destructive": false
    },
    "update_attribute_term": {
      "op": "labels-attributes/update-attribute-term",
      "method": "POST",
      "path": "/options/attr/group/{group_id}/term/{term_id}",
      "summary": "Update Attribute Term",
      "destructive": false
    },
    "update_label_selections": {
      "op": "labels-attributes/update-label-selections",
      "method": "POST",
      "path": "/labels/update-label-selections",
      "summary": "Update Label Selections",
      "destructive": false
    }
  },
  "cart_utilities": {
    "generate_retention_snapshots": {
      "op": "reports/generate-retention-snapshots",
      "method": "POST",
      "path": "/reports/retention-snapshots/generate",
      "summary": "Generate Retention Snapshots",
      "destructive": false
    },
    "retention_snapshots_status": {
      "op": "reports/retention-snapshots-status",
      "method": "GET",
      "path": "/reports/retention-snapshots/status",
      "summary": "Check Retention Snapshot Status",
      "destructive": false
    },
    "attach_note_to_order": {
      "op": "dashboard/attach-note-to-order",
      "method": "POST",
      "path": "/notes/attach",
      "summary": "Attach Note to Order",
      "destructive": false
    },
    "create_all_pages": {
      "op": "dashboard/create-all-pages",
      "method": "POST",
      "path": "/onboarding/create-pages",
      "summary": "Create All Pages",
      "destructive": false
    },
    "create_single_page": {
      "op": "dashboard/create-single-page",
      "method": "POST",
      "path": "/onboarding/create-page",
      "summary": "Create Single Page",
      "destructive": false
    },
    "delete_activity": {
      "op": "dashboard/delete-activity",
      "method": "DELETE",
      "path": "/activity/{id}",
      "summary": "Delete Activity",
      "destructive": true
    },
    "get_country_info": {
      "op": "dashboard/get-country-info",
      "method": "GET",
      "path": "/address-info/get-country-info",
      "summary": "Get Country Info",
      "destructive": false
    },
    "get_dashboard_stats": {
      "op": "dashboard/get-dashboard-stats",
      "method": "GET",
      "path": "/dashboard/stats",
      "summary": "Get Dashboard Stats",
      "destructive": false
    },
    "get_filter_options": {
      "op": "dashboard/get-filter-options",
      "method": "GET",
      "path": "/advance_filter/get-filter-options",
      "summary": "Get Filter Options",
      "destructive": false
    },
    "get_onboarding_data": {
      "op": "dashboard/get-onboarding-data",
      "method": "GET",
      "path": "/dashboard",
      "summary": "Get Onboarding Data",
      "destructive": false
    },
    "get_onboarding_settings": {
      "op": "dashboard/get-onboarding-settings",
      "method": "GET",
      "path": "/onboarding",
      "summary": "Get Onboarding Settings",
      "destructive": false
    },
    "get_print_templates": {
      "op": "dashboard/get-print-templates",
      "method": "GET",
      "path": "/templates/print-templates",
      "summary": "Get Print Templates",
      "destructive": false
    },
    "get_search_options": {
      "op": "dashboard/get-search-options",
      "method": "GET",
      "path": "/forms/search_options",
      "summary": "Get Search Options",
      "destructive": false
    },
    "get_widgets": {
      "op": "dashboard/get-widgets",
      "method": "GET",
      "path": "/widgets",
      "summary": "Get Widgets",
      "destructive": false
    },
    "initialize_app": {
      "op": "dashboard/initialize-app",
      "method": "GET",
      "path": "/app/init",
      "summary": "Initialize App",
      "destructive": false
    },
    "list_activities": {
      "op": "dashboard/list-activities",
      "method": "GET",
      "path": "/activity",
      "summary": "List Activities",
      "destructive": false
    },
    "list_attachments": {
      "op": "dashboard/list-attachments",
      "method": "GET",
      "path": "/app/attachments",
      "summary": "List Attachments",
      "destructive": false
    },
    "list_countries": {
      "op": "dashboard/list-countries",
      "method": "GET",
      "path": "/address-info/countries",
      "summary": "List Countries",
      "destructive": false
    },
    "mark_activity_read": {
      "op": "dashboard/mark-activity-read",
      "method": "PUT",
      "path": "/activity/{id}/mark-read",
      "summary": "Mark Activity Read/Unread",
      "destructive": false
    },
    "save_onboarding_settings": {
      "op": "dashboard/save-onboarding-settings",
      "method": "POST",
      "path": "/onboarding",
      "summary": "Save Onboarding Settings",
      "destructive": false
    },
    "save_print_templates": {
      "op": "dashboard/save-print-templates",
      "method": "PUT",
      "path": "/templates/print-templates",
      "summary": "Save Print Templates",
      "destructive": false
    },
    "upload_attachment": {
      "op": "dashboard/upload-attachment",
      "method": "POST",
      "path": "/app/upload-attachments",
      "summary": "Upload Attachment",
      "destructive": false
    }
  },
  "cart_storefront": {
    "get_product_views": {
      "op": "public-shop/get-product-views",
      "method": "GET",
      "path": "/public/product-views",
      "summary": "Get Product Views",
      "destructive": false
    },
    "list_products": {
      "op": "public-shop/list-products",
      "method": "GET",
      "path": "/public/products",
      "summary": "List Products",
      "destructive": false
    },
    "search_products": {
      "op": "public-shop/search-products",
      "method": "GET",
      "path": "/public/product-search",
      "summary": "Search Products",
      "destructive": false
    }
  },
  "cart_checkout": {
    "get_available_shipping_methods": {
      "op": "checkout/get-available-shipping-methods",
      "method": "GET",
      "path": "/checkout/get-available-shipping-methods",
      "summary": "Get Available Shipping Methods",
      "destructive": false
    },
    "get_checkout_summary": {
      "op": "checkout/get-checkout-summary",
      "method": "GET",
      "path": "/checkout/get-checkout-summary-view",
      "summary": "Get Checkout Summary",
      "destructive": false
    },
    "get_country_info": {
      "op": "checkout/get-country-info",
      "method": "GET",
      "path": "/checkout/get-country-info",
      "summary": "Get Country Info",
      "destructive": false
    },
    "get_order_info": {
      "op": "checkout/get-order-info",
      "method": "GET",
      "path": "/checkout/get-order-info",
      "summary": "Get Order Info",
      "destructive": false
    },
    "get_shipping_methods_list_view": {
      "op": "checkout/get-shipping-methods-list-view",
      "method": "GET",
      "path": "/checkout/get-shipping-methods-list-view",
      "summary": "Get Shipping Methods List View",
      "destructive": false
    },
    "login": {
      "op": "checkout/login",
      "method": "POST",
      "path": "/user/login",
      "summary": "Login",
      "destructive": false
    },
    "place_order": {
      "op": "checkout/place-order",
      "method": "POST",
      "path": "/checkout/place-order",
      "summary": "Place Order",
      "destructive": false
    }
  },
  "cart_customer_portal": {
    "create_address_checkout": {
      "op": "customer-profile/create-address-checkout",
      "method": "POST",
      "path": "/customers/add-address",
      "summary": "Create Address (Checkout)",
      "destructive": false
    },
    "create_profile_address": {
      "op": "customer-profile/create-profile-address",
      "method": "POST",
      "path": "/customer-profile/create-address",
      "summary": "Create Profile Address",
      "destructive": false
    },
    "dashboard_overview": {
      "op": "customer-profile/dashboard-overview",
      "method": "GET",
      "path": "/customer-profile/",
      "summary": "Dashboard Overview",
      "destructive": false
    },
    "delete_address_checkout": {
      "op": "customer-profile/delete-address-checkout",
      "method": "DELETE",
      "path": "/customers/{customerId}/address",
      "summary": "Delete Address (Checkout)",
      "destructive": true
    },
    "delete_profile_address": {
      "op": "customer-profile/delete-profile-address",
      "method": "POST",
      "path": "/customer-profile/delete-address",
      "summary": "Delete Profile Address",
      "destructive": true
    },
    "get_customer_details": {
      "op": "customer-profile/get-customer-details",
      "method": "GET",
      "path": "/customers/{customerId}",
      "summary": "Get Customer Details",
      "destructive": false
    },
    "get_customer_orders": {
      "op": "customer-profile/get-customer-orders",
      "method": "GET",
      "path": "/customers/{customerId}/orders",
      "summary": "Get Customer Orders",
      "destructive": false
    },
    "get_order_details": {
      "op": "customer-profile/get-order-details",
      "method": "GET",
      "path": "/customer-profile/orders/{order_uuid}",
      "summary": "Get Order Details",
      "destructive": false
    },
    "get_profile_details": {
      "op": "customer-profile/get-profile-details",
      "method": "GET",
      "path": "/customer-profile/profile",
      "summary": "Get Profile Details",
      "destructive": false
    },
    "get_transaction_billing_address": {
      "op": "customer-profile/get-transaction-billing-address",
      "method": "GET",
      "path": "/customer-profile/orders/{transaction_uuid}/billing-address",
      "summary": "Get Transaction Billing Address",
      "destructive": false
    },
    "get_upgrade_paths": {
      "op": "customer-profile/get-upgrade-paths",
      "method": "GET",
      "path": "/customer-profile/orders/{order_uuid}/upgrade-paths",
      "summary": "Get Upgrade Paths",
      "destructive": false
    },
    "list_downloads": {
      "op": "customer-profile/list-downloads",
      "method": "GET",
      "path": "/customer-profile/downloads",
      "summary": "List Downloads",
      "destructive": false
    },
    "list_orders": {
      "op": "customer-profile/list-orders",
      "method": "GET",
      "path": "/customer-profile/orders",
      "summary": "List Orders",
      "destructive": false
    },
    "make_profile_address_primary": {
      "op": "customer-profile/make-profile-address-primary",
      "method": "POST",
      "path": "/customer-profile/make-primary-address",
      "summary": "Make Profile Address Primary",
      "destructive": false
    },
    "save_transaction_billing_address": {
      "op": "customer-profile/save-transaction-billing-address",
      "method": "PUT",
      "path": "/customer-profile/orders/{transaction_uuid}/billing-address",
      "summary": "Save Transaction Billing Address",
      "destructive": false
    },
    "select_address_for_checkout": {
      "op": "customer-profile/select-address-for-checkout",
      "method": "GET",
      "path": "/customers/{customerAddressId}/update-address-select",
      "summary": "Select Address for Checkout",
      "destructive": false
    },
    "set_address_as_primary": {
      "op": "customer-profile/set-address-as-primary",
      "method": "POST",
      "path": "/customers/{customerId}/address/make-primary",
      "summary": "Set Address as Primary",
      "destructive": false
    },
    "update_address_checkout": {
      "op": "customer-profile/update-address-checkout",
      "method": "PUT",
      "path": "/customers/{customerId}/address",
      "summary": "Update Address (Checkout)",
      "destructive": false
    },
    "update_customer_details": {
      "op": "customer-profile/update-customer-details",
      "method": "PUT",
      "path": "/customers/{customerId}",
      "summary": "Update Customer Details",
      "destructive": false
    },
    "update_profile_address": {
      "op": "customer-profile/update-profile-address",
      "method": "POST",
      "path": "/customer-profile/edit-address",
      "summary": "Update Profile Address",
      "destructive": false
    },
    "update_profile_details": {
      "op": "customer-profile/update-profile-details",
      "method": "POST",
      "path": "/customer-profile/update",
      "summary": "Update Profile Details",
      "destructive": false
    }
  },
  "cart_licensing": {
    "activate_plugin_license": {
      "op": "licensing/activate-plugin-license",
      "method": "POST",
      "path": "/settings/license/",
      "summary": "Activate Plugin License",
      "destructive": false
    },
    "activate_site_admin": {
      "op": "licensing/activate-site-admin",
      "method": "POST",
      "path": "/licensing/licenses/{id}/activate_site",
      "summary": "Activate Site (Admin)",
      "destructive": false
    },
    "deactivate_plugin_license": {
      "op": "licensing/deactivate-plugin-license",
      "method": "DELETE",
      "path": "/settings/license/",
      "summary": "Deactivate Plugin License",
      "destructive": true
    },
    "deactivate_site_admin": {
      "op": "licensing/deactivate-site-admin",
      "method": "POST",
      "path": "/licensing/licenses/{id}/deactivate_site",
      "summary": "Deactivate Site (Admin)",
      "destructive": true
    },
    "deactivate_site_customer": {
      "op": "licensing/deactivate-site-customer",
      "method": "POST",
      "path": "/customer-profile/licenses/{license_key}/deactivate_site",
      "summary": "Deactivate Site (Customer)",
      "destructive": true
    },
    "delete_license": {
      "op": "licensing/delete-license",
      "method": "DELETE",
      "path": "/licensing/licenses/{id}/delete",
      "summary": "Delete License",
      "destructive": true
    },
    "extend_license_validity": {
      "op": "licensing/extend-license-validity",
      "method": "POST",
      "path": "/licensing/licenses/{id}/extend-validity",
      "summary": "Extend License Validity",
      "destructive": false
    },
    "get_customer_license_details": {
      "op": "licensing/get-customer-license-details",
      "method": "GET",
      "path": "/customer-profile/licenses/{license_key}",
      "summary": "Get Customer License Details",
      "destructive": false
    },
    "get_customer_licenses_admin": {
      "op": "licensing/get-customer-licenses-admin",
      "method": "GET",
      "path": "/licensing/licenses/customer/{id}",
      "summary": "Get Customer Licenses (Admin)",
      "destructive": false
    },
    "get_license_activations": {
      "op": "licensing/get-license-activations",
      "method": "GET",
      "path": "/customer-profile/licenses/{license_key}/activations",
      "summary": "Get License Activations",
      "destructive": false
    },
    "get_license_chart": {
      "op": "licensing/get-license-chart",
      "method": "GET",
      "path": "/reports/license-chart",
      "summary": "Get License Line Chart",
      "destructive": false
    },
    "get_license_details": {
      "op": "licensing/get-license-details",
      "method": "GET",
      "path": "/licensing/licenses/{id}",
      "summary": "Get License Details",
      "destructive": false
    },
    "get_license_pie_chart": {
      "op": "licensing/get-license-pie-chart",
      "method": "GET",
      "path": "/reports/license-pie-chart",
      "summary": "Get License Pie Chart",
      "destructive": false
    },
    "get_license_summary": {
      "op": "licensing/get-license-summary",
      "method": "GET",
      "path": "/reports/license-summary",
      "summary": "Get License Summary",
      "destructive": false
    },
    "get_plugin_license_status": {
      "op": "licensing/get-plugin-license-status",
      "method": "GET",
      "path": "/settings/license/",
      "summary": "Get Plugin License Status",
      "destructive": false
    },
    "get_product_license_settings": {
      "op": "licensing/get-product-license-settings",
      "method": "GET",
      "path": "/licensing/products/{id}/settings",
      "summary": "Get Product License Settings",
      "destructive": false
    },
    "list_customer_licenses": {
      "op": "licensing/list-customer-licenses",
      "method": "GET",
      "path": "/customer-profile/licenses/",
      "summary": "List Customer Licenses",
      "destructive": false
    },
    "list_licenses": {
      "op": "licensing/list-licenses",
      "method": "GET",
      "path": "/licensing/licenses",
      "summary": "List Licenses",
      "destructive": false
    },
    "public_activate_license": {
      "op": "licensing/public-activate-license",
      "method": "POST",
      "path": "/?fluent-cart=activate_license",
      "summary": "Activate License",
      "destructive": false,
      "siteRoot": true
    },
    "public_check_license": {
      "op": "licensing/public-check-license",
      "method": "GET",
      "path": "/?fluent-cart=check_license",
      "summary": "Check License",
      "destructive": false,
      "siteRoot": true
    },
    "public_deactivate_license": {
      "op": "licensing/public-deactivate-license",
      "method": "POST",
      "path": "/?fluent-cart=deactivate_license",
      "summary": "Deactivate License",
      "destructive": true,
      "siteRoot": true
    },
    "public_download_license_package": {
      "op": "licensing/public-download-license-package",
      "method": "GET",
      "path": "/?fluent-cart=download_license_package",
      "summary": "Download License Package",
      "destructive": false,
      "siteRoot": true
    },
    "public_get_license_version": {
      "op": "licensing/public-get-license-version",
      "method": "GET",
      "path": "/?fluent-cart=get_license_version",
      "summary": "Get License Version",
      "destructive": false,
      "siteRoot": true
    },
    "regenerate_license_key": {
      "op": "licensing/regenerate-license-key",
      "method": "POST",
      "path": "/licensing/licenses/{id}/regenerate-key",
      "summary": "Regenerate License Key",
      "destructive": true
    },
    "save_product_license_settings": {
      "op": "licensing/save-product-license-settings",
      "method": "POST",
      "path": "/licensing/products/{id}/settings",
      "summary": "Save Product License Settings",
      "destructive": false
    },
    "update_license_activation_limit": {
      "op": "licensing/update-license-activation-limit",
      "method": "POST",
      "path": "/licensing/licenses/{id}/update_limit",
      "summary": "Update License Activation Limit",
      "destructive": false
    },
    "update_license_status": {
      "op": "licensing/update-license-status",
      "method": "POST",
      "path": "/licensing/licenses/{id}/update_status",
      "summary": "Update License Status",
      "destructive": false
    }
  },
  "cart_roles": {
    "assign_role": {
      "op": "roles-permissions/assign-role",
      "method": "POST",
      "path": "/roles",
      "summary": "Assign Role",
      "destructive": false
    },
    "delete_role_assignment": {
      "op": "roles-permissions/delete-role-assignment",
      "method": "DELETE",
      "path": "/roles/{key}",
      "summary": "Delete Role Assignment",
      "destructive": true
    },
    "get_permissions": {
      "op": "roles-permissions/get-permissions",
      "method": "GET",
      "path": "/settings/permissions",
      "summary": "Get Permissions",
      "destructive": false
    },
    "get_role": {
      "op": "roles-permissions/get-role",
      "method": "GET",
      "path": "/roles/{key}",
      "summary": "Get Role",
      "destructive": false
    },
    "list_managers": {
      "op": "roles-permissions/list-managers",
      "method": "GET",
      "path": "/roles/managers",
      "summary": "List Managers",
      "destructive": false
    },
    "list_roles": {
      "op": "roles-permissions/list-roles",
      "method": "GET",
      "path": "/roles",
      "summary": "List Roles",
      "destructive": false
    },
    "save_permissions": {
      "op": "roles-permissions/save-permissions",
      "method": "POST",
      "path": "/settings/permissions",
      "summary": "Save Permissions",
      "destructive": false
    },
    "search_users": {
      "op": "roles-permissions/search-users",
      "method": "GET",
      "path": "/roles/user-list",
      "summary": "Search Users",
      "destructive": false
    },
    "update_role": {
      "op": "roles-permissions/update-role",
      "method": "POST",
      "path": "/roles/{key}",
      "summary": "Update Role",
      "destructive": false
    }
  },
  "cart_order_bumps": {
    "create_order_bump": {
      "op": "order-bumps/create-order-bump",
      "method": "POST",
      "path": "/order_bump",
      "summary": "Create Order Bump",
      "destructive": false
    },
    "delete_order_bump": {
      "op": "order-bumps/delete-order-bump",
      "method": "DELETE",
      "path": "/order_bump/{id}",
      "summary": "Delete Order Bump",
      "destructive": true
    },
    "get_order_bump": {
      "op": "order-bumps/get-order-bump",
      "method": "GET",
      "path": "/order_bump/{id}",
      "summary": "Get Order Bump",
      "destructive": false
    },
    "list_order_bumps": {
      "op": "order-bumps/list-order-bumps",
      "method": "GET",
      "path": "/order_bump",
      "summary": "List Order Bumps",
      "destructive": false
    },
    "update_order_bump": {
      "op": "order-bumps/update-order-bump",
      "method": "PUT",
      "path": "/order_bump/{id}",
      "summary": "Update Order Bump",
      "destructive": false
    }
  }
};

export const TOOL_META: Record<string, { description: string; note?: string; idempotent?: boolean }> = {
  "cart_orders": {
    "description": "Look up, create, update, refund, and manage store orders, including their statuses, transactions, addresses, and disputes.",
    "note": "Order totals and amounts are integers in CENTS (e.g. 1200 = $12.00)."
  },
  "cart_products": {
    "description": "Look up, create, update, delete, and bulk-edit store products, including search, duplication, taxonomy terms, and shipping/tax classes."
  },
  "cart_product_variants": {
    "description": "Manage product variations: pricing, inventory and stock, bundles, upgrade paths, media, and variant search.",
    "note": "PRICE UNITS: despite the API docs' blanket 'cents' claim, variation create/update prices (item_price, compare_price) are plain DOLLARS — sending cents stores a 100× price; read back after writing to confirm. Stock updates expect a variants wrapper with total_stock/available (422 errors name the missing fields)."
  },
  "cart_product_assets": {
    "description": "Manage products' downloadable files and per-product integration feeds."
  },
  "cart_customers": {
    "description": "Look up, create, update, and manage store customers, their addresses, purchase stats, and linked WordPress users."
  },
  "cart_coupons": {
    "description": "Manage discount coupons: create, update, delete, apply to or remove from orders, and check product eligibility."
  },
  "cart_subscriptions": {
    "description": "View and manage recurring subscriptions: cancel, re-sync from the payment gateway, switch payment methods, and handle early payments."
  },
  "cart_tax": {
    "description": "Manage tax classes, tax rates, per-country configuration, EU VAT/OSS overrides, and order tax records."
  },
  "cart_shipping": {
    "description": "Manage shipping zones, shipping methods, and shipping classes."
  },
  "cart_settings": {
    "description": "Read or update store settings: general store options, modules and addons, permissions, payment methods, storage drivers, and checkout fields."
  },
  "cart_email_notifications": {
    "description": "Manage the store's transactional email templates, global email settings, reminders, and previews."
  },
  "cart_reports": {
    "description": "Read-only store analytics: revenue, orders, products, customers, subscriptions, refunds, licenses, and dashboard summaries."
  },
  "cart_integrations": {
    "description": "Manage global integration feeds and provider settings, and install or activate integration addons."
  },
  "cart_files": {
    "description": "List, upload, and delete files in the store's configured storage drivers."
  },
  "cart_labels_attributes": {
    "description": "Manage store labels and product attribute groups and their terms."
  },
  "cart_utilities": {
    "description": "Store utilities: dashboard stats and onboarding, activity log, order notes, print templates, country data, filter options, and retention snapshots."
  },
  "cart_storefront": {
    "description": "Read-only public storefront data: published products, rendered product listings, and product search — no authentication required."
  },
  "cart_checkout": {
    "description": "Checkout-session operations: place an order, fetch payment and shipping info for the cart, and log a customer in.",
    "note": "These endpoints expect a customer browser session (cookie + nonce); most will be rejected under Application Password auth — see docs/api-reference/auth.md."
  },
  "cart_customer_portal": {
    "description": "Customer-portal operations on the logged-in customer's own profile, orders, addresses, subscriptions, and downloads.",
    "note": "These endpoints expect a customer browser session (cookie + nonce); most will be rejected under Application Password auth — see docs/api-reference/auth.md."
  },
  "cart_licensing": {
    "description": "Manage software licenses: view, extend, regenerate keys, change limits, activate or deactivate sites, plus the public license verification endpoints (FluentCart Pro)."
  },
  "cart_roles": {
    "description": "Manage FluentCart shop roles, permissions, and user assignments (FluentCart Pro)."
  },
  "cart_order_bumps": {
    "description": "Manage checkout order bumps: list, create, update, and delete (FluentCart Pro)."
  }
};
