/* AUTO-GENERATED by scripts/gen-endpoint-maps.mjs from docs/api-reference/fluentcrm/endpoints.json — do not edit by hand. */
import type { EndpointDef } from '../../core/types.js';

export const TOOL_ENDPOINTS: Record<string, Record<string, EndpointDef>> = {
  "crm_contacts": {
    "bulk_action_contacts": {
      "op": "contacts/bulk-action-contacts",
      "method": "POST",
      "path": "/subscribers/do-bulk-action",
      "summary": "Bulk Action Contacts",
      "destructive": true
    },
    "bulk_add_update_contacts": {
      "op": "contacts/bulk-add-update-contacts",
      "method": "POST",
      "path": "/subscribers/bulk-add-update",
      "summary": "Bulk Add/Update Contacts",
      "destructive": false
    },
    "create_contact": {
      "op": "contacts/create-contact",
      "method": "POST",
      "path": "/subscribers",
      "summary": "Create Contact",
      "destructive": false
    },
    "create_contact_note": {
      "op": "contacts/create-contact-note",
      "method": "POST",
      "path": "/subscribers/{id}/notes",
      "summary": "Create Contact Note",
      "destructive": false
    },
    "delete_contact": {
      "op": "contacts/delete-contact",
      "method": "DELETE",
      "path": "/subscribers/{id}",
      "summary": "Delete Contact",
      "destructive": true
    },
    "delete_contact_emails": {
      "op": "contacts/delete-contact-emails",
      "method": "DELETE",
      "path": "/subscribers/{id}/emails",
      "summary": "Delete Contact Emails",
      "destructive": true
    },
    "delete_contact_note": {
      "op": "contacts/delete-contact-note",
      "method": "DELETE",
      "path": "/subscribers/{id}/notes/{note_id}",
      "summary": "Delete Contact Note",
      "destructive": true
    },
    "delete_contacts": {
      "op": "contacts/delete-contacts",
      "method": "DELETE",
      "path": "/subscribers",
      "summary": "Delete Contacts",
      "destructive": true
    },
    "get_contact": {
      "op": "contacts/get-contact",
      "method": "GET",
      "path": "/subscribers/{id}",
      "summary": "Get Contact",
      "destructive": false
    },
    "get_contact_dynamic_item_view": {
      "op": "contacts/get-contact-dynamic-item-view",
      "method": "GET",
      "path": "/subscribers/{id}/dynamic-item-view",
      "summary": "Get Contact Dynamic Item View",
      "destructive": false
    },
    "get_contact_emails": {
      "op": "contacts/get-contact-emails",
      "method": "GET",
      "path": "/subscribers/{id}/emails",
      "summary": "Get Contact Emails",
      "destructive": false
    },
    "get_contact_external_view": {
      "op": "contacts/get-contact-external-view",
      "method": "GET",
      "path": "/subscribers/{id}/external_view",
      "summary": "Get Contact External View",
      "destructive": false
    },
    "get_contact_form_submissions": {
      "op": "contacts/get-contact-form-submissions",
      "method": "GET",
      "path": "/subscribers/{id}/form-submissions",
      "summary": "Get Contact Form Submissions",
      "destructive": false
    },
    "get_contact_info_widgets": {
      "op": "contacts/get-contact-info-widgets",
      "method": "GET",
      "path": "/subscribers/{id}/info-widgets",
      "summary": "Get Contact Info Widgets",
      "destructive": false
    },
    "get_contact_notes": {
      "op": "contacts/get-contact-notes",
      "method": "GET",
      "path": "/subscribers/{id}/notes",
      "summary": "Get Contact Notes",
      "destructive": false
    },
    "get_contact_prev_next_ids": {
      "op": "contacts/get-contact-prev-next-ids",
      "method": "GET",
      "path": "/subscribers/prev-next-ids",
      "summary": "Get Contact Prev/Next IDs",
      "destructive": false
    },
    "get_contact_purchase_history": {
      "op": "contacts/get-contact-purchase-history",
      "method": "GET",
      "path": "/subscribers/{id}/purchase-history",
      "summary": "Get Contact Purchase History",
      "destructive": false
    },
    "get_contact_support_tickets": {
      "op": "contacts/get-contact-support-tickets",
      "method": "GET",
      "path": "/subscribers/{id}/support-tickets",
      "summary": "Get Contact Support Tickets",
      "destructive": false
    },
    "get_contact_template_mock": {
      "op": "contacts/get-contact-template-mock",
      "method": "GET",
      "path": "/subscribers/{id}/emails/template-mock",
      "summary": "Get Contact Template Mock",
      "destructive": false
    },
    "get_contact_tracking_events": {
      "op": "contacts/get-contact-tracking-events",
      "method": "GET",
      "path": "/subscribers/{id}/tracking-events",
      "summary": "Get Contact Tracking Events",
      "destructive": false
    },
    "get_contact_url_metrics": {
      "op": "contacts/get-contact-url-metrics",
      "method": "GET",
      "path": "/subscribers/{id}/url-metrics",
      "summary": "Get Contact URL Metrics",
      "destructive": false
    },
    "list_contacts": {
      "op": "contacts/list-contacts",
      "method": "GET",
      "path": "/subscribers",
      "summary": "List Contacts",
      "destructive": false
    },
    "save_contact_external_view": {
      "op": "contacts/save-contact-external-view",
      "method": "POST",
      "path": "/subscribers/{id}/external_view",
      "summary": "Save Contact External View",
      "destructive": false
    },
    "search_contacts": {
      "op": "contacts/search-contacts",
      "method": "GET",
      "path": "/subscribers/search-contacts",
      "summary": "Search Contacts",
      "destructive": false
    },
    "send_contact_custom_email": {
      "op": "contacts/send-contact-custom-email",
      "method": "POST",
      "path": "/subscribers/{id}/emails/send",
      "summary": "Send Contact Custom Email",
      "destructive": false
    },
    "send_contact_double_optin": {
      "op": "contacts/send-contact-double-optin",
      "method": "POST",
      "path": "/subscribers/{id}/send-double-optin",
      "summary": "Send Contact Double Opt-in",
      "destructive": false
    },
    "sync_contact_segments": {
      "op": "contacts/sync-contact-segments",
      "method": "POST",
      "path": "/subscribers/sync-segments",
      "summary": "Sync Contact Segments",
      "destructive": false
    },
    "track_contact_event": {
      "op": "contacts/track-contact-event",
      "method": "POST",
      "path": "/subscribers/track-event",
      "summary": "Track Contact Event",
      "destructive": false
    },
    "update_contact": {
      "op": "contacts/update-contact",
      "method": "PUT",
      "path": "/subscribers/{id}",
      "summary": "Update Contact",
      "destructive": false
    },
    "update_contact_note": {
      "op": "contacts/update-contact-note",
      "method": "PUT",
      "path": "/subscribers/{id}/notes/{note_id}",
      "summary": "Update Contact Note",
      "destructive": false
    },
    "update_contacts_property": {
      "op": "contacts/update-contacts-property",
      "method": "PUT",
      "path": "/subscribers/subscribers-property",
      "summary": "Update Contacts Property",
      "destructive": false
    }
  },
  "crm_lists": {
    "bulk_action_lists": {
      "op": "lists/bulk-action-lists",
      "method": "POST",
      "path": "/lists/do-bulk-action",
      "summary": "Bulk Action Lists",
      "destructive": true
    },
    "bulk_create_lists": {
      "op": "lists/bulk-create-lists",
      "method": "POST",
      "path": "/lists/bulk",
      "summary": "Bulk Create Lists",
      "destructive": false
    },
    "create_list": {
      "op": "lists/create-list",
      "method": "POST",
      "path": "/lists",
      "summary": "Create List",
      "destructive": false
    },
    "delete_list": {
      "op": "lists/delete-list",
      "method": "DELETE",
      "path": "/lists/{id}",
      "summary": "Delete List",
      "destructive": true
    },
    "get_list": {
      "op": "lists/get-list",
      "method": "GET",
      "path": "/lists/{id}",
      "summary": "Get List",
      "destructive": false
    },
    "list_lists": {
      "op": "lists/list-lists",
      "method": "GET",
      "path": "/lists",
      "summary": "List Lists",
      "destructive": false
    },
    "update_list": {
      "op": "lists/update-list",
      "method": "PUT",
      "path": "/lists/{id}",
      "summary": "Update List",
      "destructive": false
    }
  },
  "crm_tags": {
    "bulk_action_tags": {
      "op": "tags/bulk-action-tags",
      "method": "POST",
      "path": "/tags/do-bulk-action",
      "summary": "Bulk Action Tags",
      "destructive": true
    },
    "bulk_create_tags": {
      "op": "tags/bulk-create-tags",
      "method": "POST",
      "path": "/tags/bulk",
      "summary": "Bulk Create Tags",
      "destructive": false
    },
    "create_tag": {
      "op": "tags/create-tag",
      "method": "POST",
      "path": "/tags",
      "summary": "Create Tag",
      "destructive": false
    },
    "delete_tag": {
      "op": "tags/delete-tag",
      "method": "DELETE",
      "path": "/tags/{id}",
      "summary": "Delete Tag",
      "destructive": true
    },
    "get_tag": {
      "op": "tags/get-tag",
      "method": "GET",
      "path": "/tags/{id}",
      "summary": "Get Tag",
      "destructive": false
    },
    "list_tags": {
      "op": "tags/list-tags",
      "method": "GET",
      "path": "/tags",
      "summary": "List Tags",
      "destructive": false
    },
    "update_tag": {
      "op": "tags/update-tag",
      "method": "PUT",
      "path": "/tags/{id}",
      "summary": "Update Tag",
      "destructive": false
    }
  },
  "crm_segments": {
    "create_dynamic_segment": {
      "op": "dynamic-segments/create-dynamic-segment",
      "method": "POST",
      "path": "/dynamic-segments",
      "summary": "Create Dynamic Segment",
      "destructive": false
    },
    "delete_dynamic_segment": {
      "op": "dynamic-segments/delete-dynamic-segment",
      "method": "DELETE",
      "path": "/dynamic-segments/{id}",
      "summary": "Delete Dynamic Segment",
      "destructive": true
    },
    "duplicate_dynamic_segment": {
      "op": "dynamic-segments/duplicate-dynamic-segment",
      "method": "POST",
      "path": "/dynamic-segments/duplicate/{id}",
      "summary": "Duplicate Dynamic Segment",
      "destructive": false
    },
    "estimate_dynamic_segment_contacts": {
      "op": "dynamic-segments/estimate-dynamic-segment-contacts",
      "method": "POST",
      "path": "/dynamic-segments/estimated-contacts",
      "summary": "Estimate Dynamic Segment Contacts",
      "destructive": false
    },
    "get_dynamic_segment_custom_fields": {
      "op": "dynamic-segments/get-dynamic-segment-custom-fields",
      "method": "GET",
      "path": "/dynamic-segments/custom-fields",
      "summary": "Get Dynamic Segment Custom Fields",
      "destructive": false
    },
    "get_dynamic_segment_stats": {
      "op": "dynamic-segments/get-dynamic-segment-stats",
      "method": "GET",
      "path": "/dynamic-segments/stats",
      "summary": "Get Dynamic Segment Stats",
      "destructive": false
    },
    "get_dynamic_segment_subscribers": {
      "op": "dynamic-segments/get-dynamic-segment-subscribers",
      "method": "GET",
      "path": "/dynamic-segments/{slug}/subscribers/{id}",
      "summary": "Get Dynamic Segment Subscribers",
      "destructive": false
    },
    "list_dynamic_segments": {
      "op": "dynamic-segments/list-dynamic-segments",
      "method": "GET",
      "path": "/dynamic-segments",
      "summary": "List Dynamic Segments",
      "destructive": false
    },
    "update_dynamic_segment": {
      "op": "dynamic-segments/update-dynamic-segment",
      "method": "PUT",
      "path": "/dynamic-segments/{id}",
      "summary": "Update Dynamic Segment",
      "destructive": false
    }
  },
  "crm_custom_fields": {
    "get_contact_custom_fields": {
      "op": "custom-fields/get-contact-custom-fields",
      "method": "GET",
      "path": "/custom-fields/contacts",
      "summary": "Get Contact Custom Fields",
      "destructive": false
    },
    "save_contact_custom_fields": {
      "op": "custom-fields/save-contact-custom-fields",
      "method": "PUT",
      "path": "/custom-fields/contacts",
      "summary": "Save Contact Custom Fields",
      "destructive": false
    },
    "update_custom_field_group_name": {
      "op": "custom-fields/update-custom-field-group-name",
      "method": "PUT",
      "path": "/custom-fields/contacts/update_group_name",
      "summary": "Update Custom Field Group Name",
      "destructive": false
    }
  },
  "crm_labels": {
    "create_label": {
      "op": "labels/create-label",
      "method": "POST",
      "path": "/labels",
      "summary": "Create Label",
      "destructive": false
    },
    "delete_label": {
      "op": "labels/delete-label",
      "method": "DELETE",
      "path": "/labels/{id}",
      "summary": "Delete Label",
      "destructive": true
    },
    "list_labels": {
      "op": "labels/list-labels",
      "method": "GET",
      "path": "/labels",
      "summary": "List Labels",
      "destructive": false
    },
    "update_label": {
      "op": "labels/update-label",
      "method": "PUT",
      "path": "/labels/{id}",
      "summary": "Update Label",
      "destructive": false
    }
  },
  "crm_companies": {
    "attach_company_subscribers": {
      "op": "companies/attach-company-subscribers",
      "method": "POST",
      "path": "/companies/attach-subscribers",
      "summary": "Attach Subscribers to Companies",
      "destructive": false
    },
    "bulk_action_companies": {
      "op": "companies/bulk-action-companies",
      "method": "POST",
      "path": "/companies/do-bulk-action",
      "summary": "Bulk Action on Companies",
      "destructive": true
    },
    "create_company": {
      "op": "companies/create-company",
      "method": "POST",
      "path": "/companies",
      "summary": "Create Company",
      "destructive": false
    },
    "create_company_note": {
      "op": "companies/create-company-note",
      "method": "POST",
      "path": "/companies/{id}/notes",
      "summary": "Create Company Note",
      "destructive": false
    },
    "delete_company": {
      "op": "companies/delete-company",
      "method": "DELETE",
      "path": "/companies/{id}",
      "summary": "Delete Company",
      "destructive": true
    },
    "delete_company_note": {
      "op": "companies/delete-company-note",
      "method": "DELETE",
      "path": "/companies/{id}/notes/{note_id}",
      "summary": "Delete Company Note",
      "destructive": true
    },
    "detach_company_subscribers": {
      "op": "companies/detach-company-subscribers",
      "method": "POST",
      "path": "/companies/detach-subscribers",
      "summary": "Detach Subscribers from Companies",
      "destructive": true
    },
    "get_company": {
      "op": "companies/get-company",
      "method": "GET",
      "path": "/companies/{id}",
      "summary": "Get Company",
      "destructive": false
    },
    "get_company_custom_fields": {
      "op": "companies/get-company-custom-fields",
      "method": "GET",
      "path": "/companies/custom-fields",
      "summary": "Get Company Custom Fields",
      "destructive": false
    },
    "get_company_external_view": {
      "op": "companies/get-company-external-view",
      "method": "GET",
      "path": "/companies/{id}/custom_tab_view",
      "summary": "Get Company External View",
      "destructive": false
    },
    "get_company_notes": {
      "op": "companies/get-company-notes",
      "method": "GET",
      "path": "/companies/{id}/notes",
      "summary": "Get Company Notes",
      "destructive": false
    },
    "import_companies_csv": {
      "op": "companies/import-companies-csv",
      "method": "POST",
      "path": "/companies/csv-import",
      "summary": "Import Companies from CSV",
      "destructive": false
    },
    "list_companies": {
      "op": "companies/list-companies",
      "method": "GET",
      "path": "/companies",
      "summary": "List Companies",
      "destructive": false
    },
    "save_company_custom_fields": {
      "op": "companies/save-company-custom-fields",
      "method": "PUT",
      "path": "/companies/custom-fields",
      "summary": "Save Company Custom Fields",
      "destructive": false
    },
    "search_companies": {
      "op": "companies/search-companies",
      "method": "GET",
      "path": "/companies/search",
      "summary": "Search Companies",
      "destructive": false
    },
    "search_unattached_contacts": {
      "op": "companies/search-unattached-contacts",
      "method": "GET",
      "path": "/companies/search-unattached-contacts",
      "summary": "Search Unattached Contacts",
      "destructive": false
    },
    "update_companies_property": {
      "op": "companies/update-companies-property",
      "method": "PUT",
      "path": "/companies/companies-property",
      "summary": "Update Companies Property",
      "destructive": false
    },
    "update_company": {
      "op": "companies/update-company",
      "method": "PUT",
      "path": "/companies/{id}",
      "summary": "Update Company",
      "destructive": false
    },
    "update_company_note": {
      "op": "companies/update-company-note",
      "method": "PUT",
      "path": "/companies/{id}/notes/{note_id}",
      "summary": "Update Company Note",
      "destructive": false
    }
  },
  "crm_campaigns": {
    "bulk_action_campaigns": {
      "op": "campaigns/bulk-action-campaigns",
      "method": "POST",
      "path": "/campaigns/do-bulk-action",
      "summary": "Bulk Action Campaigns",
      "destructive": true
    },
    "create_campaign": {
      "op": "campaigns/create-campaign",
      "method": "POST",
      "path": "/campaigns",
      "summary": "Create Campaign",
      "destructive": false
    },
    "delete_campaign": {
      "op": "campaigns/delete-campaign",
      "method": "DELETE",
      "path": "/campaigns/{id}",
      "summary": "Delete Campaign",
      "destructive": true
    },
    "delete_campaign_emails": {
      "op": "campaigns/delete-campaign-emails",
      "method": "DELETE",
      "path": "/campaigns/{id}/emails",
      "summary": "Delete Campaign Emails",
      "destructive": true
    },
    "draft_campaign_recipients": {
      "op": "campaigns/draft-campaign-recipients",
      "method": "POST",
      "path": "/campaigns/{id}/draft-recipients",
      "summary": "Draft Campaign Recipients",
      "destructive": false
    },
    "duplicate_campaign": {
      "op": "campaigns/duplicate-campaign",
      "method": "POST",
      "path": "/campaigns/{id}/duplicate",
      "summary": "Duplicate Campaign",
      "destructive": false
    },
    "estimate_campaign_contacts": {
      "op": "campaigns/estimate-campaign-contacts",
      "method": "POST",
      "path": "/campaigns/estimated-contacts",
      "summary": "Estimate Campaign Contacts",
      "destructive": false
    },
    "get_campaign": {
      "op": "campaigns/get-campaign",
      "method": "GET",
      "path": "/campaigns/{id}",
      "summary": "Get Campaign",
      "destructive": false
    },
    "get_campaign_contacts_by_segment": {
      "op": "campaigns/get-campaign-contacts-by-segment",
      "method": "GET",
      "path": "/campaigns/{id}/contacts-by-segment",
      "summary": "Get Campaign Contacts by Segment",
      "destructive": false
    },
    "get_campaign_emails": {
      "op": "campaigns/get-campaign-emails",
      "method": "GET",
      "path": "/campaigns/{id}/emails",
      "summary": "Get Campaign Emails",
      "destructive": false
    },
    "get_campaign_link_report": {
      "op": "campaigns/get-campaign-link-report",
      "method": "GET",
      "path": "/campaigns/{id}/link-report",
      "summary": "Get Campaign Link Report",
      "destructive": false
    },
    "get_campaign_overview_stats": {
      "op": "campaigns/get-campaign-overview-stats",
      "method": "GET",
      "path": "/campaigns/{id}/overview_stats",
      "summary": "Get Campaign Overview Stats",
      "destructive": false
    },
    "get_campaign_processing_stat": {
      "op": "campaigns/get-campaign-processing-stat",
      "method": "GET",
      "path": "/campaigns/{id}/processing-stat",
      "summary": "Get Campaign Processing Stat",
      "destructive": false
    },
    "get_campaign_recipients_count": {
      "op": "campaigns/get-campaign-recipients-count",
      "method": "GET",
      "path": "/campaigns/{id}/estimated-recipients-count",
      "summary": "Get Campaign Recipients Count",
      "destructive": false
    },
    "get_campaign_revenues": {
      "op": "campaigns/get-campaign-revenues",
      "method": "GET",
      "path": "/campaigns/{id}/revenues",
      "summary": "Get Campaign Revenues",
      "destructive": false
    },
    "get_campaign_share_url": {
      "op": "campaigns/get-campaign-share-url",
      "method": "GET",
      "path": "/campaigns/{id}/share-url",
      "summary": "Get Campaign Share URL",
      "destructive": false
    },
    "get_campaign_status": {
      "op": "campaigns/get-campaign-status",
      "method": "GET",
      "path": "/campaigns/{id}/status",
      "summary": "Get Campaign Status",
      "destructive": false
    },
    "get_campaign_unsubscribers": {
      "op": "campaigns/get-campaign-unsubscribers",
      "method": "GET",
      "path": "/campaigns/{id}/unsubscribers",
      "summary": "Get Campaign Unsubscribers",
      "destructive": false
    },
    "list_campaigns": {
      "op": "campaigns/list-campaigns",
      "method": "GET",
      "path": "/campaigns",
      "summary": "List Campaigns",
      "destructive": false
    },
    "pause_campaign": {
      "op": "campaigns/pause-campaign",
      "method": "POST",
      "path": "/campaigns/{id}/pause",
      "summary": "Pause Campaign",
      "destructive": false
    },
    "preview_campaign_email": {
      "op": "campaigns/preview-campaign-email",
      "method": "GET",
      "path": "/campaigns/emails/{email_id}/preview",
      "summary": "Preview Campaign Email",
      "destructive": false
    },
    "preview_campaign_email_html": {
      "op": "campaigns/preview-campaign-email-html",
      "method": "POST",
      "path": "/campaigns/email-preview-html",
      "summary": "Preview Campaign Email HTML",
      "destructive": false
    },
    "resume_campaign": {
      "op": "campaigns/resume-campaign",
      "method": "POST",
      "path": "/campaigns/{id}/resume",
      "summary": "Resume Campaign",
      "destructive": true
    },
    "resync_campaign_revenues": {
      "op": "campaigns/resync-campaign-revenues",
      "method": "POST",
      "path": "/campaigns/{id}/revenues/resync",
      "summary": "Resync Campaign Revenues",
      "destructive": false
    },
    "schedule_campaign": {
      "op": "campaigns/schedule-campaign",
      "method": "POST",
      "path": "/campaigns/{id}/schedule",
      "summary": "Schedule Campaign",
      "destructive": true
    },
    "send_campaign_test_email": {
      "op": "campaigns/send-campaign-test-email",
      "method": "POST",
      "path": "/campaigns/send-test-email",
      "summary": "Send Campaign Test Email",
      "destructive": false
    },
    "un_schedule_campaign": {
      "op": "campaigns/un-schedule-campaign",
      "method": "POST",
      "path": "/campaigns/{id}/un-schedule",
      "summary": "Un-Schedule Campaign",
      "destructive": true
    },
    "update_campaign": {
      "op": "campaigns/update-campaign",
      "method": "PUT",
      "path": "/campaigns/{id}",
      "summary": "Update Campaign",
      "destructive": false
    },
    "update_campaign_labels": {
      "op": "campaigns/update-campaign-labels",
      "method": "PUT",
      "path": "/campaigns/{id}/update-labels",
      "summary": "Update Campaign Labels",
      "destructive": false
    },
    "update_campaign_step": {
      "op": "campaigns/update-campaign-step",
      "method": "POST",
      "path": "/campaigns/{id}/step",
      "summary": "Update Campaign Step",
      "destructive": false
    },
    "update_campaign_title": {
      "op": "campaigns/update-campaign-title",
      "method": "PUT",
      "path": "/campaigns/{id}/title",
      "summary": "Update Campaign Title",
      "destructive": false
    },
    "update_single_campaign_simulate": {
      "op": "campaigns/update-single-campaign-simulate",
      "method": "POST",
      "path": "/campaigns/update-single-campaign",
      "summary": "Update Single Campaign (Simulate)",
      "destructive": false
    },
    "do_campaign_tag_actions": {
      "op": "campaigns-pro/do-campaign-tag-actions",
      "method": "POST",
      "path": "/campaigns-pro/{id}/tag-actions",
      "summary": "Campaign Tag Actions",
      "destructive": false
    },
    "get_dynamic_post_taxonomies": {
      "op": "campaigns-pro/get-dynamic-post-taxonomies",
      "method": "GET",
      "path": "/campaigns-pro/posts/taxonomies",
      "summary": "Dynamic Post Taxonomies",
      "destructive": false
    },
    "get_dynamic_posts": {
      "op": "campaigns-pro/get-dynamic-posts",
      "method": "GET",
      "path": "/campaigns-pro/posts",
      "summary": "Dynamic Posts",
      "destructive": false
    },
    "get_dynamic_products": {
      "op": "campaigns-pro/get-dynamic-products",
      "method": "GET",
      "path": "/campaigns-pro/products",
      "summary": "Dynamic Products",
      "destructive": false
    },
    "resend_campaign_emails": {
      "op": "campaigns-pro/resend-campaign-emails",
      "method": "POST",
      "path": "/campaigns-pro/{id}/resend-emails",
      "summary": "Resend Campaign Emails",
      "destructive": true
    },
    "resend_failed_emails": {
      "op": "campaigns-pro/resend-failed-emails",
      "method": "POST",
      "path": "/campaigns-pro/{id}/resend-failed-emails",
      "summary": "Resend Failed Emails",
      "destructive": true
    },
    "resend_unopened_emails": {
      "op": "campaigns-pro/resend-unopened-emails",
      "method": "POST",
      "path": "/campaigns-pro/{id}/resend-unopened-emails",
      "summary": "Resend Unopened Emails",
      "destructive": true
    }
  },
  "crm_recurring_campaigns": {
    "bulk_action_recurring_campaigns": {
      "op": "recurring-campaigns/bulk-action-recurring-campaigns",
      "method": "POST",
      "path": "/recurring-campaigns/do-bulk-action",
      "summary": "Bulk Action Recurring Campaigns",
      "destructive": true
    },
    "change_recurring_campaign_status": {
      "op": "recurring-campaigns/change-recurring-campaign-status",
      "method": "POST",
      "path": "/recurring-campaigns/{campaign_id}/change-status",
      "summary": "Change Recurring Campaign Status",
      "destructive": false
    },
    "create_recurring_campaign": {
      "op": "recurring-campaigns/create-recurring-campaign",
      "method": "POST",
      "path": "/recurring-campaigns",
      "summary": "Create Recurring Campaign",
      "destructive": false
    },
    "delete_bulk_recurring_campaigns": {
      "op": "recurring-campaigns/delete-bulk-recurring-campaigns",
      "method": "POST",
      "path": "/recurring-campaigns/delete-bulk",
      "summary": "Delete Bulk Recurring Campaigns",
      "destructive": true
    },
    "duplicate_recurring_campaign": {
      "op": "recurring-campaigns/duplicate-recurring-campaign",
      "method": "POST",
      "path": "/recurring-campaigns/{campaign_id}/duplicate",
      "summary": "Duplicate Recurring Campaign",
      "destructive": false
    },
    "get_recurring_campaign": {
      "op": "recurring-campaigns/get-recurring-campaign",
      "method": "GET",
      "path": "/recurring-campaigns/{campaign_id}",
      "summary": "Get Recurring Campaign",
      "destructive": false
    },
    "get_recurring_campaign_email": {
      "op": "recurring-campaigns/get-recurring-campaign-email",
      "method": "GET",
      "path": "/recurring-campaigns/{campaign_id}/emails/{email_id}",
      "summary": "Get Recurring Campaign Email",
      "destructive": false
    },
    "get_recurring_campaign_emails": {
      "op": "recurring-campaigns/get-recurring-campaign-emails",
      "method": "GET",
      "path": "/recurring-campaigns/{campaign_id}/emails",
      "summary": "Get Recurring Campaign Emails",
      "destructive": false
    },
    "list_recurring_campaigns": {
      "op": "recurring-campaigns/list-recurring-campaigns",
      "method": "GET",
      "path": "/recurring-campaigns",
      "summary": "List Recurring Campaigns",
      "destructive": false
    },
    "patch_recurring_campaign_email": {
      "op": "recurring-campaigns/patch-recurring-campaign-email",
      "method": "PUT",
      "path": "/recurring-campaigns/{campaign_id}/emails/{email_id}",
      "summary": "Patch Recurring Campaign Email Status",
      "destructive": false
    },
    "update_recurring_campaign_data": {
      "op": "recurring-campaigns/update-recurring-campaign-data",
      "method": "POST",
      "path": "/recurring-campaigns/update-campaign-data",
      "summary": "Update Recurring Campaign Email Data",
      "destructive": false
    },
    "update_recurring_campaign_email": {
      "op": "recurring-campaigns/update-recurring-campaign-email",
      "method": "POST",
      "path": "/recurring-campaigns/{campaign_id}/emails/update-email",
      "summary": "Update Recurring Campaign Email",
      "destructive": false
    },
    "update_recurring_campaign_labels": {
      "op": "recurring-campaigns/update-recurring-campaign-labels",
      "method": "PUT",
      "path": "/recurring-campaigns/{campaign_id}/update-labels",
      "summary": "Update Recurring Campaign Labels",
      "destructive": false
    },
    "update_recurring_campaign_settings": {
      "op": "recurring-campaigns/update-recurring-campaign-settings",
      "method": "POST",
      "path": "/recurring-campaigns/{campaign_id}/update-settings",
      "summary": "Update Recurring Campaign Settings",
      "destructive": false
    }
  },
  "crm_sequences": {
    "add_sequence_subscribers": {
      "op": "sequences/add-sequence-subscribers",
      "method": "POST",
      "path": "/sequences/{id}/subscribers",
      "summary": "Add Sequence Subscribers",
      "destructive": false
    },
    "bulk_action_sequences": {
      "op": "sequences/bulk-action-sequences",
      "method": "POST",
      "path": "/sequences/do-bulk-action",
      "summary": "Bulk Action Sequences",
      "destructive": true
    },
    "create_or_update_sequence_email": {
      "op": "sequences/create-or-update-sequence-email",
      "method": "POST",
      "path": "/sequences/sequence-email-update-create",
      "summary": "Create or Update Sequence Email",
      "destructive": false,
      "requiredBody": [
        "route_method",
        "sequence_id",
        "email"
      ],
      "bodyNote": "Body shape: {\"route_method\": \"create\"|\"update\", \"sequence_id\": <sequence id>, \"mail_id\": <sequence email id — update only>, \"email\": {...}} — the \"email\" object uses the same nested shape as crm_sequences_create_email (including its absolute-from-enrollment delay semantics); without route_method the endpoint returns 422 \"Invalid route_method\"."
    },
    "create_sequence": {
      "op": "sequences/create-sequence",
      "method": "POST",
      "path": "/sequences",
      "summary": "Create Sequence",
      "destructive": false
    },
    "create_sequence_email": {
      "op": "sequences/create-sequence-email",
      "method": "POST",
      "path": "/sequences/{id}/email",
      "summary": "Create Sequence Email",
      "destructive": false,
      "requiredBody": [
        "email"
      ],
      "bodyNote": "Body shape: {\"email\": {\"email_subject\", \"email_body\", \"email_pre_header\"?, \"design_template\"?, \"template_id\"?, \"settings\": {\"timings\": {\"delay\", \"delay_unit\", \"is_anytime\"}}}} — every field nests under the top-level \"email\" object (the plugin silently ignores flat body fields and the insert fails). The row title is set from email_subject. TIMING SEMANTICS: settings.timings.delay × delay_unit is recomputed into the row's delay column (seconds) on save, and that delay is an ABSOLUTE offset from the contact's enrollment — NOT relative to the previous email. delay 172800 sends 2 days after enrollment regardless of what comes before; emails sharing the same delay send together as one group. sending_time (with is_anytime:\"no\") is a [start,end] time-of-day window applied on the target day; it is silently ignored while is_anytime is \"yes\"."
    },
    "delete_sequence": {
      "op": "sequences/delete-sequence",
      "method": "DELETE",
      "path": "/sequences/{id}",
      "summary": "Delete Sequence",
      "destructive": true
    },
    "delete_sequence_email": {
      "op": "sequences/delete-sequence-email",
      "method": "DELETE",
      "path": "/sequences/{id}/email/{email_id}",
      "summary": "Delete Sequence Email",
      "destructive": true
    },
    "duplicate_sequence": {
      "op": "sequences/duplicate-sequence",
      "method": "POST",
      "path": "/sequences/{id}/duplicate",
      "summary": "Duplicate Sequence",
      "destructive": false
    },
    "duplicate_sequence_email": {
      "op": "sequences/duplicate-sequence-email",
      "method": "POST",
      "path": "/sequences/{id}/email/duplicate",
      "summary": "Duplicate Sequence Email",
      "destructive": false
    },
    "get_sequence": {
      "op": "sequences/get-sequence",
      "method": "GET",
      "path": "/sequences/{id}",
      "summary": "Get Sequence",
      "destructive": false
    },
    "get_sequence_email": {
      "op": "sequences/get-sequence-email",
      "method": "GET",
      "path": "/sequences/{id}/email/{email_id}",
      "summary": "Get Sequence Email",
      "destructive": false
    },
    "get_sequence_subscribers": {
      "op": "sequences/get-sequence-subscribers",
      "method": "GET",
      "path": "/sequences/{id}/subscribers",
      "summary": "Get Sequence Subscribers",
      "destructive": false
    },
    "get_subscriber_sequences": {
      "op": "sequences/get-subscriber-sequences",
      "method": "GET",
      "path": "/sequences/subscriber/{subscriber_id}/sequences",
      "summary": "Get Subscriber Sequences",
      "destructive": false
    },
    "list_sequences": {
      "op": "sequences/list-sequences",
      "method": "GET",
      "path": "/sequences",
      "summary": "List Sequences",
      "destructive": false
    },
    "reapply_sequence": {
      "op": "sequences/reapply-sequence",
      "method": "POST",
      "path": "/sequences/{id}/reapply",
      "summary": "Reapply Sequence",
      "destructive": false
    },
    "remove_sequence_subscribers": {
      "op": "sequences/remove-sequence-subscribers",
      "method": "DELETE",
      "path": "/sequences/{id}/subscribers",
      "summary": "Remove Sequence Subscribers",
      "destructive": true
    },
    "update_sequence": {
      "op": "sequences/update-sequence",
      "method": "PUT",
      "path": "/sequences/{id}",
      "summary": "Update Sequence",
      "destructive": false
    },
    "update_sequence_email": {
      "op": "sequences/update-sequence-email",
      "method": "PUT",
      "path": "/sequences/{id}/email/{email_id}",
      "summary": "Update Sequence Email",
      "destructive": false,
      "requiredBody": [
        "email"
      ],
      "bodyNote": "Body shape: {\"email\": {\"email_subject\", \"email_body\", \"email_pre_header\"?, \"design_template\"?, \"template_id\"?, \"settings\": {\"timings\": {\"delay\", \"delay_unit\", \"is_anytime\"}}}} — every field nests under the top-level \"email\" object (the plugin silently ignores flat body fields). The row title is set from email_subject. TIMING SEMANTICS: settings.timings.delay × delay_unit is recomputed into the row's delay column (seconds) on save, and that delay is an ABSOLUTE offset from the contact's enrollment — NOT relative to the previous email. delay 172800 sends 2 days after enrollment regardless of what comes before; emails sharing the same delay send together as one group. sending_time (with is_anytime:\"no\") is a [start,end] time-of-day window applied on the target day; it is silently ignored while is_anytime is \"yes\". Preview the computed timetable with crm_sequences_preview_schedule and sanity-check with crm_sequences_validate."
    }
  },
  "crm_automations": {
    "bulk_action_funnels": {
      "op": "funnels/bulk-action-funnels",
      "method": "POST",
      "path": "/funnels/do-bulk-action",
      "summary": "Bulk Action Funnels",
      "destructive": true
    },
    "change_funnel_trigger": {
      "op": "funnels/change-funnel-trigger",
      "method": "PUT",
      "path": "/funnels/{id}/change-trigger",
      "summary": "Change Funnel Trigger",
      "destructive": false
    },
    "clone_funnel": {
      "op": "funnels/clone-funnel",
      "method": "POST",
      "path": "/funnels/{id}/clone",
      "summary": "Clone Funnel",
      "destructive": false
    },
    "create_funnel": {
      "op": "funnels/create-funnel",
      "method": "POST",
      "path": "/funnels",
      "summary": "Create Funnel",
      "destructive": false
    },
    "create_funnel_from_template": {
      "op": "funnels/create-funnel-from-template",
      "method": "POST",
      "path": "/funnels/create-from-template",
      "summary": "Create Funnel from Template",
      "destructive": false
    },
    "delete_funnel": {
      "op": "funnels/delete-funnel",
      "method": "DELETE",
      "path": "/funnels/{id}",
      "summary": "Delete Funnel",
      "destructive": true
    },
    "delete_funnel_subscribers": {
      "op": "funnels/delete-funnel-subscribers",
      "method": "DELETE",
      "path": "/funnels/{id}/subscribers",
      "summary": "Delete Funnel Subscribers",
      "destructive": true
    },
    "force_advance_funnel_subscriber": {
      "op": "funnels/force-advance-funnel-subscriber",
      "method": "POST",
      "path": "/funnels/{id}/subscribers/{subscriber_id}/advance",
      "summary": "Force Advance Funnel Subscriber",
      "destructive": false
    },
    "get_funnel": {
      "op": "funnels/get-funnel",
      "method": "GET",
      "path": "/funnels/{id}",
      "summary": "Get Funnel",
      "destructive": false
    },
    "get_funnel_all_activities": {
      "op": "funnels/get-funnel-all-activities",
      "method": "GET",
      "path": "/funnels/all-activities",
      "summary": "Get All Funnel Activities",
      "destructive": false
    },
    "get_funnel_email_reports": {
      "op": "funnels/get-funnel-email-reports",
      "method": "GET",
      "path": "/funnels/{id}/email_reports",
      "summary": "Get Funnel Email Reports",
      "destructive": false
    },
    "get_funnel_report": {
      "op": "funnels/get-funnel-report",
      "method": "GET",
      "path": "/funnels/{id}/report",
      "summary": "Get Funnel Report",
      "destructive": false
    },
    "get_funnel_subscriber_reporting": {
      "op": "funnels/get-funnel-subscriber-reporting",
      "method": "GET",
      "path": "/funnels/{id}/subscribers/{contact_id}",
      "summary": "Get Funnel Subscriber Reporting",
      "destructive": false
    },
    "get_funnel_subscribers": {
      "op": "funnels/get-funnel-subscribers",
      "method": "GET",
      "path": "/funnels/{id}/subscribers",
      "summary": "Get Funnel Subscribers",
      "destructive": false
    },
    "get_funnel_syncable_counts": {
      "op": "funnels/get-funnel-syncable-counts",
      "method": "GET",
      "path": "/funnels/{id}/syncable-counts",
      "summary": "Get Funnel Syncable Counts",
      "destructive": false
    },
    "get_funnel_templates": {
      "op": "funnels/get-funnel-templates",
      "method": "GET",
      "path": "/funnels/templates",
      "summary": "Get Funnel Templates",
      "destructive": false
    },
    "get_funnel_triggers": {
      "op": "funnels/get-funnel-triggers",
      "method": "GET",
      "path": "/funnels/triggers",
      "summary": "Get Funnel Triggers",
      "destructive": false
    },
    "get_subscriber_automations": {
      "op": "funnels/get-subscriber-automations",
      "method": "GET",
      "path": "/funnels/subscriber/{subscriber_id}/automations",
      "summary": "Get Subscriber Automations",
      "destructive": false
    },
    "import_funnel": {
      "op": "funnels/import-funnel",
      "method": "POST",
      "path": "/funnels/import",
      "summary": "Import Funnel",
      "destructive": false
    },
    "list_funnels": {
      "op": "funnels/list-funnels",
      "method": "GET",
      "path": "/funnels",
      "summary": "List Funnels",
      "destructive": false
    },
    "remove_funnel_bulk_subscribers": {
      "op": "funnels/remove-funnel-bulk-subscribers",
      "method": "POST",
      "path": "/funnels/remove-bulk-subscribers",
      "summary": "Remove Bulk Subscribers from Funnels",
      "destructive": true
    },
    "save_email_action_fallback": {
      "op": "funnels/save-email-action-fallback",
      "method": "POST",
      "path": "/funnels/funnel/save-email-action-fallback",
      "summary": "Save Email Action (Fallback)",
      "destructive": false
    },
    "save_funnel_email_action": {
      "op": "funnels/save-funnel-email-action",
      "method": "POST",
      "path": "/funnels/{id}/sequences/save-email-action",
      "summary": "Save Funnel Email Action",
      "destructive": false
    },
    "save_funnel_sequences": {
      "op": "funnels/save-funnel-sequences",
      "method": "POST",
      "path": "/funnels/{id}/sequences",
      "summary": "Save Funnel Sequences",
      "destructive": false
    },
    "save_funnel_sequences_fallback": {
      "op": "funnels/save-funnel-sequences-fallback",
      "method": "POST",
      "path": "/funnels/funnel/save-funnel-sequences",
      "summary": "Save Funnel Sequences (Fallback)",
      "destructive": false
    },
    "send_test_webhook": {
      "op": "funnels/send-test-webhook",
      "method": "POST",
      "path": "/funnels/send-test-webhook",
      "summary": "Send Test Webhook",
      "destructive": false
    },
    "sync_funnel_new_steps": {
      "op": "funnels/sync-funnel-new-steps",
      "method": "POST",
      "path": "/funnels/{id}/sync-new-steps",
      "summary": "Sync Funnel New Steps",
      "destructive": false
    },
    "update_funnel_labels": {
      "op": "funnels/update-funnel-labels",
      "method": "PUT",
      "path": "/funnels/{id}/update-labels",
      "summary": "Update Funnel Labels",
      "destructive": false
    },
    "update_funnel_property": {
      "op": "funnels/update-funnel-property",
      "method": "PUT",
      "path": "/funnels/{id}",
      "summary": "Update Funnel Property",
      "destructive": false
    },
    "update_funnel_subscription_status": {
      "op": "funnels/update-funnel-subscription-status",
      "method": "PUT",
      "path": "/funnels/{id}/subscribers/{subscriber_id}/status",
      "summary": "Update Funnel Subscription Status",
      "destructive": false
    },
    "update_funnel_title": {
      "op": "funnels/update-funnel-title",
      "method": "PUT",
      "path": "/funnels/funnel/{id}/title",
      "summary": "Update Funnel Title",
      "destructive": false
    }
  },
  "crm_templates": {
    "bulk_action_templates": {
      "op": "templates/bulk-action-templates",
      "method": "POST",
      "path": "/templates/do-bulk-action",
      "summary": "Bulk Action Templates",
      "destructive": true
    },
    "create_template": {
      "op": "templates/create-template",
      "method": "POST",
      "path": "/templates",
      "summary": "Create Template",
      "destructive": false
    },
    "delete_template": {
      "op": "templates/delete-template",
      "method": "DELETE",
      "path": "/templates/{id}",
      "summary": "Delete Template",
      "destructive": true
    },
    "duplicate_template": {
      "op": "templates/duplicate-template",
      "method": "POST",
      "path": "/templates/duplicate/{id}",
      "summary": "Duplicate Template",
      "destructive": false
    },
    "get_built_in_templates": {
      "op": "templates/get-built-in-templates",
      "method": "GET",
      "path": "/templates/built-in-templates",
      "summary": "Get Built-In Templates",
      "destructive": false
    },
    "get_smart_codes": {
      "op": "templates/get-smart-codes",
      "method": "GET",
      "path": "/templates/smartcodes",
      "summary": "Get Smart Codes",
      "destructive": false
    },
    "get_template": {
      "op": "templates/get-template",
      "method": "GET",
      "path": "/templates/{id}",
      "summary": "Get Template",
      "destructive": false
    },
    "list_all_templates": {
      "op": "templates/list-all-templates",
      "method": "GET",
      "path": "/templates/all",
      "summary": "List All Templates",
      "destructive": false
    },
    "list_templates": {
      "op": "templates/list-templates",
      "method": "GET",
      "path": "/templates",
      "summary": "List Templates",
      "destructive": false
    },
    "set_global_style": {
      "op": "templates/set-global-style",
      "method": "POST",
      "path": "/templates/set-global-style",
      "summary": "Set Global Style",
      "destructive": false
    },
    "update_template": {
      "op": "templates/update-template",
      "method": "PUT",
      "path": "/templates/{id}",
      "summary": "Update Template",
      "destructive": false
    }
  },
  "crm_forms": {
    "create_form": {
      "op": "forms/create-form",
      "method": "POST",
      "path": "/forms",
      "summary": "Create Form",
      "destructive": false
    },
    "get_form_entries": {
      "op": "forms/get-form-entries",
      "method": "GET",
      "path": "/forms/{id}/entries",
      "summary": "Form Entries",
      "destructive": false
    },
    "get_form_entry": {
      "op": "forms/get-form-entry",
      "method": "GET",
      "path": "/forms/{form_id}/entries/{id}",
      "summary": "Form Entry",
      "destructive": false
    },
    "get_form_templates": {
      "op": "forms/get-form-templates",
      "method": "GET",
      "path": "/forms/templates",
      "summary": "Form Templates",
      "destructive": false
    },
    "list_forms": {
      "op": "forms/list-forms",
      "method": "GET",
      "path": "/forms",
      "summary": "List Forms",
      "destructive": false
    }
  },
  "crm_webhooks": {
    "create_webhook": {
      "op": "webhooks/create-webhook",
      "method": "POST",
      "path": "/webhooks",
      "summary": "Create Webhook",
      "destructive": false
    },
    "delete_webhook": {
      "op": "webhooks/delete-webhook",
      "method": "DELETE",
      "path": "/webhooks/{id}",
      "summary": "Delete Webhook",
      "destructive": true
    },
    "list_sms_webhooks": {
      "op": "webhooks/list-sms-webhooks",
      "method": "GET",
      "path": "/webhooks/sms",
      "summary": "List SMS Webhooks",
      "destructive": false
    },
    "list_webhooks": {
      "op": "webhooks/list-webhooks",
      "method": "GET",
      "path": "/webhooks",
      "summary": "List Webhooks",
      "destructive": false
    },
    "update_webhook": {
      "op": "webhooks/update-webhook",
      "method": "PUT",
      "path": "/webhooks/{id}",
      "summary": "Update Webhook",
      "destructive": false
    }
  },
  "crm_smart_links": {
    "activate_smart_link": {
      "op": "smart-links/activate-smart-link",
      "method": "POST",
      "path": "/smart-links/activate",
      "summary": "Activate Smart Links Module",
      "destructive": false
    },
    "create_smart_link": {
      "op": "smart-links/create-smart-link",
      "method": "POST",
      "path": "/smart-links",
      "summary": "Create Smart Link",
      "destructive": false
    },
    "delete_smart_link": {
      "op": "smart-links/delete-smart-link",
      "method": "DELETE",
      "path": "/smart-links/{id}",
      "summary": "Delete Smart Link",
      "destructive": true
    },
    "list_smart_links": {
      "op": "smart-links/list-smart-links",
      "method": "GET",
      "path": "/smart-links",
      "summary": "List Smart Links",
      "destructive": false
    },
    "update_smart_link": {
      "op": "smart-links/update-smart-link",
      "method": "PUT",
      "path": "/smart-links/{id}",
      "summary": "Update Smart Link",
      "destructive": false
    }
  },
  "crm_sms": {
    "bulk_action_sms_campaigns": {
      "op": "sms/bulk-action-sms-campaigns",
      "method": "POST",
      "path": "/sms/campaigns/do-bulk-action",
      "summary": "Bulk Action on SMS Campaigns",
      "destructive": true
    },
    "create_sms_campaign": {
      "op": "sms/create-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns",
      "summary": "Create SMS Campaign",
      "destructive": false
    },
    "delete_sms_campaign": {
      "op": "sms/delete-sms-campaign",
      "method": "DELETE",
      "path": "/sms/campaigns/{id}",
      "summary": "Delete SMS Campaign",
      "destructive": true
    },
    "delete_sms_messages": {
      "op": "sms/delete-sms-messages",
      "method": "DELETE",
      "path": "/sms/messages",
      "summary": "Delete SMS Messages",
      "destructive": true
    },
    "do_sms_campaign_tag_actions": {
      "op": "sms/do-sms-campaign-tag-actions",
      "method": "POST",
      "path": "/sms/campaigns/{id}/tag-actions",
      "summary": "Apply Tag Actions to SMS Campaign Recipients",
      "destructive": false
    },
    "duplicate_sms_campaign": {
      "op": "sms/duplicate-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns/{id}/duplicate",
      "summary": "Duplicate SMS Campaign",
      "destructive": false
    },
    "estimate_sms_campaign_contacts": {
      "op": "sms/estimate-sms-campaign-contacts",
      "method": "POST",
      "path": "/sms/campaigns/estimated-contacts",
      "summary": "Estimate SMS Campaign Contacts",
      "destructive": false
    },
    "get_sms_campaign": {
      "op": "sms/get-sms-campaign",
      "method": "GET",
      "path": "/sms/campaigns/{id}",
      "summary": "Get SMS Campaign",
      "destructive": false
    },
    "get_sms_campaign_processing_stat": {
      "op": "sms/get-sms-campaign-processing-stat",
      "method": "GET",
      "path": "/sms/campaigns/{id}/processing-stat",
      "summary": "Get SMS Campaign Processing Status",
      "destructive": false
    },
    "get_sms_campaign_recipients": {
      "op": "sms/get-sms-campaign-recipients",
      "method": "GET",
      "path": "/sms/campaigns/{id}/recipients",
      "summary": "Get SMS Campaign Recipients",
      "destructive": false
    },
    "get_sms_campaign_recipients_count": {
      "op": "sms/get-sms-campaign-recipients-count",
      "method": "GET",
      "path": "/sms/campaigns/{id}/estimated-recipients-count",
      "summary": "Get SMS Campaign Recipients Count",
      "destructive": false
    },
    "get_sms_campaign_status": {
      "op": "sms/get-sms-campaign-status",
      "method": "GET",
      "path": "/sms/campaigns/{id}/status",
      "summary": "Get SMS Campaign Status",
      "destructive": false
    },
    "get_subscriber_sms_logs": {
      "op": "sms/get-subscriber-sms-logs",
      "method": "GET",
      "path": "/sms/subscribers/{id}/logs",
      "summary": "Get Subscriber SMS Logs",
      "destructive": false
    },
    "get_subscriber_sms_stats": {
      "op": "sms/get-subscriber-sms-stats",
      "method": "GET",
      "path": "/sms/subscribers/{id}/stats",
      "summary": "Get Subscriber SMS Statistics",
      "destructive": false
    },
    "list_sms_campaigns": {
      "op": "sms/list-sms-campaigns",
      "method": "GET",
      "path": "/sms/campaigns",
      "summary": "List SMS Campaigns",
      "destructive": false
    },
    "list_sms_messages": {
      "op": "sms/list-sms-messages",
      "method": "GET",
      "path": "/sms/messages",
      "summary": "List All SMS Messages",
      "destructive": false
    },
    "pause_sms_campaign": {
      "op": "sms/pause-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns/{id}/pause",
      "summary": "Pause SMS Campaign",
      "destructive": false
    },
    "resend_sms_message": {
      "op": "sms/resend-sms-message",
      "method": "POST",
      "path": "/sms/messages/{id}/resend",
      "summary": "Resend SMS Message",
      "destructive": false
    },
    "resume_sms_campaign": {
      "op": "sms/resume-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns/{id}/resume",
      "summary": "Resume SMS Campaign",
      "destructive": true
    },
    "schedule_sms_campaign": {
      "op": "sms/schedule-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns/{id}/schedule",
      "summary": "Schedule SMS Campaign",
      "destructive": true
    },
    "send_subscriber_custom_sms": {
      "op": "sms/send-subscriber-custom-sms",
      "method": "POST",
      "path": "/sms/subscribers/{id}/send",
      "summary": "Send Custom SMS to Subscriber",
      "destructive": false
    },
    "unschedule_sms_campaign": {
      "op": "sms/unschedule-sms-campaign",
      "method": "POST",
      "path": "/sms/campaigns/{id}/unschedule",
      "summary": "Unschedule SMS Campaign",
      "destructive": false
    },
    "update_sms_campaign": {
      "op": "sms/update-sms-campaign",
      "method": "PUT",
      "path": "/sms/campaigns/{id}",
      "summary": "Update SMS Campaign",
      "destructive": false
    },
    "update_sms_campaign_labels": {
      "op": "sms/update-sms-campaign-labels",
      "method": "PUT",
      "path": "/sms/{id}/update-labels",
      "summary": "Update SMS Campaign Labels",
      "destructive": false
    }
  },
  "crm_reports": {
    "get_commerce_report": {
      "op": "commerce-reports/get-commerce-report",
      "method": "GET",
      "path": "/commerce-reports/{provider}/report",
      "summary": "Commerce Report",
      "destructive": false
    },
    "get_commerce_reports": {
      "op": "commerce-reports/get-commerce-reports",
      "method": "GET",
      "path": "/commerce-reports/{provider}",
      "summary": "Commerce Reports",
      "destructive": false
    },
    "get_advanced_report_providers": {
      "op": "reports/get-advanced-report-providers",
      "method": "GET",
      "path": "/reports/advanced-providers",
      "summary": "Advanced Report Providers",
      "destructive": false
    },
    "get_ajax_options": {
      "op": "reports/get-ajax-options",
      "method": "GET",
      "path": "/reports/ajax-options",
      "summary": "Ajax Options",
      "destructive": false
    },
    "get_cascade_selections": {
      "op": "reports/get-cascade-selections",
      "method": "GET",
      "path": "/reports/cascade_selections",
      "summary": "Cascade Selections",
      "destructive": false
    },
    "get_contact_growth": {
      "op": "reports/get-contact-growth",
      "method": "GET",
      "path": "/reports/subscribers",
      "summary": "Contact Growth",
      "destructive": false
    },
    "get_dashboard_stats": {
      "op": "reports/get-dashboard-stats",
      "method": "GET",
      "path": "/reports/dashboard-stats",
      "summary": "Dashboard Stats",
      "destructive": false
    },
    "get_email_click_stats": {
      "op": "reports/get-email-click-stats",
      "method": "GET",
      "path": "/reports/email-clicks",
      "summary": "Email Click Stats",
      "destructive": false
    },
    "get_email_open_stats": {
      "op": "reports/get-email-open-stats",
      "method": "GET",
      "path": "/reports/email-opens",
      "summary": "Email Open Stats",
      "destructive": false
    },
    "get_email_performance": {
      "op": "reports/get-email-performance",
      "method": "GET",
      "path": "/reports/email-performance",
      "summary": "Email Performance",
      "destructive": false
    },
    "get_email_sent_stats": {
      "op": "reports/get-email-sent-stats",
      "method": "GET",
      "path": "/reports/email-sents",
      "summary": "Email Sent Stats",
      "destructive": false
    },
    "get_report_emails": {
      "op": "reports/get-report-emails",
      "method": "GET",
      "path": "/reports/emails",
      "summary": "Report Emails",
      "destructive": false
    },
    "get_report_options": {
      "op": "reports/get-report-options",
      "method": "GET",
      "path": "/reports/options",
      "summary": "Report Options",
      "destructive": false
    },
    "get_taxonomy_terms": {
      "op": "reports/get-taxonomy-terms",
      "method": "GET",
      "path": "/reports/taxonomy-terms",
      "summary": "Taxonomy Terms",
      "destructive": false
    },
    "ping_report": {
      "op": "reports/ping-report",
      "method": "GET",
      "path": "/reports/ping",
      "summary": "Ping Report",
      "destructive": false
    },
    "global_search": {
      "op": "global-search/global-search",
      "method": "GET",
      "path": "/global-search",
      "summary": "Global Search",
      "destructive": false
    }
  },
  "crm_abandoned_carts": {
    "bulk_delete_abandoned_carts": {
      "op": "abandon-carts/bulk-delete-abandoned-carts",
      "method": "POST",
      "path": "/abandon-carts/bulk-delete",
      "summary": "Bulk Delete Abandoned Carts",
      "destructive": true
    },
    "get_abandon_cart_report_summary": {
      "op": "abandon-carts/get-abandon-cart-report-summary",
      "method": "GET",
      "path": "/abandon-carts/report-summary",
      "summary": "Get Abandon Cart Report Summary",
      "destructive": false
    },
    "list_abandoned_carts": {
      "op": "abandon-carts/list-abandoned-carts",
      "method": "GET",
      "path": "/abandon-carts",
      "summary": "List Abandoned Carts",
      "destructive": false
    }
  },
  "crm_settings": {
    "delete_report_emails": {
      "op": "reports/delete-report-emails",
      "method": "DELETE",
      "path": "/reports/emails",
      "summary": "Report Emails",
      "destructive": true
    },
    "complete_installation": {
      "op": "settings/complete-installation",
      "method": "POST",
      "path": "/setting/complete-installation",
      "summary": "Complete Installation Wizard",
      "destructive": false
    },
    "create_rest_key": {
      "op": "settings/create-rest-key",
      "method": "POST",
      "path": "/setting/rest-keys",
      "summary": "Create REST API Key",
      "destructive": true,
      "bodyNote": "Privilege/code change: Mints a standing REST API key — a persistent credential. Requires confirm:true."
    },
    "delete_rest_key": {
      "op": "settings/delete-rest-key",
      "method": "DELETE",
      "path": "/setting/rest-keys",
      "summary": "REST API Key",
      "destructive": true
    },
    "get_abandon_cart_settings": {
      "op": "settings/get-abandon-cart-settings",
      "method": "GET",
      "path": "/setting/abandon-cart",
      "summary": "Abandon Cart Settings",
      "destructive": false
    },
    "get_auto_subscribe_settings": {
      "op": "settings/get-auto-subscribe-settings",
      "method": "GET",
      "path": "/setting/auto_subscribe_settings",
      "summary": "Auto Subscribe Settings",
      "destructive": false
    },
    "get_bounce_configs": {
      "op": "settings/get-bounce-configs",
      "method": "GET",
      "path": "/setting/bounce_configs",
      "summary": "Bounce Handler Configurations",
      "destructive": false
    },
    "get_compliance_settings": {
      "op": "settings/get-compliance-settings",
      "method": "GET",
      "path": "/setting/compliance",
      "summary": "Compliance Settings",
      "destructive": false
    },
    "get_cron_status": {
      "op": "settings/get-cron-status",
      "method": "GET",
      "path": "/setting/cron_status",
      "summary": "Cron Status",
      "destructive": false
    },
    "get_double_optin_settings": {
      "op": "settings/get-double-optin-settings",
      "method": "GET",
      "path": "/setting/double-optin",
      "summary": "Double Opt-in Settings",
      "destructive": false
    },
    "get_experiment_campaigns": {
      "op": "settings/get-experiment-campaigns",
      "method": "GET",
      "path": "/setting/experiments/campaigns",
      "summary": "Experiment Campaigns",
      "destructive": false
    },
    "get_experimental_settings": {
      "op": "settings/get-experimental-settings",
      "method": "GET",
      "path": "/setting/experiments",
      "summary": "Experimental Settings",
      "destructive": false
    },
    "get_integrations": {
      "op": "settings/get-integrations",
      "method": "GET",
      "path": "/setting/integrations",
      "summary": "Deep Integration Providers",
      "destructive": false
    },
    "get_old_logs": {
      "op": "settings/get-old-logs",
      "method": "GET",
      "path": "/setting/old_logs",
      "summary": "Old Log Details",
      "destructive": false
    },
    "get_rest_keys": {
      "op": "settings/get-rest-keys",
      "method": "GET",
      "path": "/setting/rest-keys",
      "summary": "REST API Keys",
      "destructive": false
    },
    "get_settings": {
      "op": "settings/get-settings",
      "method": "GET",
      "path": "/setting",
      "summary": "Global Settings",
      "destructive": false
    },
    "get_system_logs": {
      "op": "settings/get-system-logs",
      "method": "GET",
      "path": "/setting/system-logs",
      "summary": "System Logs",
      "destructive": false
    },
    "install_fluent_boards": {
      "op": "settings/install-fluent-boards",
      "method": "POST",
      "path": "/setting/install-fluent-boards",
      "summary": "Install Fluent Boards Plugin",
      "destructive": false
    },
    "install_fluent_booking": {
      "op": "settings/install-fluent-booking",
      "method": "POST",
      "path": "/setting/install-fluent-booking",
      "summary": "Install Fluent Booking Plugin",
      "destructive": false
    },
    "install_fluent_cart": {
      "op": "settings/install-fluent-cart",
      "method": "POST",
      "path": "/setting/install-fluent-cart",
      "summary": "Install FluentCart Plugin",
      "destructive": false
    },
    "install_fluent_community": {
      "op": "settings/install-fluent-community",
      "method": "POST",
      "path": "/setting/install-fluent-community",
      "summary": "Install Fluent Community Plugin",
      "destructive": false
    },
    "install_fluent_form": {
      "op": "settings/install-fluent-form",
      "method": "POST",
      "path": "/setting/install-fluentform",
      "summary": "Install Fluent Forms Plugin",
      "destructive": false
    },
    "install_fluent_smtp": {
      "op": "settings/install-fluent-smtp",
      "method": "POST",
      "path": "/setting/install-fluentsmtp",
      "summary": "Install FluentSMTP Plugin",
      "destructive": false
    },
    "install_fluent_support": {
      "op": "settings/install-fluent-support",
      "method": "POST",
      "path": "/setting/install-fluent-support",
      "summary": "Install Fluent Support Plugin",
      "destructive": false
    },
    "remove_old_logs": {
      "op": "settings/remove-old-logs",
      "method": "DELETE",
      "path": "/setting/old_logs",
      "summary": "Remove Old Logs",
      "destructive": true
    },
    "reset_database": {
      "op": "settings/reset-database",
      "method": "POST",
      "path": "/setting/reset_db",
      "summary": "Reset Database",
      "destructive": true
    },
    "reset_system_logs": {
      "op": "settings/reset-system-logs",
      "method": "GET",
      "path": "/setting/system-logs/reset",
      "summary": "Reset System Logs",
      "destructive": true
    },
    "run_cron": {
      "op": "settings/run-cron",
      "method": "POST",
      "path": "/setting/run_cron",
      "summary": "Run Cron Event",
      "destructive": false
    },
    "save_abandon_cart_settings": {
      "op": "settings/save-abandon-cart-settings",
      "method": "POST",
      "path": "/setting/abandon-cart",
      "summary": "Save Abandon Cart Settings",
      "destructive": false
    },
    "save_auto_subscribe_settings": {
      "op": "settings/save-auto-subscribe-settings",
      "method": "POST",
      "path": "/setting/auto_subscribe_settings",
      "summary": "Save Auto Subscribe Settings",
      "destructive": false
    },
    "save_double_optin_settings": {
      "op": "settings/save-double-optin-settings",
      "method": "PUT",
      "path": "/setting/double-optin",
      "summary": "Save Double Opt-in Settings",
      "destructive": false
    },
    "save_integration": {
      "op": "settings/save-integration",
      "method": "POST",
      "path": "/setting/integrations",
      "summary": "Save Integration Settings",
      "destructive": false
    },
    "save_settings": {
      "op": "settings/save-settings",
      "method": "PUT",
      "path": "/setting",
      "summary": "Save Global Settings",
      "destructive": false
    },
    "test_delete_request": {
      "op": "settings/test-delete-request",
      "method": "DELETE",
      "path": "/setting/test",
      "summary": "Test Request Resolver",
      "destructive": true
    },
    "test_get_request": {
      "op": "settings/test-get-request",
      "method": "GET",
      "path": "/setting/test",
      "summary": "Test Request Resolver",
      "destructive": false
    },
    "test_post_request": {
      "op": "settings/test-post-request",
      "method": "POST",
      "path": "/setting/test",
      "summary": "Test Request Resolver",
      "destructive": false
    },
    "test_put_request": {
      "op": "settings/test-put-request",
      "method": "PUT",
      "path": "/setting/test",
      "summary": "Test Request Resolver",
      "destructive": false
    },
    "update_compliance_settings": {
      "op": "settings/update-compliance-settings",
      "method": "POST",
      "path": "/setting/compliance",
      "summary": "Update Compliance Settings",
      "destructive": false
    },
    "update_experimental_settings": {
      "op": "settings/update-experimental-settings",
      "method": "POST",
      "path": "/setting/experiments",
      "summary": "Update Experimental Settings",
      "destructive": false
    }
  },
  "crm_settings_pro": {
    "add_manager": {
      "op": "pro-settings/add-manager",
      "method": "POST",
      "path": "/campaign-pro-settings/managers",
      "summary": "Add Manager",
      "destructive": true,
      "bodyNote": "Privilege/code change: Grants a WordPress user FluentCRM manager access. Requires confirm:true."
    },
    "deactivate_license": {
      "op": "pro-settings/deactivate-license",
      "method": "DELETE",
      "path": "/campaign-pro-settings/license",
      "summary": "Deactivate License",
      "destructive": true
    },
    "delete_manager": {
      "op": "pro-settings/delete-manager",
      "method": "DELETE",
      "path": "/campaign-pro-settings/managers/{id}",
      "summary": "Remove Manager",
      "destructive": true
    },
    "disable_sms": {
      "op": "pro-settings/disable-sms",
      "method": "POST",
      "path": "/campaign-pro-settings/sms/disable",
      "summary": "Disable SMS",
      "destructive": false
    },
    "get_license_status": {
      "op": "pro-settings/get-license-status",
      "method": "GET",
      "path": "/campaign-pro-settings/license",
      "summary": "License Status",
      "destructive": false
    },
    "get_managers": {
      "op": "pro-settings/get-managers",
      "method": "GET",
      "path": "/campaign-pro-settings/managers",
      "summary": "List Managers",
      "destructive": false
    },
    "get_sms_settings": {
      "op": "pro-settings/get-sms-settings",
      "method": "GET",
      "path": "/campaign-pro-settings/sms",
      "summary": "SMS Settings",
      "destructive": false
    },
    "import_funnel": {
      "op": "pro-settings/import-funnel",
      "method": "POST",
      "path": "/campaign-pro-settings/import_funnel",
      "summary": "Import Funnel",
      "destructive": false
    },
    "save_license": {
      "op": "pro-settings/save-license",
      "method": "POST",
      "path": "/campaign-pro-settings/license",
      "summary": "Save License",
      "destructive": false
    },
    "save_sms_settings": {
      "op": "pro-settings/save-sms-settings",
      "method": "POST",
      "path": "/campaign-pro-settings/sms",
      "summary": "Save SMS Settings",
      "destructive": false
    },
    "update_manager": {
      "op": "pro-settings/update-manager",
      "method": "PUT",
      "path": "/campaign-pro-settings/managers/{id}",
      "summary": "Update Manager",
      "destructive": true,
      "bodyNote": "Privilege/code change: Changes a manager's permissions. Requires confirm:true."
    }
  },
  "crm_utilities": {
    "get_import_driver": {
      "op": "import/get-import-driver",
      "method": "GET",
      "path": "/import/drivers/{driver}",
      "summary": "Import Driver Details",
      "destructive": false
    },
    "get_import_drivers": {
      "op": "import/get-import-drivers",
      "method": "GET",
      "path": "/import/drivers",
      "summary": "Import Drivers",
      "destructive": false
    },
    "import_csv_contacts": {
      "op": "import/import-csv-contacts",
      "method": "POST",
      "path": "/import/csv-import",
      "summary": "Import Contacts from CSV",
      "destructive": false
    },
    "import_driver_data": {
      "op": "import/import-driver-data",
      "method": "POST",
      "path": "/import/drivers/{driver}",
      "summary": "Import Data via Driver",
      "destructive": false
    },
    "import_wp_users": {
      "op": "import/import-wp-users",
      "method": "POST",
      "path": "/import/users",
      "summary": "Import WordPress Users",
      "destructive": false
    },
    "upload_csv_import": {
      "op": "import/upload-csv-import",
      "method": "POST",
      "path": "/import/csv-upload",
      "summary": "Upload CSV for Import",
      "destructive": false
    },
    "get_migrator_drivers": {
      "op": "migrators/get-migrator-drivers",
      "method": "GET",
      "path": "/migrators",
      "summary": "Migrator Drivers",
      "destructive": false
    },
    "get_migrator_import_summary": {
      "op": "migrators/get-migrator-import-summary",
      "method": "POST",
      "path": "/migrators/summary",
      "summary": "Get Migrator Import Summary",
      "destructive": false
    },
    "get_migrator_list_tag_mappings": {
      "op": "migrators/get-migrator-list-tag-mappings",
      "method": "GET",
      "path": "/migrators/list-tag-mappings",
      "summary": "Migrator List/Tag Mappings",
      "destructive": false
    },
    "handle_migrator_import": {
      "op": "migrators/handle-migrator-import",
      "method": "POST",
      "path": "/migrators/import",
      "summary": "Execute Migrator Import",
      "destructive": false
    },
    "verify_migrator_credential": {
      "op": "migrators/verify-migrator-credential",
      "method": "POST",
      "path": "/migrators/verify-cred",
      "summary": "Verify Migrator Credential",
      "destructive": false
    },
    "get_user_roles": {
      "op": "users/get-user-roles",
      "method": "GET",
      "path": "/users/roles",
      "summary": "WordPress User Roles",
      "destructive": false
    },
    "list_users": {
      "op": "users/list-users",
      "method": "GET",
      "path": "/users",
      "summary": "List WordPress Users",
      "destructive": false
    },
    "get_doc": {
      "op": "docs/get-doc",
      "method": "GET",
      "path": "/docs/{doc_id}",
      "summary": "Get Doc",
      "destructive": false
    },
    "get_doc_addons": {
      "op": "docs/get-doc-addons",
      "method": "GET",
      "path": "/docs/addons",
      "summary": "Get Addons",
      "destructive": false
    },
    "list_docs": {
      "op": "docs/list-docs",
      "method": "GET",
      "path": "/docs",
      "summary": "List Docs",
      "destructive": false
    },
    "handle_bounce": {
      "op": "public-bounce/handle-bounce",
      "method": "POST",
      "path": "/public/bounce_handler/{service_name}/{security_code}",
      "summary": "Handle Bounce",
      "destructive": false
    },
    "handle_bounce_with_handle": {
      "op": "public-bounce/handle-bounce-with-handle",
      "method": "POST",
      "path": "/public/bounce_handler/{service_name}/handle/{security_code}",
      "summary": "Handle Bounce (with /handle/ path)",
      "destructive": false
    }
  }
};

export const TOOL_META: Record<string, { description: string; note?: string; idempotent?: boolean }> = {
  "crm_contacts": {
    "description": "Look up, create, update, delete, and manage CRM contacts (subscribers), including their notes, tags, lists, and email history."
  },
  "crm_lists": {
    "description": "View, create, update, or delete the contact lists used to organize CRM subscribers."
  },
  "crm_tags": {
    "description": "View, create, update, or delete the tags used to label CRM contacts."
  },
  "crm_segments": {
    "description": "View, create, update, or delete dynamic contact segments and see which contacts match them."
  },
  "crm_custom_fields": {
    "description": "View or update the custom contact fields configured in the CRM.",
    "idempotent": true
  },
  "crm_labels": {
    "description": "View, create, update, or delete the labels used to organize items in the CRM."
  },
  "crm_companies": {
    "description": "Look up, create, update, delete, and manage CRM companies, their notes, and their associated contacts."
  },
  "crm_campaigns": {
    "description": "Create, schedule, send, pause, duplicate, delete, and analyze one-off email campaigns, including resending failed or unopened emails."
  },
  "crm_recurring_campaigns": {
    "description": "Manage recurring (automatically repeating) email campaigns from creation through scheduling and deletion (FluentCRM Pro)."
  },
  "crm_sequences": {
    "description": "Manage email sequence (drip) automations, their emails, and their subscribers (FluentCRM Pro)."
  },
  "crm_automations": {
    "description": "Manage marketing automation funnels and their subscribers, from creation and editing to import, export, and deletion."
  },
  "crm_templates": {
    "description": "Manage reusable email templates, including creating, duplicating, updating, and deleting them."
  },
  "crm_forms": {
    "description": "View and manage the opt-in forms connected to the CRM."
  },
  "crm_webhooks": {
    "description": "Manage incoming webhooks that create or update CRM contacts from external services."
  },
  "crm_smart_links": {
    "description": "Manage Smart Links that tag and redirect contacts when clicked (FluentCRM Pro)."
  },
  "crm_sms": {
    "description": "Manage SMS campaigns, templates, contacts' phone data, and SMS settings (FluentCRM Pro)."
  },
  "crm_reports": {
    "description": "Read-only CRM analytics: dashboard stats, subscriber growth, email and revenue reports, commerce reports, and global search."
  },
  "crm_abandoned_carts": {
    "description": "View abandoned-cart records and their report summary, and delete records in bulk (FluentCRM Pro commerce feature)."
  },
  "crm_settings": {
    "description": "Read or update FluentCRM settings such as double opt-in, business info, email preferences, compliance, and experimental features."
  },
  "crm_settings_pro": {
    "description": "Read or update FluentCRM Pro settings such as the plugin license and Pro-only features."
  },
  "crm_utilities": {
    "description": "Administrative utilities: import contacts from CSV or WordPress users, migrate from other tools, list WordPress users and roles, browse in-app docs, and receive bounce webhooks.",
    "note": "The two handle_bounce actions are webhook receivers meant to be called by email services, not by API clients."
  }
};
