/* AUTO-GENERATED by scripts/gen-endpoint-maps.mjs from docs/api-reference/wpsocialninja/endpoints.json — do not edit by hand. */
import type { EndpointDef } from '../../core/types.js';

export const TOOL_ENDPOINTS: Record<string, Record<string, EndpointDef>> = {
  "social_reviews": {
    "list_reviews": {
      "op": "reviews/list-reviews",
      "method": "GET",
      "path": "/reviews",
      "summary": "List Reviews",
      "destructive": false
    },
    "create_review": {
      "op": "reviews/create-review",
      "method": "POST",
      "path": "/reviews",
      "summary": "Create Review",
      "destructive": false
    },
    "delete_reviews": {
      "op": "reviews/delete-reviews",
      "method": "DELETE",
      "path": "/reviews",
      "summary": "Delete Reviews",
      "destructive": true
    },
    "update_review": {
      "op": "reviews/update-review",
      "method": "PUT",
      "path": "/reviews/{id}",
      "summary": "Update Review",
      "destructive": false
    },
    "duplicate_review": {
      "op": "reviews/duplicate-review",
      "method": "POST",
      "path": "/reviews/duplicate",
      "summary": "Duplicate Review",
      "destructive": false
    },
    "update_review_statuses": {
      "op": "reviews/update-review-statuses",
      "method": "PUT",
      "path": "/reviews/status-update",
      "summary": "Update Review Statuses",
      "destructive": false
    },
    "mark_reviews_spam": {
      "op": "reviews/mark-reviews-spam",
      "method": "PUT",
      "path": "/reviews/spam",
      "summary": "Mark Reviews as Spam",
      "destructive": false
    },
    "bulk_assign_review_category": {
      "op": "reviews/bulk-assign-review-category",
      "method": "PUT",
      "path": "/reviews/bulk-category",
      "summary": "Bulk Assign Review Category",
      "destructive": false
    },
    "list_review_categories": {
      "op": "reviews/list-review-categories",
      "method": "GET",
      "path": "/reviews/categories",
      "summary": "List Review Categories",
      "destructive": false
    },
    "update_review_category": {
      "op": "reviews/update-review-category",
      "method": "PUT",
      "path": "/reviews/categories/{id}",
      "summary": "Update Review Category",
      "destructive": false
    },
    "delete_review_category": {
      "op": "reviews/delete-review-category",
      "method": "DELETE",
      "path": "/reviews/categories/{id}",
      "summary": "Delete Review Category",
      "destructive": true
    }
  },
  "social_testimonials": {
    "list_testimonials": {
      "op": "testimonials/list-testimonials",
      "method": "GET",
      "path": "/testimonials",
      "summary": "List Testimonials",
      "destructive": false
    },
    "create_testimonial": {
      "op": "testimonials/create-testimonial",
      "method": "POST",
      "path": "/testimonials",
      "summary": "Create Testimonial",
      "destructive": false
    },
    "delete_testimonials": {
      "op": "testimonials/delete-testimonials",
      "method": "DELETE",
      "path": "/testimonials",
      "summary": "Delete Testimonials",
      "destructive": true
    },
    "update_testimonial": {
      "op": "testimonials/update-testimonial",
      "method": "PUT",
      "path": "/testimonials/{id}",
      "summary": "Update Testimonial",
      "destructive": false
    },
    "duplicate_testimonial": {
      "op": "testimonials/duplicate-testimonial",
      "method": "POST",
      "path": "/testimonials/duplicate",
      "summary": "Duplicate Testimonial",
      "destructive": false
    },
    "update_testimonial_statuses": {
      "op": "testimonials/update-testimonial-statuses",
      "method": "PUT",
      "path": "/testimonials/status-update",
      "summary": "Update Testimonial Statuses",
      "destructive": false
    },
    "mark_testimonials_spam": {
      "op": "testimonials/mark-testimonials-spam",
      "method": "PUT",
      "path": "/testimonials/spam",
      "summary": "Mark Testimonials as Spam",
      "destructive": false
    },
    "bulk_assign_testimonial_category": {
      "op": "testimonials/bulk-assign-testimonial-category",
      "method": "PUT",
      "path": "/testimonials/bulk-category",
      "summary": "Bulk Assign Testimonial Category",
      "destructive": false
    },
    "list_testimonial_categories": {
      "op": "testimonials/list-testimonial-categories",
      "method": "GET",
      "path": "/testimonials/categories",
      "summary": "List Testimonial Categories",
      "destructive": false
    },
    "update_testimonial_category": {
      "op": "testimonials/update-testimonial-category",
      "method": "PUT",
      "path": "/testimonials/categories/{id}",
      "summary": "Update Testimonial Category",
      "destructive": false
    },
    "delete_testimonial_category": {
      "op": "testimonials/delete-testimonial-category",
      "method": "DELETE",
      "path": "/testimonials/categories/{id}",
      "summary": "Delete Testimonial Category",
      "destructive": true
    }
  },
  "social_templates": {
    "list_templates": {
      "op": "templates/list-templates",
      "method": "GET",
      "path": "/templates",
      "summary": "List Templates",
      "destructive": false
    },
    "create_template": {
      "op": "templates/create-template",
      "method": "POST",
      "path": "/templates",
      "summary": "Create Template",
      "destructive": false
    },
    "delete_templates": {
      "op": "templates/delete-templates",
      "method": "DELETE",
      "path": "/templates",
      "summary": "Delete Templates",
      "destructive": true
    },
    "duplicate_template": {
      "op": "templates/duplicate-template",
      "method": "POST",
      "path": "/templates/duplicate",
      "summary": "Duplicate Template",
      "destructive": false
    },
    "update_template_title": {
      "op": "templates/update-template-title",
      "method": "PUT",
      "path": "/templates/title/{id}",
      "summary": "Update Template Title",
      "destructive": false
    },
    "get_reviews_template": {
      "op": "templates/get-reviews-template",
      "method": "GET",
      "path": "/templates/meta/reviews/{id}",
      "summary": "Get Reviews Template Meta",
      "destructive": false
    },
    "update_reviews_template": {
      "op": "templates/update-reviews-template",
      "method": "PUT",
      "path": "/templates/meta/reviews/{id}",
      "summary": "Update Reviews Template Meta",
      "destructive": false
    },
    "edit_reviews_template": {
      "op": "templates/edit-reviews-template",
      "method": "POST",
      "path": "/templates/meta/reviews/{id}/edit",
      "summary": "Edit Reviews Template",
      "destructive": false
    },
    "load_more_template_reviews": {
      "op": "templates/load-more-template-reviews",
      "method": "POST",
      "path": "/templates/meta/reviews/{id}/load-more",
      "summary": "Load More Template Reviews",
      "destructive": false
    },
    "can_enable_ai_summary": {
      "op": "templates/can-enable-ai-summary",
      "method": "GET",
      "path": "/templates/meta/reviews/{id}/can-enable-ai-summary",
      "summary": "Can Enable AI Summary",
      "destructive": false
    },
    "get_reviews_template_first_round": {
      "op": "templates/get-reviews-template-first-round",
      "method": "GET",
      "path": "/templates/meta/reviews/{id}/first-round/{isFirstRound}",
      "summary": "Get Reviews Template (First Round)",
      "destructive": false
    },
    "get_feed_template": {
      "op": "templates/get-feed-template",
      "method": "GET",
      "path": "/templates/meta/feeds/{id}",
      "summary": "Get Feed Template Meta",
      "destructive": false
    },
    "update_feed_template": {
      "op": "templates/update-feed-template",
      "method": "PUT",
      "path": "/templates/meta/feeds/{id}",
      "summary": "Update Feed Template Meta",
      "destructive": false
    },
    "edit_feed_template": {
      "op": "templates/edit-feed-template",
      "method": "POST",
      "path": "/templates/meta/feeds/{id}/edit",
      "summary": "Edit Feed Template",
      "destructive": false
    }
  },
  "social_platforms": {
    "list_platforms": {
      "op": "platforms/list-platforms",
      "method": "GET",
      "path": "/platforms",
      "summary": "List Platforms",
      "destructive": false
    },
    "list_enabled_platforms": {
      "op": "platforms/list-enabled-platforms",
      "method": "GET",
      "path": "/platforms/enabled",
      "summary": "List Enabled Platforms",
      "destructive": false
    },
    "get_platform_statuses": {
      "op": "platforms/get-platform-statuses",
      "method": "GET",
      "path": "/platforms/get-statuses",
      "summary": "Get Platform Statuses",
      "destructive": false
    },
    "update_platform_statuses": {
      "op": "platforms/update-platform-statuses",
      "method": "POST",
      "path": "/platforms/update-statuses",
      "summary": "Update Platform Statuses",
      "destructive": false
    },
    "update_platform_addons": {
      "op": "platforms/update-platform-addons",
      "method": "POST",
      "path": "/platforms/addons",
      "summary": "Update Platform Addons",
      "destructive": false
    },
    "subscribe_platform_updates": {
      "op": "platforms/subscribe-platform-updates",
      "method": "POST",
      "path": "/platforms/subscribe",
      "summary": "Subscribe to Platform Updates",
      "destructive": false
    },
    "get_dashboard_notices": {
      "op": "platforms/get-dashboard-notices",
      "method": "GET",
      "path": "/platforms/dashboard-notices",
      "summary": "Get Dashboard Notices",
      "destructive": false
    },
    "update_dashboard_notices": {
      "op": "platforms/update-dashboard-notices",
      "method": "POST",
      "path": "/platforms/dashboard-notices",
      "summary": "Update Dashboard Notices",
      "destructive": false
    },
    "get_review_platform_configs": {
      "op": "platforms/get-review-platform-configs",
      "method": "GET",
      "path": "/platforms/reviews/configs",
      "summary": "Get Review Platform Configs",
      "destructive": false
    },
    "save_review_platform_config": {
      "op": "platforms/save-review-platform-config",
      "method": "POST",
      "path": "/platforms/reviews/configs",
      "summary": "Save Review Platform Config",
      "destructive": false
    },
    "delete_review_platform_config": {
      "op": "platforms/delete-review-platform-config",
      "method": "DELETE",
      "path": "/platforms/reviews/configs",
      "summary": "Delete Review Platform Config",
      "destructive": true
    },
    "prepare_review_platform_connect": {
      "op": "platforms/prepare-review-platform-connect",
      "method": "POST",
      "path": "/platforms/reviews/configs/prepare",
      "summary": "Prepare Review Platform Connect",
      "destructive": false
    },
    "consume_review_platform_connect": {
      "op": "platforms/consume-review-platform-connect",
      "method": "POST",
      "path": "/platforms/reviews/configs/consume",
      "summary": "Consume Review Platform Connect",
      "destructive": false
    },
    "sync_platform_reviews": {
      "op": "platforms/sync-platform-reviews",
      "method": "POST",
      "path": "/platforms/reviews/configs/manually-sync-reviews",
      "summary": "Manually Sync Platform Reviews",
      "destructive": false
    },
    "fetch_platform_reviews": {
      "op": "platforms/fetch-platform-reviews",
      "method": "POST",
      "path": "/platforms/reviews",
      "summary": "Fetch Platform Reviews",
      "destructive": false
    },
    "get_feed_platform_configs": {
      "op": "platforms/get-feed-platform-configs",
      "method": "GET",
      "path": "/platforms/feeds/configs",
      "summary": "Get Feed Platform Configs",
      "destructive": false
    },
    "save_feed_platform_config": {
      "op": "platforms/save-feed-platform-config",
      "method": "POST",
      "path": "/platforms/feeds/configs",
      "summary": "Save Feed Platform Config",
      "destructive": false
    },
    "delete_feed_platform_config": {
      "op": "platforms/delete-feed-platform-config",
      "method": "DELETE",
      "path": "/platforms/feeds/configs",
      "summary": "Delete Feed Platform Config",
      "destructive": true
    },
    "prepare_feed_platform_connect": {
      "op": "platforms/prepare-feed-platform-connect",
      "method": "POST",
      "path": "/platforms/feeds/configs/prepare",
      "summary": "Prepare Feed Platform Connect",
      "destructive": false
    },
    "consume_feed_platform_connect": {
      "op": "platforms/consume-feed-platform-connect",
      "method": "POST",
      "path": "/platforms/feeds/configs/consume",
      "summary": "Consume Feed Platform Connect",
      "destructive": false
    }
  },
  "social_chat_widgets": {
    "list_chat_widgets": {
      "op": "chat-widgets/list-chat-widgets",
      "method": "GET",
      "path": "/chat-widgets",
      "summary": "List Chat Widgets",
      "destructive": false
    },
    "create_chat_widget": {
      "op": "chat-widgets/create-chat-widget",
      "method": "POST",
      "path": "/chat-widgets",
      "summary": "Create Chat Widget",
      "destructive": false
    },
    "update_chat_widget_statuses": {
      "op": "chat-widgets/update-chat-widget-statuses",
      "method": "PUT",
      "path": "/chat-widgets",
      "summary": "Update Chat Widget Statuses",
      "destructive": false
    },
    "delete_chat_widgets": {
      "op": "chat-widgets/delete-chat-widgets",
      "method": "DELETE",
      "path": "/chat-widgets",
      "summary": "Delete Chat Widgets",
      "destructive": true
    },
    "duplicate_chat_widget": {
      "op": "chat-widgets/duplicate-chat-widget",
      "method": "POST",
      "path": "/chat-widgets/duplicate",
      "summary": "Duplicate Chat Widget",
      "destructive": false
    },
    "get_chat_widget": {
      "op": "chat-widgets/get-chat-widget",
      "method": "GET",
      "path": "/chat-widgets/meta/chats/{id}",
      "summary": "Get Chat Widget Meta",
      "destructive": false
    },
    "update_chat_widget": {
      "op": "chat-widgets/update-chat-widget",
      "method": "PUT",
      "path": "/chat-widgets/meta/chats/{id}",
      "summary": "Update Chat Widget Meta",
      "destructive": false
    },
    "reset_chat_widget": {
      "op": "chat-widgets/reset-chat-widget",
      "method": "DELETE",
      "path": "/chat-widgets/meta/chats/{id}/edit",
      "summary": "Reset Chat Widget Meta",
      "destructive": true
    }
  },
  "social_notifications": {
    "list_notifications": {
      "op": "notifications/list-notifications",
      "method": "GET",
      "path": "/notifications",
      "summary": "List Notifications",
      "destructive": false
    },
    "create_notification": {
      "op": "notifications/create-notification",
      "method": "POST",
      "path": "/notifications",
      "summary": "Create Notification",
      "destructive": false
    },
    "update_notification": {
      "op": "notifications/update-notification",
      "method": "PUT",
      "path": "/notifications",
      "summary": "Update Notification",
      "destructive": false
    },
    "delete_notifications": {
      "op": "notifications/delete-notifications",
      "method": "DELETE",
      "path": "/notifications",
      "summary": "Delete Notifications",
      "destructive": true
    },
    "duplicate_notification": {
      "op": "notifications/duplicate-notification",
      "method": "POST",
      "path": "/notifications/duplicate",
      "summary": "Duplicate Notification",
      "destructive": false
    }
  },
  "social_shoppable": {
    "get_shoppable_feed": {
      "op": "shoppable/get-shoppable-feed",
      "method": "GET",
      "path": "/shoppable",
      "summary": "Get Shoppable Feed",
      "destructive": false
    },
    "update_shoppable_feed": {
      "op": "shoppable/update-shoppable-feed",
      "method": "PUT",
      "path": "/shoppable",
      "summary": "Update Shoppable Feed",
      "destructive": false
    },
    "delete_shoppable_feed": {
      "op": "shoppable/delete-shoppable-feed",
      "method": "DELETE",
      "path": "/shoppable",
      "summary": "Delete Shoppable Feed",
      "destructive": true
    },
    "list_shoppable_posts": {
      "op": "shoppable/list-shoppable-posts",
      "method": "GET",
      "path": "/shoppable/posts",
      "summary": "List Shoppable Posts",
      "destructive": false
    },
    "update_shoppable_template_settings": {
      "op": "shoppable/update-shoppable-template-settings",
      "method": "PUT",
      "path": "/shoppable/template-settings/{id}",
      "summary": "Update Shoppable Template Settings",
      "destructive": false
    }
  },
  "social_settings": {
    "get_settings": {
      "op": "settings/get-settings",
      "method": "GET",
      "path": "/settings",
      "summary": "Get Global Settings",
      "destructive": false
    },
    "save_settings": {
      "op": "settings/save-settings",
      "method": "PUT",
      "path": "/settings",
      "summary": "Save Global Settings",
      "destructive": false
    },
    "delete_settings": {
      "op": "settings/delete-settings",
      "method": "DELETE",
      "path": "/settings",
      "summary": "Delete Global Settings",
      "destructive": true
    },
    "get_advanced_settings": {
      "op": "settings/get-advanced-settings",
      "method": "GET",
      "path": "/settings/advance-settings",
      "summary": "Get Advanced Settings",
      "destructive": false
    },
    "save_advanced_settings": {
      "op": "settings/save-advanced-settings",
      "method": "POST",
      "path": "/settings/advance-settings",
      "summary": "Save Advanced Settings",
      "destructive": false
    },
    "get_translations": {
      "op": "settings/get-translations",
      "method": "GET",
      "path": "/settings/translations",
      "summary": "Get Translations",
      "destructive": false
    },
    "save_translations": {
      "op": "settings/save-translations",
      "method": "POST",
      "path": "/settings/translations",
      "summary": "Save Translations",
      "destructive": false
    },
    "get_license": {
      "op": "settings/get-license",
      "method": "GET",
      "path": "/settings/license",
      "summary": "Get License",
      "destructive": false
    },
    "activate_license": {
      "op": "settings/activate-license",
      "method": "POST",
      "path": "/settings/license",
      "summary": "Activate License",
      "destructive": false
    },
    "deactivate_license": {
      "op": "settings/deactivate-license",
      "method": "DELETE",
      "path": "/settings/license",
      "summary": "Deactivate License",
      "destructive": true
    },
    "delete_twitter_card": {
      "op": "settings/delete-twitter-card",
      "method": "DELETE",
      "path": "/settings/twitter-card",
      "summary": "Delete Twitter Card Connection",
      "destructive": true
    },
    "reset_cached_images": {
      "op": "settings/reset-cached-images",
      "method": "DELETE",
      "path": "/settings/reset-images",
      "summary": "Reset Cached Images",
      "destructive": true
    },
    "reset_error_log": {
      "op": "settings/reset-error-log",
      "method": "DELETE",
      "path": "/settings/reset-error-log",
      "summary": "Reset Error Log",
      "destructive": true
    },
    "delete_all_data": {
      "op": "settings/delete-all-data",
      "method": "DELETE",
      "path": "/settings/delete-all-data",
      "summary": "Delete All Plugin Data",
      "destructive": true
    },
    "search_pages": {
      "op": "settings/search-pages",
      "method": "GET",
      "path": "/pages/search",
      "summary": "Search Site Pages",
      "destructive": false
    },
    "list_managers": {
      "op": "settings/list-managers",
      "method": "GET",
      "path": "/pro/settings/managers",
      "summary": "List Managers",
      "destructive": false
    },
    "add_manager": {
      "op": "settings/add-manager",
      "method": "POST",
      "path": "/pro/settings/managers",
      "summary": "Add Manager",
      "destructive": true,
      "bodyNote": "Privilege/code change: Grants a WordPress user WP Social Ninja manager access. Requires confirm:true."
    },
    "update_manager": {
      "op": "settings/update-manager",
      "method": "PUT",
      "path": "/pro/settings/managers",
      "summary": "Update Manager",
      "destructive": true,
      "bodyNote": "Privilege/code change: Changes a manager's permissions. Requires confirm:true."
    },
    "delete_manager": {
      "op": "settings/delete-manager",
      "method": "DELETE",
      "path": "/pro/settings/managers/{id}",
      "summary": "Delete Manager",
      "destructive": true
    },
    "get_onboarding": {
      "op": "onboarding/get-onboarding",
      "method": "GET",
      "path": "/onboarding",
      "summary": "Get Onboarding State",
      "destructive": false
    },
    "save_onboarding": {
      "op": "onboarding/save-onboarding",
      "method": "POST",
      "path": "/onboarding",
      "summary": "Save Onboarding Step",
      "destructive": false
    },
    "get_onboarding_config": {
      "op": "onboarding/get-onboarding-config",
      "method": "GET",
      "path": "/onboarding/config",
      "summary": "Get Onboarding Config",
      "destructive": false
    },
    "skip_onboarding": {
      "op": "onboarding/skip-onboarding",
      "method": "POST",
      "path": "/onboarding/skip",
      "summary": "Skip Onboarding",
      "destructive": false
    }
  },
  "social_collection": {
    "list_review_forms": {
      "op": "collection/list-review-forms",
      "method": "GET",
      "path": "/pro/review-forms",
      "summary": "List Review Forms",
      "destructive": false
    },
    "create_review_form": {
      "op": "collection/create-review-form",
      "method": "POST",
      "path": "/pro/review-forms",
      "summary": "Create Review Form",
      "destructive": false
    },
    "delete_review_forms": {
      "op": "collection/delete-review-forms",
      "method": "DELETE",
      "path": "/pro/review-forms",
      "summary": "Delete Review Forms",
      "destructive": true
    },
    "get_review_form": {
      "op": "collection/get-review-form",
      "method": "GET",
      "path": "/pro/review-forms/{id}",
      "summary": "Get Review Form",
      "destructive": false
    },
    "update_review_form": {
      "op": "collection/update-review-form",
      "method": "PUT",
      "path": "/pro/review-forms/{id}",
      "summary": "Update Review Form",
      "destructive": false
    },
    "duplicate_review_form": {
      "op": "collection/duplicate-review-form",
      "method": "POST",
      "path": "/pro/review-forms/{id}/duplicate",
      "summary": "Duplicate Review Form",
      "destructive": false
    },
    "update_review_form_statuses": {
      "op": "collection/update-review-form-statuses",
      "method": "PUT",
      "path": "/pro/review-forms/status-update",
      "summary": "Update Review Form Statuses",
      "destructive": false
    },
    "list_custom_sources": {
      "op": "collection/list-custom-sources",
      "method": "GET",
      "path": "/pro/custom-sources",
      "summary": "List Custom Sources",
      "destructive": false
    },
    "create_custom_source": {
      "op": "collection/create-custom-source",
      "method": "POST",
      "path": "/pro/custom-sources",
      "summary": "Create Custom Source",
      "destructive": false
    },
    "delete_custom_sources": {
      "op": "collection/delete-custom-sources",
      "method": "DELETE",
      "path": "/pro/custom-sources",
      "summary": "Delete Custom Sources",
      "destructive": true
    },
    "get_custom_source": {
      "op": "collection/get-custom-source",
      "method": "GET",
      "path": "/pro/custom-sources/{id}",
      "summary": "Get Custom Source",
      "destructive": false
    },
    "save_custom_source_settings": {
      "op": "collection/save-custom-source-settings",
      "method": "POST",
      "path": "/pro/custom-sources/{id}/settings",
      "summary": "Save Custom Source Settings",
      "destructive": false
    },
    "list_custom_source_form_templates": {
      "op": "collection/list-custom-source-form-templates",
      "method": "GET",
      "path": "/pro/custom-sources/forms/templates",
      "summary": "List Custom Source Form Templates",
      "destructive": false
    },
    "list_qr_codes": {
      "op": "collection/list-qr-codes",
      "method": "GET",
      "path": "/pro/settings/get-reviews/qr-code",
      "summary": "List Get-Reviews QR Codes",
      "destructive": false
    },
    "create_qr_code": {
      "op": "collection/create-qr-code",
      "method": "POST",
      "path": "/pro/settings/get-reviews/qr-code",
      "summary": "Create Get-Reviews QR Code",
      "destructive": false
    },
    "update_qr_code": {
      "op": "collection/update-qr-code",
      "method": "PUT",
      "path": "/pro/settings/get-reviews/qr-code/{id}",
      "summary": "Update Get-Reviews QR Code",
      "destructive": false
    },
    "delete_qr_code": {
      "op": "collection/delete-qr-code",
      "method": "DELETE",
      "path": "/pro/settings/get-reviews/qr-code/{id}",
      "summary": "Delete Get-Reviews QR Code",
      "destructive": true
    },
    "list_review_collection_platforms": {
      "op": "collection/list-review-collection-platforms",
      "method": "GET",
      "path": "/pro/settings/get-reviews/get-review-collection-platforms",
      "summary": "List Review Collection Platforms",
      "destructive": false
    },
    "get_review_form_captcha": {
      "op": "collection/get-review-form-captcha",
      "method": "GET",
      "path": "/pro/settings/review-form-captcha",
      "summary": "Get Review Form Captcha",
      "destructive": false
    },
    "save_review_form_captcha": {
      "op": "collection/save-review-form-captcha",
      "method": "POST",
      "path": "/pro/settings/review-form-captcha",
      "summary": "Save Review Form Captcha",
      "destructive": false
    },
    "delete_review_form_captcha": {
      "op": "collection/delete-review-form-captcha",
      "method": "DELETE",
      "path": "/pro/settings/review-form-captcha",
      "summary": "Delete Review Form Captcha",
      "destructive": true
    },
    "get_fluentcrm_review_tag": {
      "op": "collection/get-fluentcrm-review-tag",
      "method": "GET",
      "path": "/pro/settings/fluentcrm-review-tag",
      "summary": "Get FluentCRM Review Tag",
      "destructive": false
    },
    "save_fluentcrm_review_tag": {
      "op": "collection/save-fluentcrm-review-tag",
      "method": "POST",
      "path": "/pro/settings/fluentcrm-review-tag",
      "summary": "Save FluentCRM Review Tag",
      "destructive": false
    },
    "import_woocommerce_reviews": {
      "op": "collection/import-woocommerce-reviews",
      "method": "POST",
      "path": "/pro/settings/woocommerce/import-reviews",
      "summary": "Import WooCommerce Reviews",
      "destructive": false
    },
    "restart_woocommerce_import": {
      "op": "collection/restart-woocommerce-import",
      "method": "POST",
      "path": "/pro/settings/woocommerce/restart-import-reviews",
      "summary": "Restart WooCommerce Review Import",
      "destructive": false
    },
    "get_woocommerce_import_progress": {
      "op": "collection/get-woocommerce-import-progress",
      "method": "GET",
      "path": "/pro/settings/woocommerce/import-progress",
      "summary": "Get WooCommerce Import Progress",
      "destructive": false
    },
    "quick_setup_woocommerce": {
      "op": "collection/quick-setup-woocommerce",
      "method": "POST",
      "path": "/pro/settings/woocommerce/quick-setup",
      "summary": "Quick Setup WooCommerce Reviews",
      "destructive": false
    },
    "quick_setup_fluent_cart": {
      "op": "collection/quick-setup-fluent-cart",
      "method": "POST",
      "path": "/pro/settings/fluent-cart/quick-setup",
      "summary": "Quick Setup FluentCart Reviews",
      "destructive": false
    },
    "connect_fluent_cart_products": {
      "op": "collection/connect-fluent-cart-products",
      "method": "POST",
      "path": "/pro/settings/fluent-cart/connect-all-products",
      "summary": "Connect All FluentCart Products",
      "destructive": false
    }
  }
};

export const TOOL_META: Record<string, { description: string; note?: string; idempotent?: boolean }> = {
  "social_reviews": {
    "description": "Manage the reviews collected from connected platforms: list, edit, duplicate, categorize, change status, or mark as spam."
  },
  "social_testimonials": {
    "description": "Manage hand-written testimonials, their statuses, spam flags, and categories."
  },
  "social_templates": {
    "description": "Manage the review and social-feed widget templates rendered on the site via shortcodes and blocks."
  },
  "social_platforms": {
    "description": "Connect review and feed platforms (Google, Facebook, Instagram, …), manage their configs, and sync their content."
  },
  "social_chat_widgets": {
    "description": "Manage floating chat widgets (WhatsApp, Messenger, Telegram, …) shown on the site."
  },
  "social_notifications": {
    "description": "Manage sales/social-proof notification popups."
  },
  "social_shoppable": {
    "description": "Manage the shoppable Instagram feed and its product-tagged posts."
  },
  "social_settings": {
    "description": "Global WP Social Ninja settings: general and advanced options, translations, licensing, managers, resets, and the onboarding wizard.",
    "note": "The manager endpoints (/pro/settings/managers) require WP Social Ninja Pro."
  },
  "social_collection": {
    "description": "Collect new reviews: review forms, custom sources, get-reviews QR codes, form captcha, FluentCRM tagging, and WooCommerce/FluentCart review imports.",
    "note": "Requires WP Social Ninja Pro (all endpoints live under /pro/)."
  }
};
